// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { FilterResponseSchema, type FilterResponse } from "./filters.js";
import {
  MMADetectorResponseSchema,
  type MMADetectorResponse,
} from "./mmadetectors.js";
import { StreamResponseSchema, type StreamResponse } from "./streams.js";

export const EphemerisResponseSchema = v.strictObject({
  sunset_utc: v.nullish(v.string()),
  sunrise_utc: v.nullish(v.string()),
  twilight_morning_astronomical_utc: v.nullish(v.string()),
  twilight_evening_astronomical_utc: v.nullish(v.string()),
  twilight_morning_nautical_utc: v.nullish(v.string()),
  twilight_evening_nautical_utc: v.nullish(v.string()),
  utc_offset_hours: v.nullish(v.number()),
  sunset_unix_ms: v.nullish(v.number()),
  sunrise_unix_ms: v.nullish(v.number()),
  twilight_morning_astronomical_unix_ms: v.nullish(v.number()),
  twilight_evening_astronomical_unix_ms: v.nullish(v.number()),
  twilight_morning_nautical_unix_ms: v.nullish(v.number()),
  twilight_evening_nautical_unix_ms: v.nullish(v.number()),
});

/**
 * Sun/twilight times computed for a telescope's site.
 *
 * Every value is None when the telescope has no usable observer (no fixed
 * location, or missing coordinates), in which case an empty object is sent.
 */
export type EphemerisResponse = v.InferOutput<typeof EphemerisResponseSchema>;

export const InstrumentFieldResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  instrument_id: v.nullish(v.number()),
  field_id: v.nullish(v.number()),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  contour: v.nullish(v.record(v.string(), v.unknown())),
  contour_summary: v.nullish(v.record(v.string(), v.unknown())),
  reference_filters: v.nullish(v.array(v.string())),
  reference_filter_mags: v.nullish(v.array(v.number())),
  tiles: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  airmass: v.nullish(v.number()),
});

/**
 * One field (pointing) of an instrument.
 *
 * ``contour`` and ``contour_summary`` are deferred and only present when the
 * request asked for GeoJSON. ``airmass`` is injected when the fields are
 * sliced by a localization.
 */
export type InstrumentFieldResponse = v.InferOutput<
  typeof InstrumentFieldResponseSchema
>;

export const GroupMemberResponseSchema = v.strictObject({
  id: v.number(),
  username: v.nullish(v.string()),
  first_name: v.nullish(v.string()),
  last_name: v.nullish(v.string()),
  contact_email: v.nullish(v.string()),
  contact_phone: v.nullish(v.string()),
  oauth_uid: v.nullish(v.string()),
  admin: v.nullish(v.boolean()),
  can_save: v.nullish(v.boolean()),
  can_share_photometry: v.nullish(v.boolean()),
});

/** A group member as assembled by the ``GET /api/groups/{id}`` handler. */
export type GroupMemberResponse = v.InferOutput<
  typeof GroupMemberResponseSchema
>;

/** A SkyPortal group. */
export type GroupResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  name: string;
  nickname?: string | null | undefined;
  description?: string | null | undefined;
  private?: boolean | null | undefined;
  auto_accept_requests?: boolean | null | undefined;
  discoverable_data?: boolean | null | undefined;
  single_user_group?: boolean | undefined;
  streams?: StreamResponse[] | null | undefined;
  filters?: FilterResponse[] | null | undefined;
  group_users?: GroupUserResponse[] | null | undefined;
  users?: GroupMemberResponse[] | null | undefined;
};

export const GroupResponseSchema: v.GenericSchema<GroupResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    name: v.string(),
    nickname: v.nullish(v.string()),
    description: v.nullish(v.string()),
    private: v.nullish(v.boolean()),
    auto_accept_requests: v.nullish(v.boolean()),
    discoverable_data: v.nullish(v.boolean()),
    single_user_group: v.optional(v.boolean()),
    streams: v.nullish(v.array(StreamResponseSchema)),
    filters: v.nullish(v.array(FilterResponseSchema)),
    group_users: v.nullish(v.array(v.lazy(() => GroupUserResponseSchema))),
    users: v.nullish(v.array(GroupMemberResponseSchema)),
  });

/** A user's membership of a group (the ``GroupUser`` join model). */
export type GroupUserResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  group_id?: number | null | undefined;
  user_id?: number | null | undefined;
  admin?: boolean | null | undefined;
  can_save?: boolean | null | undefined;
  can_share_photometry?: boolean | null | undefined;
  user?: UserResponse | null | undefined;
  group?: GroupResponse | null | undefined;
};

export const GroupUserResponseSchema: v.GenericSchema<GroupUserResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    group_id: v.nullish(v.number()),
    user_id: v.nullish(v.number()),
    admin: v.nullish(v.boolean()),
    can_save: v.nullish(v.boolean()),
    can_share_photometry: v.nullish(v.boolean()),
    user: v.nullish(v.lazy(() => UserResponseSchema)),
    group: v.nullish(v.lazy(() => GroupResponseSchema)),
  });

/** A SkyPortal user (baselayer ``User``). */
export type UserResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  username: string;
  first_name?: string | null | undefined;
  last_name?: string | null | undefined;
  bio?: string | null | undefined;
  affiliations?: string[] | undefined;
  contact_email?: string | null | undefined;
  contact_phone?: string | null | undefined;
  oauth_uid?: string | null | undefined;
  is_bot?: boolean | null | undefined;
  expiration_date?: string | null | undefined;
  permissions?: string[] | undefined;
  roles?: string[] | undefined;
  acls?: string[] | undefined;
  gravatar_url?: string | null | undefined;
  groups?: GroupResponse[] | string[] | null | undefined;
  streams?: StreamResponse[] | null | undefined;
};

export const UserResponseSchema: v.GenericSchema<UserResponse> = v.strictObject(
  {
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    username: v.string(),
    first_name: v.nullish(v.string()),
    last_name: v.nullish(v.string()),
    bio: v.nullish(v.string()),
    affiliations: v.optional(v.array(v.string())),
    contact_email: v.nullish(v.string()),
    contact_phone: v.nullish(v.string()),
    oauth_uid: v.nullish(v.string()),
    is_bot: v.nullish(v.boolean()),
    expiration_date: v.nullish(v.string()),
    permissions: v.optional(v.array(v.string())),
    roles: v.optional(v.array(v.string())),
    acls: v.optional(v.array(v.string())),
    gravatar_url: v.nullish(v.string()),
    groups: v.optional(
      v.union([
        v.array(v.lazy(() => GroupResponseSchema)),
        v.array(v.string()),
        v.null(),
      ]),
    ),
    streams: v.nullish(v.array(StreamResponseSchema)),
  },
);

/**
 * An observing-time allocation on an instrument.
 *
 * ``allocation_users`` is a list of plain users: every handler that
 * serializes it (allocation and telescope alike) substitutes
 * ``allocation_user.user`` for the join row. ``requests``, ``default_requests``, ``default_observation_plans``,
 * ``catalog_queries``, ``observation_plans``, ``gcn_triggers`` and ``group``
 * stay untyped: those models point back at ``Allocation``, so typing them
 * would risk an import cycle. ``requests``, ``ephemeris`` and ``telescope``
 * are injected by the single-allocation endpoint. The encrypted ``_altdata``
 * column is never serialized.
 */
export type AllocationResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  pi?: string | null | undefined;
  proposal_id?: string | null | undefined;
  hours_allocated?: number | null | undefined;
  validity_ranges?: Record<string, unknown>[] | null | undefined;
  default_share_group_ids?: number[] | null | undefined;
  types?:
    | ("triggered" | "forced_photometry" | "observation_plan")[]
    | null
    | undefined;
  group_id: number;
  instrument_id: number;
  instrument?: InstrumentResponse | null | undefined;
  allocation_users?: UserResponse[] | null | undefined;
  group?: Record<string, unknown> | null | undefined;
  requests?: Record<string, unknown>[] | null | undefined;
  default_requests?: Record<string, unknown>[] | null | undefined;
  default_observation_plans?: Record<string, unknown>[] | null | undefined;
  catalog_queries?: Record<string, unknown>[] | null | undefined;
  observation_plans?: Record<string, unknown>[] | null | undefined;
  gcn_triggers?: Record<string, unknown>[] | null | undefined;
  ephemeris?: EphemerisResponse | null | undefined;
  telescope?: TelescopeResponse | null | undefined;
};

export const AllocationResponseSchema: v.GenericSchema<AllocationResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    pi: v.nullish(v.string()),
    proposal_id: v.nullish(v.string()),
    hours_allocated: v.nullish(v.number()),
    validity_ranges: v.nullish(v.array(v.record(v.string(), v.unknown()))),
    default_share_group_ids: v.nullish(v.array(v.number())),
    types: v.nullish(
      v.array(
        v.picklist(["triggered", "forced_photometry", "observation_plan"]),
      ),
    ),
    group_id: v.number(),
    instrument_id: v.number(),
    instrument: v.nullish(v.lazy(() => InstrumentResponseSchema)),
    allocation_users: v.nullish(v.array(UserResponseSchema)),
    group: v.nullish(v.record(v.string(), v.unknown())),
    requests: v.nullish(v.array(v.record(v.string(), v.unknown()))),
    default_requests: v.nullish(v.array(v.record(v.string(), v.unknown()))),
    default_observation_plans: v.nullish(
      v.array(v.record(v.string(), v.unknown())),
    ),
    catalog_queries: v.nullish(v.array(v.record(v.string(), v.unknown()))),
    observation_plans: v.nullish(v.array(v.record(v.string(), v.unknown()))),
    gcn_triggers: v.nullish(v.array(v.record(v.string(), v.unknown()))),
    ephemeris: v.nullish(EphemerisResponseSchema),
    telescope: v.nullish(v.lazy(() => TelescopeResponseSchema)),
  });

/**
 * An instrument, as returned by the instrument endpoints.
 *
 * ``log_exists``, ``number_of_fields`` and ``region_summary`` are injected
 * by the instrument endpoints rather than being columns.
 */
export type InstrumentResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  name?: string | null | undefined;
  type?: "imager" | "spectrograph" | "imaging spectrograph" | null | undefined;
  band?: string | null | undefined;
  acknowledgment?: string | null | undefined;
  telescope_id?: number | null | undefined;
  telescope?: TelescopeResponse | null | undefined;
  filters?: string[] | undefined;
  sensitivity_data?: Record<string, unknown> | null | undefined;
  configuration_data?: Record<string, unknown> | null | undefined;
  status?: Record<string, unknown> | null | undefined;
  last_status_update?: string | null | undefined;
  api_classname?: string | null | undefined;
  api_classname_obsplan?: string | null | undefined;
  listener_classname?: string | null | undefined;
  treasuremap_id?: number | null | undefined;
  tns_id?: number | null | undefined;
  across_id?: string | null | undefined;
  region?: string | null | undefined;
  has_fields?: boolean | null | undefined;
  has_region?: boolean | null | undefined;
  fields?: InstrumentFieldResponse[] | null | undefined;
  allocations?: AllocationResponse[] | null | undefined;
  log_exists?: boolean | null | undefined;
  number_of_fields?: number | null | undefined;
  region_summary?: string | null | undefined;
};

export const InstrumentResponseSchema: v.GenericSchema<InstrumentResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    name: v.nullish(v.string()),
    type: v.nullish(
      v.picklist(["imager", "spectrograph", "imaging spectrograph"]),
    ),
    band: v.nullish(v.string()),
    acknowledgment: v.nullish(v.string()),
    telescope_id: v.nullish(v.number()),
    telescope: v.nullish(v.lazy(() => TelescopeResponseSchema)),
    filters: v.optional(v.array(v.string())),
    sensitivity_data: v.nullish(v.record(v.string(), v.unknown())),
    configuration_data: v.nullish(v.record(v.string(), v.unknown())),
    status: v.nullish(v.record(v.string(), v.unknown())),
    last_status_update: v.nullish(v.string()),
    api_classname: v.nullish(v.string()),
    api_classname_obsplan: v.nullish(v.string()),
    listener_classname: v.nullish(v.string()),
    treasuremap_id: v.nullish(v.number()),
    tns_id: v.nullish(v.number()),
    across_id: v.nullish(v.string()),
    region: v.nullish(v.string()),
    has_fields: v.nullish(v.boolean()),
    has_region: v.nullish(v.boolean()),
    fields: v.nullish(v.array(InstrumentFieldResponseSchema)),
    allocations: v.nullish(v.array(v.lazy(() => AllocationResponseSchema))),
    log_exists: v.nullish(v.boolean()),
    number_of_fields: v.nullish(v.number()),
    region_summary: v.nullish(v.string()),
  });

/** A telescope, as returned by the telescope endpoints. */
export type TelescopeResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  name: string;
  nickname?: string | null | undefined;
  lat?: number | null | undefined;
  lon?: number | null | undefined;
  elevation?: number | null | undefined;
  mpc_obscode?: string | null | undefined;
  diameter?: number | null | undefined;
  skycam_link?: string | null | undefined;
  weather_link?: string | null | undefined;
  robotic?: boolean | null | undefined;
  fixed_location?: boolean | null | undefined;
  acknowledgment?: string | null | undefined;
  instruments?: InstrumentResponse[] | null | undefined;
  allocations?: AllocationResponse[] | null | undefined;
  is_night_astronomical?: boolean | null | undefined;
  morning?: string | boolean | null | undefined;
  evening?: string | boolean | null | undefined;
};

export const TelescopeResponseSchema: v.GenericSchema<TelescopeResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    name: v.string(),
    nickname: v.nullish(v.string()),
    lat: v.nullish(v.number()),
    lon: v.nullish(v.number()),
    elevation: v.nullish(v.number()),
    mpc_obscode: v.nullish(v.string()),
    diameter: v.nullish(v.number()),
    skycam_link: v.nullish(v.string()),
    weather_link: v.nullish(v.string()),
    robotic: v.nullish(v.boolean()),
    fixed_location: v.nullish(v.boolean()),
    acknowledgment: v.nullish(v.string()),
    instruments: v.nullish(v.array(v.lazy(() => InstrumentResponseSchema))),
    allocations: v.nullish(v.array(v.lazy(() => AllocationResponseSchema))),
    is_night_astronomical: v.nullish(v.boolean()),
    morning: v.optional(v.union([v.string(), v.boolean(), v.null()])),
    evening: v.optional(v.union([v.string(), v.boolean(), v.null()])),
  });

export const ClassificationEditResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  classification_id: v.nullish(v.number()),
  editor_id: v.nullish(v.number()),
  editor_name: v.nullish(v.string()),
  old_probability: v.nullish(v.number()),
  new_probability: v.nullish(v.number()),
});

/** An edit of a classification's probability. */
export type ClassificationEditResponse = v.InferOutput<
  typeof ClassificationEditResponseSchema
>;

export const ClassificationVoteResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  classification_id: v.nullish(v.number()),
  voter_id: v.nullish(v.number()),
  vote: v.nullish(v.number()),
});

/** A vote on a classification. */
export type ClassificationVoteResponse = v.InferOutput<
  typeof ClassificationVoteResponseSchema
>;

/** A classification of a source. */
export type ClassificationResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  obj_id: string;
  classification: string;
  taxonomy_id: number;
  probability?: number | null | undefined;
  author_name?: string | null | undefined;
  author_id?: number | null | undefined;
  origin?: string | null | undefined;
  ml?: boolean | null | undefined;
  taxonomy?: TaxonomyResponse | null | undefined;
  votes?: ClassificationVoteResponse[] | null | undefined;
  edits?: ClassificationEditResponse[] | null | undefined;
  groups?: GroupResponse[] | null | undefined;
  author?: Record<string, unknown> | null | undefined;
  obj?: Record<string, unknown> | null | undefined;
};

export const ClassificationResponseSchema: v.GenericSchema<ClassificationResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    obj_id: v.string(),
    classification: v.string(),
    taxonomy_id: v.number(),
    probability: v.nullish(v.number()),
    author_name: v.nullish(v.string()),
    author_id: v.nullish(v.number()),
    origin: v.nullish(v.string()),
    ml: v.nullish(v.boolean()),
    taxonomy: v.nullish(v.lazy(() => TaxonomyResponseSchema)),
    votes: v.nullish(v.array(ClassificationVoteResponseSchema)),
    edits: v.nullish(v.array(ClassificationEditResponseSchema)),
    groups: v.nullish(v.array(GroupResponseSchema)),
    author: v.nullish(v.record(v.string(), v.unknown())),
    obj: v.nullish(v.record(v.string(), v.unknown())),
  });

/** A classification taxonomy. */
export type TaxonomyResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  name?: string | null | undefined;
  version?: string | null | undefined;
  provenance?: string | null | undefined;
  isLatest?: boolean | null | undefined;
  hierarchy?: Record<string, unknown> | null | undefined;
  groups?: GroupResponse[] | null | undefined;
  classifications?: ClassificationResponse[] | null | undefined;
};

export const TaxonomyResponseSchema: v.GenericSchema<TaxonomyResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    name: v.nullish(v.string()),
    version: v.nullish(v.string()),
    provenance: v.nullish(v.string()),
    isLatest: v.nullish(v.boolean()),
    hierarchy: v.nullish(v.record(v.string(), v.unknown())),
    groups: v.nullish(v.array(GroupResponseSchema)),
    classifications: v.nullish(
      v.array(v.lazy(() => ClassificationResponseSchema)),
    ),
  });

export const CommentResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  text: v.nullish(v.string()),
  channel: v.nullish(v.string()),
  system: v.nullish(v.boolean()),
  attachment_name: v.nullish(v.string()),
  attachment_bytes: v.optional(v.unknown()),
  origin: v.nullish(v.string()),
  bot: v.nullish(v.boolean()),
  author_id: v.nullish(v.number()),
  author: v.nullish(v.record(v.string(), v.unknown())),
  groups: v.nullish(v.array(GroupResponseSchema)),
  obj_id: v.nullish(v.string()),
  spectrum_id: v.nullish(v.number()),
  gcn_id: v.nullish(v.number()),
  earthquake_id: v.nullish(v.number()),
  shift_id: v.nullish(v.number()),
  obj: v.nullish(v.record(v.string(), v.unknown())),
  spectrum: v.nullish(v.record(v.string(), v.unknown())),
  gcn: v.nullish(v.record(v.string(), v.unknown())),
  shift: v.nullish(v.record(v.string(), v.unknown())),
  earthquake: v.nullish(v.record(v.string(), v.unknown())),
  dateobs: v.nullish(v.string()),
  resourceType: v.nullish(v.string()),
});

/**
 * A comment on a source, spectrum, GCN event, shift, or earthquake.
 *
 * Union of the Comment, CommentOnSpectrum, CommentOnGCN, CommentOnShift,
 * and CommentOnEarthquake payloads, so each type-specific foreign key is
 * optional.
 */
export type CommentResponse = v.InferOutput<typeof CommentResponseSchema>;

export const EventObservationPlanStatisticsResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  observation_plan_id: v.nullish(v.number()),
  localization_id: v.nullish(v.number()),
  statistics: v.optional(v.record(v.string(), v.unknown())),
  observation_plan: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * Statistics (sky area, 2D probability, ...) derived from one plan.
 *
 * ``observation_plan`` stays untyped to avoid a recursive model.
 */
export type EventObservationPlanStatisticsResponse = v.InferOutput<
  typeof EventObservationPlanStatisticsResponseSchema
>;

export const PlannedObservationResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  observation_plan_id: v.nullish(v.number()),
  instrument_id: v.nullish(v.number()),
  dateobs: v.nullish(v.string()),
  field_id: v.nullish(v.number()),
  field_db_id: v.nullish(v.number()),
  exposure_time: v.nullish(v.number()),
  weight: v.nullish(v.number()),
  filt: v.nullish(v.string()),
  obstime: v.nullish(v.string()),
  overhead_per_exposure: v.nullish(v.number()),
  planned_observation_id: v.nullish(v.number()),
  rise_time: v.nullish(v.string()),
  set_time: v.nullish(v.string()),
  field: v.nullish(InstrumentFieldResponseSchema),
  instrument: v.nullish(InstrumentResponseSchema),
  observation_plan: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * A single planned exposure of an observation plan.
 *
 * The single-plan handler renames the ``field_id`` foreign key to
 * ``field_db_id`` and puts the instrument's own field number in
 * ``field_id``, then adds ``rise_time``/``set_time`` (empty strings when the
 * field never rises or sets that night). ``observation_plan`` stays untyped
 * to avoid a recursive model.
 */
export type PlannedObservationResponse = v.InferOutput<
  typeof PlannedObservationResponseSchema
>;

/**
 * A generated observation plan.
 *
 * ``observation_plan_request`` stays untyped to avoid a recursive model.
 */
export type EventObservationPlanResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  observation_plan_request_id?: number | null | undefined;
  instrument_id?: number | null | undefined;
  dateobs?: string | null | undefined;
  plan_name?: string | null | undefined;
  validity_window_start?: string | null | undefined;
  validity_window_end?: string | null | undefined;
  status?: string | null | undefined;
  statistics?: EventObservationPlanStatisticsResponse[] | undefined;
  planned_observations?: PlannedObservationResponse[] | undefined;
  survey_efficiency_analyses?:
    SurveyEfficiencyForObservationPlanResponse[] | undefined;
  instrument?: InstrumentResponse | null | undefined;
  observation_plan_request?: Record<string, unknown> | null | undefined;
};

export const EventObservationPlanResponseSchema: v.GenericSchema<EventObservationPlanResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    observation_plan_request_id: v.nullish(v.number()),
    instrument_id: v.nullish(v.number()),
    dateobs: v.nullish(v.string()),
    plan_name: v.nullish(v.string()),
    validity_window_start: v.nullish(v.string()),
    validity_window_end: v.nullish(v.string()),
    status: v.nullish(v.string()),
    statistics: v.optional(
      v.array(EventObservationPlanStatisticsResponseSchema),
    ),
    planned_observations: v.optional(v.array(PlannedObservationResponseSchema)),
    survey_efficiency_analyses: v.optional(
      v.array(v.lazy(() => SurveyEfficiencyForObservationPlanResponseSchema)),
    ),
    instrument: v.nullish(InstrumentResponseSchema),
    observation_plan_request: v.nullish(v.record(v.string(), v.unknown())),
  });

/** An efficiency analysis run over an observation plan. */
export type SurveyEfficiencyForObservationPlanResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  payload?: Record<string, unknown> | undefined;
  status?: string | null | undefined;
  lightcurves?: string | null | undefined;
  requester_id?: number | null | undefined;
  observation_plan_id?: number | null | undefined;
  number_of_transients?: number | null | undefined;
  number_in_covered?: number | null | undefined;
  number_detected?: number | null | undefined;
  efficiency?: number | null | undefined;
  requester?: UserResponse | null | undefined;
  groups?: GroupResponse[] | undefined;
  observation_plan?: EventObservationPlanResponse | null | undefined;
};

export const SurveyEfficiencyForObservationPlanResponseSchema: v.GenericSchema<SurveyEfficiencyForObservationPlanResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    payload: v.optional(v.record(v.string(), v.unknown())),
    status: v.nullish(v.string()),
    lightcurves: v.nullish(v.string()),
    requester_id: v.nullish(v.number()),
    observation_plan_id: v.nullish(v.number()),
    number_of_transients: v.nullish(v.number()),
    number_in_covered: v.nullish(v.number()),
    number_detected: v.nullish(v.number()),
    efficiency: v.nullish(v.number()),
    requester: v.nullish(UserResponseSchema),
    groups: v.optional(v.array(GroupResponseSchema)),
    observation_plan: v.nullish(
      v.lazy(() => EventObservationPlanResponseSchema),
    ),
  });

export const FacilityTransactionRequestResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  last_query: v.nullish(v.string()),
  method: v.nullish(v.string()),
  endpoint: v.nullish(v.string()),
  data: v.nullish(v.record(v.string(), v.unknown())),
  params: v.nullish(v.record(v.string(), v.unknown())),
  headers: v.nullish(v.record(v.string(), v.unknown())),
  status: v.nullish(v.string()),
  followup_request_id: v.nullish(v.number()),
  observation_plan_request_id: v.nullish(v.number()),
  initiator_id: v.nullish(v.number()),
  initiator: v.nullish(UserResponseSchema),
  followup_request: v.nullish(v.record(v.string(), v.unknown())),
  observation_plan_request: v.nullish(v.record(v.string(), v.unknown())),
});

/** A queued facility call (``FacilityTransactionRequest``). */
export type FacilityTransactionRequestResponse = v.InferOutput<
  typeof FacilityTransactionRequestResponseSchema
>;

export const FacilityTransactionResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  request: v.nullish(v.record(v.string(), v.unknown())),
  response: v.nullish(v.record(v.string(), v.unknown())),
  followup_request_id: v.nullish(v.number()),
  observation_plan_request_id: v.nullish(v.number()),
  initiator_id: v.nullish(v.number()),
  initiator: v.nullish(UserResponseSchema),
  followup_request: v.nullish(v.record(v.string(), v.unknown())),
  observation_plan_request: v.nullish(v.record(v.string(), v.unknown())),
});

/** A serialized exchange with a facility (``FacilityTransaction``). */
export type FacilityTransactionResponse = v.InferOutput<
  typeof FacilityTransactionResponseSchema
>;

export const LocalizationPropertyResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sent_by_id: v.nullish(v.number()),
  localization_id: v.nullish(v.number()),
  data: v.nullish(v.record(v.string(), v.unknown())),
  sent_by: v.nullish(UserResponseSchema),
  localization: v.nullish(v.record(v.string(), v.unknown())),
});

/** Properties parsed from a localization. */
export type LocalizationPropertyResponse = v.InferOutput<
  typeof LocalizationPropertyResponseSchema
>;

export const LocalizationTagResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sent_by_id: v.nullish(v.number()),
  localization_id: v.nullish(v.number()),
  text: v.nullish(v.string()),
  sent_by: v.nullish(UserResponseSchema),
  localization: v.nullish(v.record(v.string(), v.unknown())),
});

/** A qualitative tag on a localization. */
export type LocalizationTagResponse = v.InferOutput<
  typeof LocalizationTagResponseSchema
>;

export const LocalizationResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sent_by_id: v.nullish(v.number()),
  dateobs: v.nullish(v.string()),
  localization_name: v.nullish(v.string()),
  uniq: v.nullish(v.array(v.number())),
  probdensity: v.nullish(v.array(v.number())),
  distmu: v.nullish(v.array(v.nullable(v.number()))),
  distsigma: v.nullish(v.array(v.nullable(v.number()))),
  distnorm: v.nullish(v.array(v.nullable(v.number()))),
  contour: v.nullish(v.record(v.string(), v.unknown())),
  notice_id: v.nullish(v.number()),
  flat_2d: v.nullish(v.array(v.number())),
  sent_by: v.nullish(UserResponseSchema),
  properties: v.nullish(v.array(LocalizationPropertyResponseSchema)),
  tags: v.nullish(v.array(LocalizationTagResponseSchema)),
  gcnevent: v.nullish(v.record(v.string(), v.unknown())),
  observationplan_requests: v.nullish(
    v.array(v.record(v.string(), v.unknown())),
  ),
  survey_efficiency_analyses: v.nullish(
    v.array(v.record(v.string(), v.unknown())),
  ),
});

/**
 * A GCN event localization.
 *
 * ``uniq``, ``probdensity``, ``distmu``, ``distsigma``, ``distnorm`` and
 * ``contour`` are deferred, so each is only present when the handler undefers
 * it; the distance arrays are undeferred only by the single-localization
 * endpoint, which also injects ``flat_2d`` (the rasterized 2D skymap) when
 * ``include2DMap`` is set.
 */
export type LocalizationResponse = v.InferOutput<
  typeof LocalizationResponseSchema
>;

export const GcnEventCrossmatchStateResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  gcnevent_id: v.nullish(v.number()),
  filter_id: v.nullish(v.number()),
  localization_id: v.nullish(v.number()),
  last_queried: v.nullish(v.string()),
  last_alert_jd: v.nullish(v.number()),
  status: v.nullish(v.string()),
  error: v.nullish(v.string()),
  archival_done: v.nullish(v.boolean()),
  n_matches: v.nullish(v.number()),
  filter: v.nullish(FilterResponseSchema),
  localization: v.nullish(LocalizationResponseSchema),
  gcnevent: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * Alert-crossmatch progress for one event, filter and localization.
 *
 * ``status`` is one of ``"pending"``, ``"processing"``, ``"done"`` or
 * ``"failed"``, but the column is a plain string, so it is not narrowed here.
 */
export type GcnEventCrossmatchStateResponse = v.InferOutput<
  typeof GcnEventCrossmatchStateResponseSchema
>;

export const LocalizationCenterResponseSchema = v.strictObject({
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  gal_lat: v.nullish(v.number()),
  gal_lon: v.nullish(v.number()),
  ebv: v.nullish(v.number()),
});

/**
 * The center of a localization.
 *
 * ``ebv`` is the Schlegel-Finkbeiner-Davis reddening at that position, and is
 * null when the dust map lookup fails.
 */
export type LocalizationCenterResponse = v.InferOutput<
  typeof LocalizationCenterResponseSchema
>;

export const GcnEventLocalizationResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sent_by_id: v.nullish(v.number()),
  dateobs: v.nullish(v.string()),
  localization_name: v.nullish(v.string()),
  uniq: v.nullish(v.array(v.number())),
  probdensity: v.nullish(v.array(v.number())),
  distmu: v.nullish(v.array(v.nullable(v.number()))),
  distsigma: v.nullish(v.array(v.nullable(v.number()))),
  distnorm: v.nullish(v.array(v.nullable(v.number()))),
  contour: v.nullish(v.record(v.string(), v.unknown())),
  notice_id: v.nullish(v.number()),
  flat_2d: v.nullish(v.array(v.number())),
  sent_by: v.nullish(UserResponseSchema),
  properties: v.nullish(v.array(LocalizationPropertyResponseSchema)),
  tags: v.nullish(v.array(LocalizationTagResponseSchema)),
  gcnevent: v.nullish(v.record(v.string(), v.unknown())),
  observationplan_requests: v.nullish(
    v.array(v.record(v.string(), v.unknown())),
  ),
  survey_efficiency_analyses: v.nullish(
    v.array(v.record(v.string(), v.unknown())),
  ),
  center: v.nullish(LocalizationCenterResponseSchema),
});

/**
 * A localization as returned inside a GCN event payload.
 *
 * The single-event endpoint replaces the localization's ``tags`` and
 * ``properties`` with explicitly serialized lists and adds ``center``; the
 * paginated endpoint returns ``tags`` only.
 */
export type GcnEventLocalizationResponse = v.InferOutput<
  typeof GcnEventLocalizationResponseSchema
>;

export const GcnEventUserResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  gcnevent_id: v.nullish(v.number()),
  user_id: v.nullish(v.number()),
  username: v.nullish(v.string()),
  first_name: v.nullish(v.string()),
  last_name: v.nullish(v.string()),
  user: v.nullish(UserResponseSchema),
  gcnevent: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * A user advocating for a GCN event.
 *
 * ``username``, ``first_name`` and ``last_name`` are copied off the joined
 * user by the single-event endpoint, which returns these rows as
 * ``event_users``.
 */
export type GcnEventUserResponse = v.InferOutput<
  typeof GcnEventUserResponseSchema
>;

export const GcnNoticeResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sent_by_id: v.nullish(v.number()),
  dateobs: v.nullish(v.string()),
  ivorn: v.nullish(v.string()),
  notice_type: v.nullish(v.string()),
  notice_format: v.nullish(v.string()),
  stream: v.nullish(v.string()),
  date: v.nullish(v.string()),
  content: v.optional(v.unknown()),
  has_localization: v.nullish(v.boolean()),
  localization_ingested: v.nullish(v.boolean()),
  sent_by: v.nullish(UserResponseSchema),
  gcnevent: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * A GCN notice attached to an event.
 *
 * ``content`` is the raw notice body (XML, JSON or plain text), decoded from a
 * deferred ``LargeBinary`` column: it is absent unless the handler undefers
 * it, and the single-event endpoint drops it when ``excludeNoticeContent`` is
 * set.
 */
export type GcnNoticeResponse = v.InferOutput<typeof GcnNoticeResponseSchema>;

export const GcnPropertyResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sent_by_id: v.nullish(v.number()),
  dateobs: v.nullish(v.string()),
  data: v.nullish(v.record(v.string(), v.unknown())),
  sent_by: v.nullish(UserResponseSchema),
  gcnevent: v.nullish(v.record(v.string(), v.unknown())),
});

/** Properties parsed from an event notice. */
export type GcnPropertyResponse = v.InferOutput<
  typeof GcnPropertyResponseSchema
>;

export const GcnReportResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sent_by_id: v.nullish(v.number()),
  dateobs: v.nullish(v.string()),
  group_id: v.nullish(v.number()),
  report_name: v.nullish(v.string()),
  data: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  published: v.nullish(v.boolean()),
  sent_by: v.nullish(UserResponseSchema),
  group: v.nullish(GroupResponseSchema),
  gcnevent: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * A structured (publishable) report on a GCN event.
 *
 * ``data`` is a deferred JSONB column, undeferred by the single-report
 * endpoint. It holds ``{"status": "pending"}`` while the report is being
 * assembled and a JSON string once the background writer has stored the
 * rendered report, so both forms are accepted.
 */
export type GcnReportResponse = v.InferOutput<typeof GcnReportResponseSchema>;

export const GcnSummaryResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sent_by_id: v.nullish(v.number()),
  dateobs: v.nullish(v.string()),
  group_id: v.nullish(v.number()),
  title: v.nullish(v.string()),
  text: v.nullish(v.string()),
  sent_by: v.nullish(UserResponseSchema),
  group: v.nullish(GroupResponseSchema),
  gcnevent: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * A human-readable summary of a GCN event.
 *
 * ``text`` is deferred and is undeferred by the single-summary endpoint; it
 * reads ``"pending"`` until the background writer fills it in.
 */
export type GcnSummaryResponse = v.InferOutput<typeof GcnSummaryResponseSchema>;

export const GcnTriggerResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  dateobs: v.nullish(v.string()),
  allocation_id: v.nullish(v.number()),
  triggered: v.nullish(v.boolean()),
  allocation: v.nullish(AllocationResponseSchema),
  gcnevent: v.nullish(v.record(v.string(), v.unknown())),
});

/** Whether a GCN event triggered an allocation. */
export type GcnTriggerResponse = v.InferOutput<typeof GcnTriggerResponseSchema>;

export const ReminderResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  text: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  bot: v.nullish(v.boolean()),
  next_reminder: v.nullish(v.string()),
  reminder_delay: v.nullish(v.number()),
  number_of_reminders: v.nullish(v.number()),
  user_id: v.nullish(v.number()),
  user: v.nullish(v.record(v.string(), v.unknown())),
  groups: v.nullish(v.array(GroupResponseSchema)),
  obj_id: v.nullish(v.string()),
  spectrum_id: v.nullish(v.number()),
  gcn_id: v.nullish(v.number()),
  earthquake_id: v.nullish(v.number()),
  shift_id: v.nullish(v.number()),
  obj: v.nullish(v.record(v.string(), v.unknown())),
  spectrum: v.nullish(v.record(v.string(), v.unknown())),
  gcn: v.nullish(v.record(v.string(), v.unknown())),
  shift: v.nullish(v.record(v.string(), v.unknown())),
  earthquake: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * A reminder on a source, spectrum, GCN event, shift, or earthquake.
 *
 * Union of the Reminder, ReminderOnSpectrum, ReminderOnGCN, ReminderOnShift,
 * and ReminderOnEarthquake payloads, so each type-specific foreign key is
 * optional.
 */
export type ReminderResponse = v.InferOutput<typeof ReminderResponseSchema>;

/**
 * A GCN event, keyed by its UTC observation time.
 *
 * ``tags`` (the distinct texts of the event's ``GcnTag`` rows) and
 * ``lightcurve`` (a URL parsed out of the first notice) are properties the
 * handlers inject rather than columns; the underlying ``_tags`` relationship
 * is never serialized. ``circulars``, ``gracedb_log`` and ``gracedb_labels``
 * are deferred, so they only appear when a handler undefers them.
 * ``event_users_ids`` is a column property aggregating ``gcnevent_users``,
 * and ``event_users`` is the same join rows with the user's name copied in.
 * ``summary`` is the event's editable summary text and ``summary_history``
 * its prior versions; the ``summaries`` list is the separate ``GcnSummary``
 * rows.
 */
export type GcnEventResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  sent_by_id?: number | null | undefined;
  dateobs?: string | null | undefined;
  trigger_id?: string | null | undefined;
  aliases?: string[] | null | undefined;
  tach_id?: string | null | undefined;
  summary?: string | null | undefined;
  summary_history?: Record<string, unknown>[] | null | undefined;
  circulars?: Record<string, string> | null | undefined;
  gracedb_log?: Record<string, unknown> | null | undefined;
  gracedb_labels?: Record<string, unknown> | null | undefined;
  lightcurve?: string | null | undefined;
  event_users_ids?: number[] | null | undefined;
  tags?: string[] | null | undefined;
  localizations?: GcnEventLocalizationResponse[] | null | undefined;
  gcn_notices?: GcnNoticeResponse[] | null | undefined;
  properties?: GcnPropertyResponse[] | null | undefined;
  summaries?: GcnSummaryResponse[] | null | undefined;
  reports?: GcnReportResponse[] | null | undefined;
  comments?: CommentResponse[] | null | undefined;
  reminders?: ReminderResponse[] | null | undefined;
  detectors?: MMADetectorResponse[] | null | undefined;
  gcn_triggers?: GcnTriggerResponse[] | null | undefined;
  event_users?: GcnEventUserResponse[] | null | undefined;
  gcnevent_users?: GcnEventUserResponse[] | null | undefined;
  users?: UserResponse[] | null | undefined;
  groups?: GroupResponse[] | null | undefined;
  sent_by?: UserResponse | null | undefined;
  observationplan_requests?:
    ObservationPlanRequestResponse[] | null | undefined;
  survey_efficiency_analyses?:
    SurveyEfficiencyForObservationsResponse[] | null | undefined;
  crossmatch_states?: GcnEventCrossmatchStateResponse[] | null | undefined;
};

export const GcnEventResponseSchema: v.GenericSchema<GcnEventResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    sent_by_id: v.nullish(v.number()),
    dateobs: v.nullish(v.string()),
    trigger_id: v.nullish(v.string()),
    aliases: v.nullish(v.array(v.string())),
    tach_id: v.nullish(v.string()),
    summary: v.nullish(v.string()),
    summary_history: v.nullish(v.array(v.record(v.string(), v.unknown()))),
    circulars: v.nullish(v.record(v.string(), v.string())),
    gracedb_log: v.nullish(v.record(v.string(), v.unknown())),
    gracedb_labels: v.nullish(v.record(v.string(), v.unknown())),
    lightcurve: v.nullish(v.string()),
    event_users_ids: v.nullish(v.array(v.number())),
    tags: v.nullish(v.array(v.string())),
    localizations: v.nullish(v.array(GcnEventLocalizationResponseSchema)),
    gcn_notices: v.nullish(v.array(GcnNoticeResponseSchema)),
    properties: v.nullish(v.array(GcnPropertyResponseSchema)),
    summaries: v.nullish(v.array(GcnSummaryResponseSchema)),
    reports: v.nullish(v.array(GcnReportResponseSchema)),
    comments: v.nullish(v.array(CommentResponseSchema)),
    reminders: v.nullish(v.array(ReminderResponseSchema)),
    detectors: v.nullish(v.array(MMADetectorResponseSchema)),
    gcn_triggers: v.nullish(v.array(GcnTriggerResponseSchema)),
    event_users: v.nullish(v.array(GcnEventUserResponseSchema)),
    gcnevent_users: v.nullish(v.array(GcnEventUserResponseSchema)),
    users: v.nullish(v.array(UserResponseSchema)),
    groups: v.nullish(v.array(GroupResponseSchema)),
    sent_by: v.nullish(UserResponseSchema),
    observationplan_requests: v.nullish(
      v.array(v.lazy(() => ObservationPlanRequestResponseSchema)),
    ),
    survey_efficiency_analyses: v.nullish(
      v.array(v.lazy(() => SurveyEfficiencyForObservationsResponseSchema)),
    ),
    crossmatch_states: v.nullish(
      v.array(GcnEventCrossmatchStateResponseSchema),
    ),
  });

/**
 * A request for an observation plan.
 *
 * ``dateobs`` and ``instrument_name`` are copied out of the event and
 * allocation by the paginated list handler; they are absent elsewhere.
 */
export type ObservationPlanRequestResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  requester_id?: number | null | undefined;
  last_modified_by_id?: number | null | undefined;
  gcnevent_id?: number | null | undefined;
  localization_id?: number | null | undefined;
  payload?: Record<string, unknown> | undefined;
  status?: string | null | undefined;
  allocation_id?: number | null | undefined;
  combined_id?: string | null | undefined;
  default_plan?: boolean | null | undefined;
  dateobs?: string | null | undefined;
  instrument_name?: string | null | undefined;
  observation_plans?: EventObservationPlanResponse[] | undefined;
  allocation?: AllocationResponse | null | undefined;
  gcnevent?: GcnEventResponse | null | undefined;
  localization?: LocalizationResponse | null | undefined;
  requester?: UserResponse | null | undefined;
  last_modified_by?: UserResponse | null | undefined;
  target_groups?: GroupResponse[] | undefined;
  transactions?: FacilityTransactionResponse[] | undefined;
  transaction_requests?: FacilityTransactionRequestResponse[] | undefined;
};

export const ObservationPlanRequestResponseSchema: v.GenericSchema<ObservationPlanRequestResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    requester_id: v.nullish(v.number()),
    last_modified_by_id: v.nullish(v.number()),
    gcnevent_id: v.nullish(v.number()),
    localization_id: v.nullish(v.number()),
    payload: v.optional(v.record(v.string(), v.unknown())),
    status: v.nullish(v.string()),
    allocation_id: v.nullish(v.number()),
    combined_id: v.nullish(v.string()),
    default_plan: v.nullish(v.boolean()),
    dateobs: v.nullish(v.string()),
    instrument_name: v.nullish(v.string()),
    observation_plans: v.optional(v.array(EventObservationPlanResponseSchema)),
    allocation: v.nullish(AllocationResponseSchema),
    gcnevent: v.nullish(v.lazy(() => GcnEventResponseSchema)),
    localization: v.nullish(LocalizationResponseSchema),
    requester: v.nullish(UserResponseSchema),
    last_modified_by: v.nullish(UserResponseSchema),
    target_groups: v.optional(v.array(GroupResponseSchema)),
    transactions: v.optional(v.array(FacilityTransactionResponseSchema)),
    transaction_requests: v.optional(
      v.array(FacilityTransactionRequestResponseSchema),
    ),
  });

/** An efficiency analysis run over a set of executed observations. */
export type SurveyEfficiencyForObservationsResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  payload?: Record<string, unknown> | undefined;
  status?: string | null | undefined;
  lightcurves?: string | null | undefined;
  requester_id?: number | null | undefined;
  gcnevent_id?: number | null | undefined;
  localization_id?: number | null | undefined;
  instrument_id?: number | null | undefined;
  number_of_transients?: number | null | undefined;
  number_in_covered?: number | null | undefined;
  number_detected?: number | null | undefined;
  efficiency?: number | null | undefined;
  requester?: UserResponse | null | undefined;
  groups?: GroupResponse[] | undefined;
  gcnevent?: GcnEventResponse | null | undefined;
  localization?: LocalizationResponse | null | undefined;
  instrument?: InstrumentResponse | null | undefined;
};

export const SurveyEfficiencyForObservationsResponseSchema: v.GenericSchema<SurveyEfficiencyForObservationsResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    payload: v.optional(v.record(v.string(), v.unknown())),
    status: v.nullish(v.string()),
    lightcurves: v.nullish(v.string()),
    requester_id: v.nullish(v.number()),
    gcnevent_id: v.nullish(v.number()),
    localization_id: v.nullish(v.number()),
    instrument_id: v.nullish(v.number()),
    number_of_transients: v.nullish(v.number()),
    number_in_covered: v.nullish(v.number()),
    number_detected: v.nullish(v.number()),
    efficiency: v.nullish(v.number()),
    requester: v.nullish(UserResponseSchema),
    groups: v.optional(v.array(GroupResponseSchema)),
    gcnevent: v.nullish(v.lazy(() => GcnEventResponseSchema)),
    localization: v.nullish(LocalizationResponseSchema),
    instrument: v.nullish(InstrumentResponseSchema),
  });
