// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const UserACLPostBodySchema = v.strictObject({
  aclIds: v.array(v.string()),
});

/** Request body for granting ACLs to a user. */
export type UserACLPostBody = v.InferOutput<typeof UserACLPostBodySchema>;
