// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { AllocationResponseSchema } from "./_cyclic.js";

export const AllocationDetailResponseSchema = v.strictObject({
  allocation: v.nullish(AllocationResponseSchema),
  totalMatches: v.optional(v.number()),
});

/**
 * One allocation, with the number of follow-up requests it has.
 *
 * ``totalMatches`` counts the requests the allocation has in total; the page
 * of them the query asked for is on the allocation itself.
 */
export type AllocationDetailResponse = v.InferOutput<
  typeof AllocationDetailResponseSchema
>;

export const AllocationGetQuerySchema = v.strictObject({
  numPerPage: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  sortBy: v.optional(v.picklist(["created_at", "modified", "status", "obj"])),
  sortOrder: v.optional(v.picklist(["asc", "desc"])),
  instrument_id: v.nullish(v.number()),
  apiType: v.nullish(v.picklist(["api_classname", "api_classname_obsplan"])),
  apiImplements: v.nullish(
    v.picklist([
      "update",
      "delete",
      "get",
      "submit",
      "send",
      "remove",
      "retrieve",
      "queued",
      "remove_queue",
      "prepare_payload",
      "send_skymap",
      "queued_skymap",
      "remove_skymap",
      "retrieve_log",
      "update_status",
    ]),
  ),
});

/** Query parameters for retrieving allocations. */
export type AllocationGetQuery = v.InferOutput<typeof AllocationGetQuerySchema>;

export const AllocationObservationPlanGetQuerySchema = v.strictObject({
  numPerPage: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  sortBy: v.optional(
    v.picklist(["created_at", "modified", "status", "gcnevent_id"]),
  ),
  sortOrder: v.optional(v.picklist(["asc", "desc"])),
});

/** Query parameters for listing an allocation's observation plans. */
export type AllocationObservationPlanGetQuery = v.InferOutput<
  typeof AllocationObservationPlanGetQuerySchema
>;

export const AllocationPostSchema = v.strictObject({
  instrument_id: v.number(),
  group_id: v.number(),
  hours_allocated: v.number(),
  pi: v.nullish(v.string()),
  proposal_id: v.nullish(v.string()),
  types: v.nullish(v.array(v.string())),
  validity_ranges: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  default_share_group_ids: v.nullish(v.array(v.number())),
  allocation_admin_ids: v.nullish(v.array(v.number())),
  _altdata: v.nullish(v.record(v.string(), v.unknown())),
});

/** Payload for creating an allocation. */
export type AllocationPost = v.InferOutput<typeof AllocationPostSchema>;

export const AllocationPostBodySchema = v.strictObject({
  group_id: v.nullish(v.number()),
  instrument_id: v.nullish(v.number()),
  pi: v.nullish(v.string()),
  proposal_id: v.nullish(v.string()),
  hours_allocated: v.nullish(v.number()),
  validity_ranges: v.nullish(v.array(v.unknown())),
  types: v.nullish(v.array(v.string())),
  default_share_group_ids: v.nullish(v.array(v.number())),
  allocation_admin_ids: v.nullish(v.array(v.number())),
  _altdata: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
});

/** Request body for creating an allocation. */
export type AllocationPostBody = v.InferOutput<typeof AllocationPostBodySchema>;

export const AllocationPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating an allocation. */
export type AllocationPostResponse = v.InferOutput<
  typeof AllocationPostResponseSchema
>;

export const AllocationPutBodySchema = v.strictObject({
  group_id: v.nullish(v.number()),
  instrument_id: v.nullish(v.number()),
  pi: v.nullish(v.string()),
  proposal_id: v.nullish(v.string()),
  hours_allocated: v.nullish(v.number()),
  validity_ranges: v.nullish(v.array(v.unknown())),
  types: v.nullish(v.array(v.string())),
  default_share_group_ids: v.nullish(v.array(v.number())),
  allocation_admin_ids: v.nullish(v.array(v.number())),
  _altdata: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  replace_altdata: v.nullish(v.boolean()),
});

/** Request body for updating an allocation. */
export type AllocationPutBody = v.InferOutput<typeof AllocationPutBodySchema>;

export const AllocationReportGetQuerySchema = v.strictObject({
  output_format: v.optional(v.picklist(["pdf", "png"])),
});

/** Query parameters for the allocation report. */
export type AllocationReportGetQuery = v.InferOutput<
  typeof AllocationReportGetQuerySchema
>;

export const AllocationUpdateSchema = v.strictObject({
  instrument_id: v.nullish(v.number()),
  group_id: v.nullish(v.number()),
  hours_allocated: v.nullish(v.number()),
  pi: v.nullish(v.string()),
  proposal_id: v.nullish(v.string()),
  types: v.nullish(v.array(v.string())),
  validity_ranges: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  default_share_group_ids: v.nullish(v.array(v.number())),
  allocation_admin_ids: v.nullish(v.array(v.number())),
  _altdata: v.nullish(v.record(v.string(), v.unknown())),
  replace_altdata: v.nullish(v.boolean()),
});

/** Payload for updating an allocation; every field is optional. */
export type AllocationUpdate = v.InferOutput<typeof AllocationUpdateSchema>;
