// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { GroupResponseSchema, UserResponseSchema } from "./_cyclic.js";

export const AnalysisGetQuerySchema = v.strictObject({
  objID: v.nullish(v.string()),
  analysisServiceID: v.nullish(v.number()),
  includeAnalysisData: v.optional(v.boolean()),
  summaryOnly: v.optional(v.boolean()),
  includeFilename: v.optional(v.boolean()),
});

/** Query parameters for retrieving analyses. */
export type AnalysisGetQuery = v.InferOutput<typeof AnalysisGetQuerySchema>;

export const AnalysisPatchBodySchema = v.strictObject({
  group_ids: v.array(v.number()),
});

/** Request body for re-sharing an existing analysis with a set of groups. */
export type AnalysisPatchBody = v.InferOutput<typeof AnalysisPatchBodySchema>;

export const AnalysisPostSchema = v.strictObject({
  analysis_parameters: v.nullish(v.record(v.string(), v.unknown())),
  show_parameters: v.nullish(v.boolean()),
  show_plots: v.nullish(v.boolean()),
  show_corner: v.nullish(v.boolean()),
  input_filters: v.nullish(v.record(v.string(), v.unknown())),
  group_ids: v.nullish(v.array(v.number())),
});

/** Payload for starting an analysis run. */
export type AnalysisPost = v.InferOutput<typeof AnalysisPostSchema>;

export const AnalysisPostBodySchema = v.strictObject({
  show_parameters: v.optional(v.boolean()),
  show_plots: v.optional(v.boolean()),
  show_corner: v.optional(v.boolean()),
  input_filters: v.nullish(v.record(v.string(), v.unknown())),
  analysis_parameters: v.optional(v.record(v.string(), v.unknown())),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for running an analysis. */
export type AnalysisPostBody = v.InferOutput<typeof AnalysisPostBodySchema>;

export const AnalysisPostResponseSchema = v.strictObject({
  id: v.number(),
});

/** Result of starting an analysis run. */
export type AnalysisPostResponse = v.InferOutput<
  typeof AnalysisPostResponseSchema
>;

export const AnalysisProductsGetQuerySchema = v.strictObject({
  download: v.optional(v.boolean()),
});

/** Query parameters for retrieving an analysis product. */
export type AnalysisProductsGetQuery = v.InferOutput<
  typeof AnalysisProductsGetQuerySchema
>;

export const AnalysisServicePatchBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  display_name: v.nullish(v.string()),
  description: v.nullish(v.string()),
  version: v.nullish(v.string()),
  contact_name: v.nullish(v.string()),
  contact_email: v.nullish(v.string()),
  url: v.nullish(v.string()),
  optional_analysis_parameters: v.optional(
    v.union([v.string(), v.record(v.string(), v.unknown()), v.null()]),
  ),
  authentication_type: v.nullish(v.string()),
  _authinfo: v.nullish(v.string()),
  enabled: v.nullish(v.boolean()),
  analysis_type: v.nullish(v.string()),
  input_data_types: v.nullish(v.array(v.string())),
  timeout: v.nullish(v.number()),
  is_summary: v.nullish(v.boolean()),
  display_on_resource_dropdown: v.nullish(v.boolean()),
  upload_only: v.nullish(v.boolean()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for updating an Analysis Service (all fields optional). */
export type AnalysisServicePatchBody = v.InferOutput<
  typeof AnalysisServicePatchBodySchema
>;

export const AnalysisServicePostSchema = v.strictObject({
  name: v.string(),
  url: v.string(),
  authentication_type: v.picklist([
    "none",
    "header_token",
    "api_key",
    "HTTPBasicAuth",
    "HTTPDigestAuth",
    "OAuth1",
  ]),
  analysis_type: v.picklist([
    "lightcurve_fitting",
    "spectrum_fitting",
    "meta_analysis",
  ]),
  input_data_types: v.array(
    v.picklist([
      "photometry",
      "spectra",
      "redshift",
      "annotations",
      "comments",
      "classifications",
    ]),
  ),
  display_name: v.nullish(v.string()),
  description: v.nullish(v.string()),
  version: v.nullish(v.string()),
  contact_name: v.nullish(v.string()),
  contact_email: v.nullish(v.string()),
  optional_analysis_parameters: v.nullish(v.string()),
  _authinfo: v.nullish(v.string()),
  enabled: v.nullish(v.boolean()),
  timeout: v.nullish(v.number()),
  upload_only: v.nullish(v.boolean()),
  is_summary: v.nullish(v.boolean()),
  display_on_resource_dropdown: v.nullish(v.boolean()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Payload for registering a new analysis service. */
export type AnalysisServicePost = v.InferOutput<
  typeof AnalysisServicePostSchema
>;

export const AnalysisServicePostBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  display_name: v.nullish(v.string()),
  description: v.nullish(v.string()),
  version: v.nullish(v.string()),
  contact_name: v.nullish(v.string()),
  contact_email: v.nullish(v.string()),
  url: v.nullish(v.string()),
  optional_analysis_parameters: v.optional(
    v.union([v.string(), v.record(v.string(), v.unknown()), v.null()]),
  ),
  authentication_type: v.nullish(v.string()),
  _authinfo: v.nullish(v.string()),
  enabled: v.nullish(v.boolean()),
  analysis_type: v.nullish(v.string()),
  input_data_types: v.nullish(v.array(v.string())),
  timeout: v.nullish(v.number()),
  is_summary: v.nullish(v.boolean()),
  display_on_resource_dropdown: v.nullish(v.boolean()),
  upload_only: v.nullish(v.boolean()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for creating an Analysis Service. */
export type AnalysisServicePostBody = v.InferOutput<
  typeof AnalysisServicePostBodySchema
>;

export const AnalysisServicePostResponseSchema = v.strictObject({
  id: v.number(),
});

/** Result of registering an analysis service. */
export type AnalysisServicePostResponse = v.InferOutput<
  typeof AnalysisServicePostResponseSchema
>;

export const AnalysisServiceResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  name: v.nullish(v.string()),
  display_name: v.nullish(v.string()),
  description: v.nullish(v.string()),
  version: v.nullish(v.string()),
  contact_name: v.nullish(v.string()),
  contact_email: v.nullish(v.string()),
  url: v.nullish(v.string()),
  optional_analysis_parameters: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  authentication_type: v.nullish(
    v.picklist([
      "none",
      "header_token",
      "api_key",
      "HTTPBasicAuth",
      "HTTPDigestAuth",
      "OAuth1",
    ]),
  ),
  enabled: v.nullish(v.boolean()),
  analysis_type: v.nullish(
    v.picklist(["lightcurve_fitting", "spectrum_fitting", "meta_analysis"]),
  ),
  input_data_types: v.optional(
    v.array(
      v.picklist([
        "photometry",
        "spectra",
        "redshift",
        "annotations",
        "comments",
        "classifications",
      ]),
    ),
  ),
  timeout: v.nullish(v.number()),
  upload_only: v.nullish(v.boolean()),
  display_on_resource_dropdown: v.nullish(v.boolean()),
  is_summary: v.nullish(v.boolean()),
  groups: v.optional(v.array(GroupResponseSchema)),
});

/** An external analysis service (``AnalysisService``). */
export type AnalysisServiceResponse = v.InferOutput<
  typeof AnalysisServiceResponseSchema
>;

export const AnalysisServiceUpdateSchema = v.strictObject({
  name: v.nullish(v.string()),
  url: v.nullish(v.string()),
  authentication_type: v.nullish(
    v.picklist([
      "none",
      "header_token",
      "api_key",
      "HTTPBasicAuth",
      "HTTPDigestAuth",
      "OAuth1",
    ]),
  ),
  analysis_type: v.nullish(
    v.picklist(["lightcurve_fitting", "spectrum_fitting", "meta_analysis"]),
  ),
  input_data_types: v.nullish(
    v.array(
      v.picklist([
        "photometry",
        "spectra",
        "redshift",
        "annotations",
        "comments",
        "classifications",
      ]),
    ),
  ),
  display_name: v.nullish(v.string()),
  description: v.nullish(v.string()),
  version: v.nullish(v.string()),
  contact_name: v.nullish(v.string()),
  contact_email: v.nullish(v.string()),
  optional_analysis_parameters: v.nullish(v.string()),
  authinfo: v.nullish(v.record(v.string(), v.unknown())),
  enabled: v.nullish(v.boolean()),
  timeout: v.nullish(v.number()),
  upload_only: v.nullish(v.boolean()),
  is_summary: v.nullish(v.boolean()),
  display_on_resource_dropdown: v.nullish(v.boolean()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Payload for a partial update of an analysis service. */
export type AnalysisServiceUpdate = v.InferOutput<
  typeof AnalysisServiceUpdateSchema
>;

export const AnalysisUploadBodySchema = v.strictObject({
  analysis: v.optional(v.record(v.string(), v.unknown())),
  message: v.optional(v.string()),
  show_parameters: v.optional(v.boolean()),
  show_plots: v.optional(v.boolean()),
  show_corner: v.optional(v.boolean()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for uploading an upload_only analysis result. */
export type AnalysisUploadBody = v.InferOutput<typeof AnalysisUploadBodySchema>;

export const AnalysisUploadPostSchema = v.strictObject({
  analysis: v.nullish(v.record(v.string(), v.unknown())),
  message: v.nullish(v.string()),
  show_parameters: v.nullish(v.boolean()),
  show_plots: v.nullish(v.boolean()),
  show_corner: v.nullish(v.boolean()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Payload for uploading results to an upload-only analysis service. */
export type AnalysisUploadPost = v.InferOutput<typeof AnalysisUploadPostSchema>;

export const AnalysisUploadResponseSchema = v.strictObject({
  id: v.number(),
  message: v.nullish(v.string()),
});

/** Result of uploading an upload-only analysis. */
export type AnalysisUploadResponse = v.InferOutput<
  typeof AnalysisUploadResponseSchema
>;

export const AnalysisWebhookPostBodySchema = v.looseObject({
  status: v.nullish(v.string()),
  message: v.nullish(v.string()),
  analysis: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * Result payload posted back by an external analysis service.
 *
 * External services may include additional keys, so extras are allowed
 * rather than forbidden.
 */
export type AnalysisWebhookPostBody = v.InferOutput<
  typeof AnalysisWebhookPostBodySchema
>;

export const DefaultAnalysisPatchBodySchema = v.strictObject({
  default_analysis_parameters: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  source_filter: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  daily_limit: v.optional(v.union([v.number(), v.string(), v.null()])),
  group_ids: v.nullish(v.array(v.number())),
  show_parameters: v.nullish(v.boolean()),
  show_plots: v.nullish(v.boolean()),
  show_corner: v.nullish(v.boolean()),
});

/** Request body for updating a default analysis (all fields optional). */
export type DefaultAnalysisPatchBody = v.InferOutput<
  typeof DefaultAnalysisPatchBodySchema
>;

export const DefaultAnalysisPostSchema = v.strictObject({
  default_analysis_parameters: v.nullish(v.record(v.string(), v.unknown())),
  source_filter: v.nullish(v.record(v.string(), v.unknown())),
  daily_limit: v.nullish(v.number()),
  show_parameters: v.nullish(v.boolean()),
  show_plots: v.nullish(v.boolean()),
  show_corner: v.nullish(v.boolean()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Payload for creating or updating a default analysis. */
export type DefaultAnalysisPost = v.InferOutput<
  typeof DefaultAnalysisPostSchema
>;

export const DefaultAnalysisPostBodySchema = v.strictObject({
  analysis_resource_type: v.optional(v.string()),
  default_analysis_parameters: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string()]),
  ),
  source_filter: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string()]),
  ),
  daily_limit: v.optional(v.union([v.number(), v.string()])),
  group_ids: v.nullish(v.array(v.number())),
  show_parameters: v.optional(v.boolean()),
  show_plots: v.optional(v.boolean()),
  show_corner: v.optional(v.boolean()),
});

/** Request body for creating a default analysis. */
export type DefaultAnalysisPostBody = v.InferOutput<
  typeof DefaultAnalysisPostBodySchema
>;

export const DefaultAnalysisPostResponseSchema = v.strictObject({
  id: v.number(),
});

/** Result of creating a default analysis. */
export type DefaultAnalysisPostResponse = v.InferOutput<
  typeof DefaultAnalysisPostResponseSchema
>;

export const DefaultAnalysisResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  analysis_service_id: v.nullish(v.number()),
  author_id: v.nullish(v.number()),
  show_parameters: v.nullish(v.boolean()),
  show_plots: v.nullish(v.boolean()),
  show_corner: v.nullish(v.boolean()),
  default_analysis_parameters: v.nullish(v.record(v.string(), v.unknown())),
  source_filter: v.nullish(v.record(v.string(), v.unknown())),
  stats: v.nullish(v.record(v.string(), v.unknown())),
  groups: v.optional(v.array(GroupResponseSchema)),
  author: v.nullish(UserResponseSchema),
  analysis_service: v.nullish(AnalysisServiceResponseSchema),
});

/** A default analysis (``DefaultAnalysis``). */
export type DefaultAnalysisResponse = v.InferOutput<
  typeof DefaultAnalysisResponseSchema
>;

export const ObjAnalysisResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  author_id: v.nullish(v.number()),
  analysis_service_id: v.nullish(v.number()),
  hash: v.nullish(v.string()),
  show_parameters: v.nullish(v.boolean()),
  show_plots: v.nullish(v.boolean()),
  show_corner: v.nullish(v.boolean()),
  analysis_parameters: v.nullish(v.record(v.string(), v.unknown())),
  input_filters: v.nullish(v.record(v.string(), v.unknown())),
  invalid_after: v.nullish(v.string()),
  token: v.nullish(v.string()),
  handled_by_url: v.nullish(v.string()),
  status: v.nullish(
    v.picklist([
      "queued",
      "pending",
      "completed",
      "failure",
      "cancelled",
      "timed_out",
    ]),
  ),
  status_message: v.nullish(v.string()),
  duration: v.nullish(v.number()),
  last_activity: v.nullish(v.string()),
  analysis_service_name: v.nullish(v.string()),
  analysis_service_description: v.nullish(v.string()),
  num_plots: v.nullish(v.number()),
  filename: v.nullish(v.string()),
  groups: v.optional(v.array(GroupResponseSchema)),
  data: v.nullish(v.record(v.string(), v.unknown())),
  model_lightcurve: v.optional(v.unknown()),
  model_lightcurves: v.optional(v.unknown()),
  model_name: v.nullish(v.string()),
  n_detections: v.nullish(v.number()),
  model_spectrum: v.optional(v.unknown()),
  model_spectrum_summary: v.nullish(v.string()),
  model_spectrum_source: v.optional(v.unknown()),
});

/** An analysis run on an object (``ObjAnalysis``). */
export type ObjAnalysisResponse = v.InferOutput<
  typeof ObjAnalysisResponseSchema
>;
