// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { GroupResponseSchema } from "./_cyclic.js";

export const ALMAQueryBodySchema = v.strictObject({
  crossmatchRadius: v.nullish(v.number()),
  publicOnly: v.nullish(v.boolean()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for posting ALMA archive coverage annotations. */
export type ALMAQueryBody = v.InferOutput<typeof ALMAQueryBodySchema>;

export const AnnotationDetailResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  data: v.optional(v.record(v.string(), v.unknown())),
  origin: v.nullish(v.string()),
  author_id: v.nullish(v.number()),
  author: v.nullish(v.record(v.string(), v.unknown())),
  groups: v.optional(v.array(GroupResponseSchema)),
  obj_id: v.nullish(v.string()),
  spectrum_id: v.nullish(v.number()),
  photometry_id: v.nullish(v.number()),
  obj: v.nullish(v.record(v.string(), v.unknown())),
  spectrum: v.nullish(v.record(v.string(), v.unknown())),
  photometry: v.nullish(v.record(v.string(), v.unknown())),
  type: v.nullish(v.string()),
});

/** A single annotation, as returned by the single-annotation endpoint. */
export type AnnotationDetailResponse = v.InferOutput<
  typeof AnnotationDetailResponseSchema
>;

export const AnnotationPostBodySchema = v.object({
  origin: v.string(),
  data: v.record(v.string(), v.unknown()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for posting an annotation. */
export type AnnotationPostBody = v.InferOutput<typeof AnnotationPostBodySchema>;

export const AnnotationPostResponseSchema = v.object({
  annotation_id: v.number(),
});

/** Data payload returned when posting an annotation. */
export type AnnotationPostResponse = v.InferOutput<
  typeof AnnotationPostResponseSchema
>;

export const AnnotationPutBodySchema = v.object({
  data: v.nullish(v.record(v.string(), v.unknown())),
  origin: v.nullish(v.string()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for updating an annotation. */
export type AnnotationPutBody = v.InferOutput<typeof AnnotationPutBodySchema>;

export const AnnotationResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  data: v.optional(v.record(v.string(), v.unknown())),
  origin: v.nullish(v.string()),
  author_id: v.nullish(v.number()),
  author: v.nullish(v.record(v.string(), v.unknown())),
  groups: v.optional(v.array(GroupResponseSchema)),
  obj_id: v.nullish(v.string()),
  spectrum_id: v.nullish(v.number()),
  photometry_id: v.nullish(v.number()),
  obj: v.nullish(v.record(v.string(), v.unknown())),
  spectrum: v.nullish(v.record(v.string(), v.unknown())),
  photometry: v.nullish(v.record(v.string(), v.unknown())),
  type: v.nullish(v.string()),
});

/**
 * An annotation on a source, spectrum, or photometry point.
 *
 * Union of the Annotation, AnnotationOnSpectrum, and AnnotationOnPhotometry
 * payloads, so each type-specific foreign key is optional.
 */
export type AnnotationResponse = v.InferOutput<typeof AnnotationResponseSchema>;

export const DatalabQueryBodySchema = v.strictObject({
  catalog: v.optional(v.string()),
  crossmatchRadius: v.nullish(v.number()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for posting Datalab cross-match annotations. */
export type DatalabQueryBody = v.InferOutput<typeof DatalabQueryBodySchema>;

export const IRSAQueryWISEBodySchema = v.strictObject({
  catalog: v.optional(v.string()),
  crossmatchRadius: v.nullish(v.number()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for posting WISE cross-match annotations. */
export type IRSAQueryWISEBody = v.InferOutput<typeof IRSAQueryWISEBodySchema>;

export const PS1QueryBodySchema = v.strictObject({
  catalog: v.optional(v.string()),
  crossmatchRadius: v.nullish(v.number()),
  crossmatchMinDetections: v.nullish(v.number()),
  crossmatchNumber: v.nullish(v.number()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for posting PS1 cross-match annotations. */
export type PS1QueryBody = v.InferOutput<typeof PS1QueryBodySchema>;

export const VizierQueryBodySchema = v.strictObject({
  catalog: v.optional(v.string()),
  crossmatchRadius: v.nullish(v.number()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for posting Vizier cross-match annotations. */
export type VizierQueryBody = v.InferOutput<typeof VizierQueryBodySchema>;
