// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { UserResponseSchema } from "./_cyclic.js";

export const AssignmentPostSchema = v.strictObject({
  run_id: v.number(),
  obj_id: v.string(),
  priority: v.picklist(["1", "2", "3", "4", "5"]),
  status: v.nullish(v.string()),
  comment: v.nullish(v.string()),
});

/** Payload for assigning a target to an observing run. */
export type AssignmentPost = v.InferOutput<typeof AssignmentPostSchema>;

export const AssignmentResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  run_id: v.nullish(v.number()),
  requester_id: v.nullish(v.number()),
  last_modified_by_id: v.nullish(v.number()),
  status: v.nullish(v.string()),
  priority: v.nullish(v.picklist(["1", "2", "3", "4", "5"])),
  comment: v.nullish(v.string()),
  obj: v.nullish(v.record(v.string(), v.unknown())),
  requester: v.nullish(UserResponseSchema),
  last_modified_by: v.nullish(v.number()),
  run: v.nullish(v.number()),
  spectra: v.optional(v.array(v.number())),
  photometry: v.optional(v.array(v.number())),
  photometric_series: v.optional(v.array(v.number())),
  rise_time_utc: v.nullish(v.string()),
  set_time_utc: v.nullish(v.string()),
  accessible_group_names: v.optional(v.array(v.string())),
  last_detected_mag: v.nullish(v.number()),
  last_detected_filter: v.nullish(v.string()),
  last_detected_mjd: v.nullish(v.number()),
});

/** A target assignment on an observing run (``ClassicalAssignment``). */
export type AssignmentResponse = v.InferOutput<typeof AssignmentResponseSchema>;
