// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const AssistantMessagePostResponseSchema = v.strictObject({
  id: v.number(),
});

/** Result of sending a message to the assistant. */
export type AssistantMessagePostResponse = v.InferOutput<
  typeof AssistantMessagePostResponseSchema
>;

export const AssistantMessageResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  user_id: v.nullish(v.number()),
  channel: v.nullish(v.string()),
  text: v.nullish(v.string()),
  system: v.nullish(v.boolean()),
  context_type: v.nullish(v.string()),
  context_id: v.nullish(v.string()),
});

/**
 * One message of an assistant conversation.
 *
 * ``channel`` is null for the default conversation; ``context_type`` and
 * ``context_id`` name the resource the conversation was opened on, if any.
 */
export type AssistantMessageResponse = v.InferOutput<
  typeof AssistantMessageResponseSchema
>;
