// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { StreamResponseSchema } from "./streams.js";

export const BrokerAlertSaveResponseSchema = v.strictObject({
  id: v.string(),
});

/** Result of saving a broker alert as a source. */
export type BrokerAlertSaveResponse = v.InferOutput<
  typeof BrokerAlertSaveResponseSchema
>;

export const BrokerCapabilitiesResponseSchema = v.strictObject({
  query_alerts: v.nullish(v.boolean()),
  get_alert: v.nullish(v.boolean()),
  get_cutouts: v.nullish(v.boolean()),
  cone_search: v.nullish(v.boolean()),
  get_filters: v.nullish(v.boolean()),
  create_filter: v.nullish(v.boolean()),
  update_filter: v.nullish(v.boolean()),
  delete_filter: v.nullish(v.boolean()),
  test_filter: v.nullish(v.boolean()),
  validate_filter: v.nullish(v.boolean()),
  filter_modules: v.nullish(v.boolean()),
  run_ingestion: v.nullish(v.boolean()),
  validate_config: v.nullish(v.boolean()),
  test_connection: v.nullish(v.boolean()),
  save_as_source: v.nullish(v.boolean()),
  get_photometry: v.nullish(v.boolean()),
  cross_match_catalogs: v.nullish(v.boolean()),
  filter_pipeline: v.nullish(v.string()),
});

/** What a broker's provider class implements (see ``implements()``). */
export type BrokerCapabilitiesResponse = v.InferOutput<
  typeof BrokerCapabilitiesResponseSchema
>;

export const BrokerConeSearchGetQuerySchema = v.strictObject({
  ra: v.number(),
  dec: v.number(),
  radius: v.number(),
  radius_units: v.optional(v.picklist(["deg", "arcmin", "arcsec"])),
});

/** Query parameters for a broker cone search. */
export type BrokerConeSearchGetQuery = v.InferOutput<
  typeof BrokerConeSearchGetQuerySchema
>;

export const BrokerCredentialBodySchema = v.strictObject({
  credentials: v.nullish(v.record(v.string(), v.unknown())),
  replace_credentials: v.optional(v.boolean()),
  topics: v.nullish(v.array(v.string())),
  topic_filter_ids: v.nullish(v.record(v.string(), v.array(v.number()))),
});

/**
 * A user's own credentials for a broker. ``credentials`` holds whatever the
 * provider's ``user_credential_schema`` declares.
 */
export type BrokerCredentialBody = v.InferOutput<
  typeof BrokerCredentialBodySchema
>;

export const BrokerCredentialPutResponseSchema = v.strictObject({
  id: v.number(),
});

/** Result of storing broker credentials. */
export type BrokerCredentialPutResponse = v.InferOutput<
  typeof BrokerCredentialPutResponseSchema
>;

export const BrokerCredentialResponseSchema = v.strictObject({
  id: v.number(),
  broker_id: v.number(),
  topics: v.optional(v.array(v.string())),
  topic_filter_ids: v.optional(v.record(v.string(), v.array(v.number()))),
  credentials: v.optional(v.record(v.string(), v.unknown())),
  secrets_set: v.optional(v.array(v.string())),
});

/**
 * A user's stored credentials for a broker.
 *
 * Hand-built, so ``created_at``/``modified`` are never returned. The secret
 * config fields are reported by name only in ``secrets_set``; their values
 * are stripped from ``credentials``. The whole payload is ``null`` when the
 * caller has no stored row.
 */
export type BrokerCredentialResponse = v.InferOutput<
  typeof BrokerCredentialResponseSchema
>;

export const BrokerCredentialTopicsResponseSchema = v.strictObject({
  topics: v.optional(v.array(v.string())),
});

/** The topics the broker offers the caller's credentials. */
export type BrokerCredentialTopicsResponse = v.InferOutput<
  typeof BrokerCredentialTopicsResponseSchema
>;

export const BrokerFilterAttachBodySchema = v.strictObject({
  broker_id: v.number(),
});

/** Request body for attaching a filter to a broker. */
export type BrokerFilterAttachBody = v.InferOutput<
  typeof BrokerFilterAttachBodySchema
>;

export const BrokerFilterAttachResponseSchema = v.strictObject({
  id: v.number(),
  broker_id: v.nullish(v.number()),
});

/** Result of attaching a filter to a broker. */
export type BrokerFilterAttachResponse = v.InferOutput<
  typeof BrokerFilterAttachResponseSchema
>;

export const BrokerFilterCatalogGetQuerySchema = v.strictObject({
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
  name: v.nullish(v.string()),
  groupID: v.nullish(v.number()),
  streamID: v.nullish(v.number()),
  brokerID: v.nullish(v.string()),
});

/** Query parameters for listing filters and their broker. */
export type BrokerFilterCatalogGetQuery = v.InferOutput<
  typeof BrokerFilterCatalogGetQuerySchema
>;

export const BrokerFilterVersionResponseSchema = v.strictObject({
  fid: v.optional(v.union([v.string(), v.number(), v.null()])),
  version: v.optional(v.unknown()),
});

/** One editable version of a broker filter, as stored on the filter row. */
export type BrokerFilterVersionResponse = v.InferOutput<
  typeof BrokerFilterVersionResponseSchema
>;

export const BrokerFilterDetailResponseSchema = v.strictObject({
  id: v.number(),
  name: v.nullish(v.string()),
  group_id: v.nullish(v.number()),
  broker_id: v.nullish(v.number()),
  autosave: v.nullish(v.boolean()),
  stream: v.nullish(StreamResponseSchema),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  fv: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  active_fid: v.optional(v.union([v.string(), v.number(), v.null()])),
  active: v.nullish(v.boolean()),
  filters: v.nullish(v.array(BrokerFilterVersionResponseSchema)),
});

/**
 * A broker filter enriched with its broker-side versions and state.
 *
 * ``stream`` is trimmed by the handler to the stream's ``id`` and ``name``.
 * ``fv`` comes straight back from the broker, so its entries are shaped by
 * the provider rather than by skyportal. The ``fv``/``active_fid``/
 * ``active``/``filters`` block is dropped entirely when the broker is
 * unreachable or the filter has no broker-side counterpart.
 */
export type BrokerFilterDetailResponse = v.InferOutput<
  typeof BrokerFilterDetailResponseSchema
>;

export const BrokerFilterModuleWriteBodySchema = v.strictObject({
  elements: v.nullish(v.string()),
  data: v.nullish(v.record(v.string(), v.unknown())),
});

/** Request body for creating/updating a broker custom filter module. */
export type BrokerFilterModuleWriteBody = v.InferOutput<
  typeof BrokerFilterModuleWriteBodySchema
>;

export const BrokerFilterModulesGetQuerySchema = v.strictObject({
  survey: v.nullish(v.string()),
  elements: v.optional(
    v.picklist([
      "schema",
      "variables",
      "listVariables",
      "switchCases",
      "blocks",
    ]),
  ),
});

/** Query parameters for reading a broker's filter-building vocabulary. */
export type BrokerFilterModulesGetQuery = v.InferOutput<
  typeof BrokerFilterModulesGetQuerySchema
>;

export const BrokerFilterPostResponseSchema = v.strictObject({
  id: v.number(),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  autosave: v.nullish(v.boolean()),
});

/** Result of creating a broker filter version. */
export type BrokerFilterPostResponse = v.InferOutput<
  typeof BrokerFilterPostResponseSchema
>;

export const BrokerFilterQuerySchema = v.strictObject({
  selected: v.string(),
  tables: v.string(),
  conditions: v.nullish(v.string()),
});

/** A saved query for a broker whose ``filter_kind`` is ``"query"``. */
export type BrokerFilterQuery = v.InferOutput<typeof BrokerFilterQuerySchema>;

export const BrokerFilterResponseSchema = v.strictObject({
  id: v.number(),
  name: v.nullish(v.string()),
  group_id: v.nullish(v.number()),
  stream_id: v.nullish(v.number()),
  broker_id: v.nullish(v.number()),
  autosave: v.nullish(v.boolean()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * A skyportal ``Filter`` as listed by the broker endpoints.
 *
 * The handlers hand-build this payload, so it carries a strict subset of the
 * ``Filter`` columns and never ``created_at``/``modified``. ``altdata`` stays
 * free-form: it holds the broker-side ids and the compiled native filter,
 * whose shape the broker defines.
 */
export type BrokerFilterResponse = v.InferOutput<
  typeof BrokerFilterResponseSchema
>;

export const BrokerFilterTestBodySchema = v.record(v.string(), v.unknown());

/**
 * Filter parameters specific to the broker's filter_kind, passed through to
 * the provider (e.g. Lasair's selected/tables/conditions, BOOM's pipeline).
 */
export type BrokerFilterTestBody = v.InferOutput<
  typeof BrokerFilterTestBodySchema
>;

export const BrokerFilterValidateBodySchema = v.strictObject({
  fid: v.optional(v.union([v.number(), v.string(), v.null()])),
});

/** Request body for validating a broker filter version for activation. */
export type BrokerFilterValidateBody = v.InferOutput<
  typeof BrokerFilterValidateBodySchema
>;

export const BrokerFilterValidationResponseSchema = v.strictObject({
  fid: v.optional(v.union([v.string(), v.number(), v.null()])),
  passed: v.nullish(v.boolean()),
  message: v.nullish(v.string()),
});

/** Verdict of a broker filter version validation. */
export type BrokerFilterValidationResponse = v.InferOutput<
  typeof BrokerFilterValidationResponseSchema
>;

export const BrokerFiltersPageResponseSchema = v.strictObject({
  filters: v.optional(v.array(BrokerFilterResponseSchema)),
  totalMatches: v.optional(v.number()),
});

/** One page of results from the broker filter catalog. */
export type BrokerFiltersPageResponse = v.InferOutput<
  typeof BrokerFiltersPageResponseSchema
>;

export const BrokerFiltersPatchBodySchema = v.strictObject({
  active: v.nullish(v.boolean()),
  active_fid: v.optional(v.union([v.number(), v.string(), v.null()])),
  autoAnnotate: v.nullish(v.boolean()),
  autoSave: v.nullish(v.boolean()),
  autoFollowup: v.nullish(v.boolean()),
  autoSaveIgnoreGroupIds: v.nullish(v.array(v.number())),
  autoSaveIgnoreRadius: v.optional(v.union([v.number(), v.string(), v.null()])),
  autoSaveSaverId: v.optional(v.union([v.number(), v.string(), v.null()])),
  autoSaveComment: v.nullish(v.string()),
  autoFollowupDefaultId: v.optional(
    v.union([v.number(), v.string(), v.null()]),
  ),
});

/** Request body for updating a broker filter. */
export type BrokerFiltersPatchBody = v.InferOutput<
  typeof BrokerFiltersPatchBodySchema
>;

export const BrokerFiltersPostBodySchema = v.strictObject({
  query: v.nullish(v.record(v.string(), v.unknown())),
  altdata: v.nullish(v.array(v.unknown())),
  filters: v.optional(v.unknown()),
  name: v.nullish(v.string()),
  autosave: v.nullish(v.boolean()),
});

/** Request body for creating a broker filter version. */
export type BrokerFiltersPostBody = v.InferOutput<
  typeof BrokerFiltersPostBodySchema
>;

export const BrokerPatchBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  active: v.nullish(v.boolean()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  default_alert_search: v.nullish(v.boolean()),
  default_crossmatch: v.nullish(v.boolean()),
  default_photometry: v.nullish(v.boolean()),
});

/** Request body for updating a broker. */
export type BrokerPatchBody = v.InferOutput<typeof BrokerPatchBodySchema>;

export const BrokerPhotometryGetQuerySchema = v.strictObject({
  survey: v.nullish(v.string()),
  format: v.optional(v.picklist(["mag", "flux", "both"])),
  magsys: v.optional(
    v.picklist(["jla1", "ab", "vega", "bd17", "csp", "ab-b12"]),
  ),
  includeSuperObjsPhotometry: v.optional(v.boolean()),
  includeOwnerInfo: v.optional(v.boolean()),
  includeStreamInfo: v.optional(v.boolean()),
  includeValidationInfo: v.optional(v.boolean()),
  includeAnnotationInfo: v.optional(v.boolean()),
  includeExtinction: v.optional(v.boolean()),
});

/** Query parameters for displaying an object's photometry via a broker. */
export type BrokerPhotometryGetQuery = v.InferOutput<
  typeof BrokerPhotometryGetQuerySchema
>;

export const BrokerPostSchema = v.strictObject({
  name: v.string(),
  broker_classname: v.picklist([
    "GENERICBROKER",
    "LASAIRBROKER",
    "BABAMULBROKER",
    "BOOMBROKER",
    "FINKBROKER",
    "ALERCEBROKER",
    "ANTARESBROKER",
    "PITTGOOGLEBROKER",
    "AMPELBROKER",
  ]),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  active: v.nullish(v.boolean()),
  default_alert_search: v.nullish(v.boolean()),
  default_crossmatch: v.nullish(v.boolean()),
  default_photometry: v.nullish(v.boolean()),
});

/** Payload for registering a broker. */
export type BrokerPost = v.InferOutput<typeof BrokerPostSchema>;

export const BrokerPostBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  broker_classname: v.nullish(v.string()),
  altdata: v.optional(v.record(v.string(), v.unknown())),
  active: v.optional(v.boolean()),
  default_alert_search: v.optional(v.boolean()),
  default_crossmatch: v.optional(v.boolean()),
  default_photometry: v.optional(v.boolean()),
});

/** Request body for creating a broker. */
export type BrokerPostBody = v.InferOutput<typeof BrokerPostBodySchema>;

export const BrokerPostResponseSchema = v.strictObject({
  id: v.number(),
});

/** Result of registering a broker. */
export type BrokerPostResponse = v.InferOutput<typeof BrokerPostResponseSchema>;

export const BrokerResponseSchema = v.strictObject({
  id: v.number(),
  name: v.nullish(v.string()),
  broker_classname: v.nullish(
    v.picklist([
      "GENERICBROKER",
      "LASAIRBROKER",
      "BABAMULBROKER",
      "BOOMBROKER",
      "FINKBROKER",
      "ALERCEBROKER",
      "ANTARESBROKER",
      "PITTGOOGLEBROKER",
      "AMPELBROKER",
    ]),
  ),
  active: v.nullish(v.boolean()),
  default_alert_search: v.nullish(v.boolean()),
  default_crossmatch: v.nullish(v.boolean()),
  default_photometry: v.nullish(v.boolean()),
  capabilities: v.nullish(BrokerCapabilitiesResponseSchema),
  surveys: v.optional(v.array(v.string())),
  filter_kind: v.nullish(v.picklist(["pipeline", "query", "tags", "none"])),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * A configured connection to an external alert broker.
 *
 * ``broker_to_dict`` hand-builds this payload rather than calling
 * ``to_dict()``, so ``created_at``/``modified`` are never returned even though
 * the row carries them. ``altdata`` is only present for system admins, with
 * the provider's secret config fields stripped out.
 */
export type BrokerResponse = v.InferOutput<typeof BrokerResponseSchema>;

export const BrokerSaveBodySchema = v.strictObject({
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for saving a broker alert as a source. */
export type BrokerSaveBody = v.InferOutput<typeof BrokerSaveBodySchema>;
