// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import {
  ClassificationResponseSchema,
  CommentResponseSchema,
  GroupResponseSchema,
} from "./_cyclic.js";
import { AnnotationResponseSchema } from "./annotations.js";
import { GalaxyResponseSchema } from "./galaxies.js";
import { ObjTagResponseSchema } from "./tags.js";
import { ThumbnailResponseSchema } from "./thumbnails.js";

export const BulkCandidateDeleteResponseSchema = v.strictObject({
  deleted: v.number(),
  remaining: v.number(),
  dryRun: v.boolean(),
});

/** Result of a bulk deletion of old, unsaved candidate objects. */
export type BulkCandidateDeleteResponse = v.InferOutput<
  typeof BulkCandidateDeleteResponseSchema
>;

export const BulkDeleteCandidatesPostBodySchema = v.strictObject({
  maxAgeMonths: v.optional(v.number()),
  batchSize: v.optional(v.number()),
  dryRun: v.optional(v.boolean()),
});

/** Request body for bulk-deleting old, unsaved candidates. */
export type BulkDeleteCandidatesPostBody = v.InferOutput<
  typeof BulkDeleteCandidatesPostBodySchema
>;

export const CandidateAssociatedObjResponseSchema = v.strictObject({
  obj_id: v.nullish(v.string()),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  separation: v.nullish(v.number()),
  super_obj_id: v.nullish(v.number()),
  super_obj_name: v.nullish(v.string()),
});

/** Another object linked to a candidate through a ``SuperObj``. */
export type CandidateAssociatedObjResponse = v.InferOutput<
  typeof CandidateAssociatedObjResponseSchema
>;

export const CandidateFilterGetQuerySchema = v.strictObject({
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  groupIDs: v.nullish(v.string()),
  filterIDs: v.nullish(v.string()),
  savedStatus: v.optional(
    v.picklist([
      "all",
      "savedToAllSelected",
      "savedToAnySelected",
      "savedToAnyAccessible",
      "notSavedToAnyAccessible",
      "notSavedToAnySelected",
      "notSavedToAllSelected",
    ]),
  ),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/** Query parameters for listing candidates with their alert ids. */
export type CandidateFilterGetQuery = v.InferOutput<
  typeof CandidateFilterGetQuerySchema
>;

export const CandidateRecordResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  filter_id: v.nullish(v.number()),
  passed_at: v.nullish(v.string()),
  passing_alert_id: v.nullish(v.number()),
  uploader_id: v.nullish(v.number()),
});

/** One row of the ``candidates`` table (a ``Candidate``). */
export type CandidateRecordResponse = v.InferOutput<
  typeof CandidateRecordResponseSchema
>;

export const CandidateFilterPageResponseSchema = v.strictObject({
  candidates: v.optional(v.array(CandidateRecordResponseSchema)),
  totalMatches: v.nullish(v.number()),
});

/** One page of raw candidate rows from ``/api/candidates_filter``. */
export type CandidateFilterPageResponse = v.InferOutput<
  typeof CandidateFilterPageResponseSchema
>;

export const CandidateGetQuerySchema = v.strictObject({
  numPerPage: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  autosave: v.optional(v.boolean()),
  autosaveGroupIds: v.nullish(v.array(v.number())),
  savedStatus: v.optional(
    v.picklist([
      "all",
      "savedToAllSelected",
      "savedToAnySelected",
      "savedToAnyAccessible",
      "notSavedToAnyAccessible",
      "notSavedToAnySelected",
      "notSavedToAllSelected",
    ]),
  ),
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  groupIDs: v.nullish(v.string()),
  filterIDs: v.nullish(v.string()),
  sortByAnnotationOrigin: v.nullish(v.string()),
  sortByAnnotationKey: v.nullish(v.string()),
  sortByAnnotationOrder: v.nullish(v.string()),
  minAbsGalacticLatitude: v.nullish(v.number()),
  maxSgscore: v.nullish(v.number()),
  minNdethist: v.nullish(v.number()),
  maxDeltaT: v.nullish(v.number()),
  promptDeltaT: v.nullish(v.number()),
  crossmatchOrigin: v.optional(v.string()),
  annotationFilterList: v.nullish(v.string()),
  includePhotometry: v.optional(v.boolean()),
  includeSpectra: v.optional(v.boolean()),
  includeComments: v.optional(v.boolean()),
  includeFollowupRequests: v.optional(v.boolean()),
  includeAssociatedObjs: v.optional(v.boolean()),
  includeAlerts: v.optional(v.boolean()),
  classifications: v.nullish(v.array(v.string())),
  classificationsReject: v.nullish(v.array(v.string())),
  minRedshift: v.nullish(v.number()),
  maxRedshift: v.nullish(v.number()),
  listName: v.nullish(v.string()),
  listNameReject: v.nullish(v.string()),
  photometryAnnotationsFilter: v.nullish(v.array(v.string())),
  photometryAnnotationsFilterOrigin: v.nullish(v.array(v.string())),
  photometryAnnotationsFilterBefore: v.nullish(v.string()),
  photometryAnnotationsFilterAfter: v.nullish(v.string()),
  photometryAnnotationsFilterMinCount: v.optional(v.number()),
  localizationDateobs: v.nullish(v.string()),
  localizationName: v.nullish(v.string()),
  localizationCumprob: v.optional(v.number()),
  firstDetectionAfter: v.nullish(v.string()),
  lastDetectionBefore: v.nullish(v.string()),
  numberDetections: v.nullish(v.number()),
  requireDetections: v.optional(v.boolean()),
  excludeForcedPhotometry: v.optional(v.boolean()),
  nameOnly: v.optional(v.boolean()),
  objID: v.nullish(v.string()),
  queryID: v.nullish(v.string()),
  annotationExcludeOrigin: v.nullish(v.string()),
  annotationExcludeOutdatedDate: v.nullish(v.string()),
});

/** Query parameters for retrieving a single candidate or querying candidates. */
export type CandidateGetQuery = v.InferOutput<typeof CandidateGetQuerySchema>;

export const CandidatePassingAlertResponseSchema = v.strictObject({
  filter_id: v.nullish(v.number()),
  passing_alert_id: v.nullish(v.number()),
  passed_at: v.nullish(v.string()),
});

/** One alert that made an object pass a filter (a ``Candidate`` row). */
export type CandidatePassingAlertResponse = v.InferOutput<
  typeof CandidatePassingAlertResponseSchema
>;

export const CandidatePostSchema = v.strictObject({
  id: v.string(),
  ra: v.number(),
  dec: v.number(),
  filter_ids: v.array(v.number()),
  passed_at: v.string(),
  passing_alert_id: v.nullish(v.number()),
  ra_dis: v.nullish(v.number()),
  dec_dis: v.nullish(v.number()),
  ra_err: v.nullish(v.number()),
  dec_err: v.nullish(v.number()),
  offset: v.nullish(v.number()),
  t0: v.nullish(v.number()),
  redshift: v.nullish(v.number()),
  redshift_error: v.nullish(v.number()),
  redshift_origin: v.nullish(v.string()),
  host_id: v.nullish(v.number()),
  summary: v.nullish(v.string()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  dist_nearest_source: v.nullish(v.number()),
  mag_nearest_source: v.nullish(v.number()),
  e_mag_nearest_source: v.nullish(v.number()),
  transient: v.nullish(v.boolean()),
  varstar: v.nullish(v.boolean()),
  is_roid: v.nullish(v.boolean()),
  mpc_name: v.nullish(v.string()),
  tns_name: v.nullish(v.string()),
  tns_info: v.nullish(v.record(v.string(), v.unknown())),
  score: v.nullish(v.number()),
  origin: v.nullish(v.string()),
  alias: v.nullish(v.array(v.string())),
  detect_photometry_count: v.nullish(v.number()),
});

/**
 * Payload for posting a new candidate.
 *
 * Beyond the candidate's own fields, the server loads the body with the
 * ``Obj`` schema, so any ``Obj`` column may be set when the object does
 * not exist yet (and is updated in place when it does).
 */
export type CandidatePost = v.InferOutput<typeof CandidatePostSchema>;

export const CandidatePostBodySchema = v.strictObject({
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_dis: v.nullish(v.number()),
  dec_dis: v.nullish(v.number()),
  ra_err: v.nullish(v.number()),
  dec_err: v.nullish(v.number()),
  offset: v.nullish(v.number()),
  t0: v.nullish(v.number()),
  redshift: v.nullish(v.number()),
  redshift_error: v.nullish(v.number()),
  redshift_origin: v.nullish(v.string()),
  redshift_history: v.optional(v.unknown()),
  host_id: v.nullish(v.number()),
  summary: v.nullish(v.string()),
  summary_history: v.optional(v.unknown()),
  altdata: v.optional(v.unknown()),
  dist_nearest_source: v.nullish(v.number()),
  mag_nearest_source: v.nullish(v.number()),
  e_mag_nearest_source: v.nullish(v.number()),
  transient: v.nullish(v.boolean()),
  varstar: v.nullish(v.boolean()),
  is_roid: v.nullish(v.boolean()),
  mpc_name: v.nullish(v.string()),
  tns_name: v.nullish(v.string()),
  tns_info: v.optional(v.unknown()),
  score: v.nullish(v.number()),
  origin: v.nullish(v.string()),
  alias: v.nullish(v.array(v.string())),
  id: v.string(),
  filter_ids: v.array(v.number()),
  passed_at: v.string(),
  passing_alert_id: v.nullish(v.number()),
});

/** Request body for creating new candidate(s) (one per filter). */
export type CandidatePostBody = v.InferOutput<typeof CandidatePostBodySchema>;

export const CandidatePostResponseSchema = v.strictObject({
  ids: v.optional(v.array(v.number())),
});

/** Result of posting a new candidate. */
export type CandidatePostResponse = v.InferOutput<
  typeof CandidatePostResponseSchema
>;

export const CandidateResponseSchema = v.strictObject({
  id: v.string(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_dis: v.nullish(v.number()),
  dec_dis: v.nullish(v.number()),
  ra_err: v.nullish(v.number()),
  dec_err: v.nullish(v.number()),
  offset: v.nullish(v.number()),
  t0: v.nullish(v.number()),
  redshift: v.nullish(v.number()),
  redshift_error: v.nullish(v.number()),
  redshift_origin: v.nullish(v.string()),
  redshift_history: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  host_id: v.nullish(v.number()),
  summary: v.nullish(v.string()),
  summary_history: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  dist_nearest_source: v.nullish(v.number()),
  mag_nearest_source: v.nullish(v.number()),
  e_mag_nearest_source: v.nullish(v.number()),
  transient: v.nullish(v.boolean()),
  varstar: v.nullish(v.boolean()),
  is_roid: v.nullish(v.boolean()),
  mpc_name: v.nullish(v.string()),
  tns_name: v.nullish(v.string()),
  tns_info: v.nullish(v.record(v.string(), v.unknown())),
  score: v.nullish(v.number()),
  origin: v.nullish(v.string()),
  alias: v.nullish(v.array(v.string())),
  healpix: v.nullish(v.number()),
  detect_photometry_count: v.nullish(v.number()),
  internal_key: v.nullish(v.string()),
  thumbnails: v.nullish(v.array(ThumbnailResponseSchema)),
  photstats: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  host: v.nullish(GalaxyResponseSchema),
  is_source: v.optional(v.union([v.boolean(), v.number(), v.null()])),
  saved_groups: v.nullish(v.array(GroupResponseSchema)),
  classifications: v.nullish(v.array(ClassificationResponseSchema)),
  passing_group_ids: v.nullish(v.array(v.number())),
  filter_ids: v.nullish(v.array(v.number())),
  passing_alerts: v.nullish(v.array(CandidatePassingAlertResponseSchema)),
  tags: v.nullish(v.array(ObjTagResponseSchema)),
  annotations: v.nullish(v.array(AnnotationResponseSchema)),
  comments: v.nullish(v.array(CommentResponseSchema)),
  photometry: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  spectra: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  followup_requests: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  associated_objs: v.nullish(v.array(CandidateAssociatedObjResponseSchema)),
  last_detected_at: v.nullish(v.string()),
  gal_lon: v.nullish(v.number()),
  gal_lat: v.nullish(v.number()),
  luminosity_distance: v.nullish(v.number()),
  dm: v.nullish(v.number()),
  angular_diameter_distance: v.nullish(v.number()),
});

/**
 * An object that passed a filter: the serialized ``Obj`` columns plus
 * the scanning extras the candidate endpoints graft onto them.
 */
export type CandidateResponse = v.InferOutput<typeof CandidateResponseSchema>;

export const CandidatesPageResponseSchema = v.strictObject({
  candidates: v.array(CandidateResponseSchema),
  totalMatches: v.nullish(v.number()),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
  queryID: v.nullish(v.string()),
});

/** One page of results from a candidates query. */
export type CandidatesPageResponse = v.InferOutput<
  typeof CandidatesPageResponseSchema
>;

export const ScanReportGetQuerySchema = v.strictObject({
  numPerPage: v.optional(v.number()),
  page: v.optional(v.number()),
});

/** Query parameters for listing candidate scanning reports. */
export type ScanReportGetQuery = v.InferOutput<typeof ScanReportGetQuerySchema>;

export const ScanReportItemPatchBodySchema = v.strictObject({
  comment: v.nullish(v.string()),
});

/** Request body for updating a scanning report item. */
export type ScanReportItemPatchBody = v.InferOutput<
  typeof ScanReportItemPatchBodySchema
>;

export const ScanReportItemResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  scan_report_id: v.nullish(v.number()),
  data: v.nullish(v.record(v.string(), v.unknown())),
});

/** One saved candidate listed in a scanning report. */
export type ScanReportItemResponse = v.InferOutput<
  typeof ScanReportItemResponseSchema
>;

export const ScanReportPassedFiltersRangeSchema = v.strictObject({
  start_date: v.string(),
  end_date: v.string(),
});

/** Time range over which candidates must have passed a filter. */
export type ScanReportPassedFiltersRange = v.InferOutput<
  typeof ScanReportPassedFiltersRangeSchema
>;

export const ScanReportSavedCandidatesRangeSchema = v.strictObject({
  start_saved_date: v.string(),
  end_saved_date: v.string(),
});

/** Time range over which candidates must have been saved as sources. */
export type ScanReportSavedCandidatesRange = v.InferOutput<
  typeof ScanReportSavedCandidatesRangeSchema
>;

export const ScanReportPostSchema = v.strictObject({
  group_ids: v.array(v.number()),
  passed_filters_range: v.nullish(ScanReportPassedFiltersRangeSchema),
  saved_candidates_range: v.nullish(ScanReportSavedCandidatesRangeSchema),
  passed_filters_window_hours: v.nullish(v.number()),
  saved_candidates_window_hours: v.nullish(v.number()),
  gcn_event_dateobs: v.nullish(v.string()),
});

/** Payload for generating a candidate scanning report. */
export type ScanReportPost = v.InferOutput<typeof ScanReportPostSchema>;

export const ScanReportPostBodySchema = v.strictObject({
  group_ids: v.nullish(v.array(v.number())),
  passed_filters_range: v.nullish(v.record(v.string(), v.unknown())),
  saved_candidates_range: v.nullish(v.record(v.string(), v.unknown())),
  passed_filters_window_hours: v.nullish(v.number()),
  saved_candidates_window_hours: v.nullish(v.number()),
  gcn_event_dateobs: v.nullish(v.string()),
});

/** Request body for populating a candidate scanning report. */
export type ScanReportPostBody = v.InferOutput<typeof ScanReportPostBodySchema>;

export const ScanReportResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  author_id: v.nullish(v.number()),
  author: v.nullish(v.string()),
  options: v.nullish(v.record(v.string(), v.unknown())),
  groups: v.nullish(v.array(GroupResponseSchema)),
});

/** A candidate scanning report (a ``ScanReport``). */
export type ScanReportResponse = v.InferOutput<typeof ScanReportResponseSchema>;

export const ScanReportsPageResponseSchema = v.strictObject({
  reports: v.optional(v.array(ScanReportResponseSchema)),
  totalMatches: v.number(),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/** One page of candidate scanning reports. */
export type ScanReportsPageResponse = v.InferOutput<
  typeof ScanReportsPageResponseSchema
>;
