// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const CatalogQueryPostSchema = v.strictObject({
  allocation_id: v.number(),
  payload: v.record(v.string(), v.unknown()),
  status: v.nullish(v.string()),
  target_group_ids: v.nullish(v.array(v.number())),
});

/** Payload for submitting a catalog query. */
export type CatalogQueryPost = v.InferOutput<typeof CatalogQueryPostSchema>;

export const CatalogQueryPostBodySchema = v.strictObject({
  allocation_id: v.number(),
  payload: v.nullish(v.record(v.string(), v.unknown())),
  status: v.nullish(v.string()),
  target_group_ids: v.nullish(v.array(v.number())),
});

/** Request body for submitting a catalog query. */
export type CatalogQueryPostBody = v.InferOutput<
  typeof CatalogQueryPostBodySchema
>;

export const GaiaPhotometricAlertsQueryPostBodySchema = v.strictObject({
  telescope_name: v.nullish(v.string()),
  groupIDs: v.nullish(v.array(v.number())),
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
});

/** Request body for posting Gaia Photometric Alerts as sources. */
export type GaiaPhotometricAlertsQueryPostBody = v.InferOutput<
  typeof GaiaPhotometricAlertsQueryPostBodySchema
>;

export const SwiftLSXPSQueryPostBodySchema = v.strictObject({
  telescope_name: v.nullish(v.string()),
  groupIDs: v.nullish(v.array(v.number())),
});

/** Request body for posting Swift LSXPS objects as sources. */
export type SwiftLSXPSQueryPostBody = v.InferOutput<
  typeof SwiftLSXPSQueryPostBodySchema
>;

export const TessTransientsQueryPostBodySchema = v.strictObject({
  telescope_name: v.nullish(v.string()),
  groupIDs: v.nullish(v.array(v.number())),
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
});

/** Request body for posting TESS transients as sources. */
export type TessTransientsQueryPostBody = v.InferOutput<
  typeof TessTransientsQueryPostBodySchema
>;
