// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { ClassificationResponseSchema } from "./_cyclic.js";

export const ClassificationDeleteBodySchema = v.strictObject({
  label: v.optional(v.boolean()),
});

/** Request body for deleting classification(s). */
export type ClassificationDeleteBody = v.InferOutput<
  typeof ClassificationDeleteBodySchema
>;

export const ClassificationGetQuerySchema = v.strictObject({
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  includeTaxonomy: v.optional(v.boolean()),
  numPerPage: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
});

/** Query parameters for retrieving classifications. */
export type ClassificationGetQuery = v.InferOutput<
  typeof ClassificationGetQuerySchema
>;

export const ClassificationPostSchema = v.strictObject({
  obj_id: v.string(),
  classification: v.string(),
  taxonomy_id: v.number(),
  origin: v.nullish(v.string()),
  probability: v.nullish(v.number()),
  ml: v.nullish(v.boolean()),
  group_ids: v.nullish(v.array(v.number())),
  vote: v.nullish(v.boolean()),
  label: v.nullish(v.boolean()),
});

/** Payload for posting a classification. */
export type ClassificationPost = v.InferOutput<typeof ClassificationPostSchema>;

export const ClassificationPostItemSchema = v.strictObject({
  obj_id: v.nullish(v.string()),
  classification: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  taxonomy_id: v.nullish(v.number()),
  probability: v.nullish(v.number()),
  group_ids: v.nullish(v.array(v.number())),
  vote: v.nullish(v.boolean()),
  label: v.nullish(v.boolean()),
  ml: v.optional(v.union([v.boolean(), v.string(), v.null()])),
});

/**
 * A single classification. Cross-field checks (probability range, allowed
 * classes, ml value) are enforced by the handler with their own messages.
 */
export type ClassificationPostItem = v.InferOutput<
  typeof ClassificationPostItemSchema
>;

export const ClassificationPostBodySchema = v.strictObject({
  obj_id: v.nullish(v.string()),
  classification: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  taxonomy_id: v.nullish(v.number()),
  probability: v.nullish(v.number()),
  group_ids: v.nullish(v.array(v.number())),
  vote: v.nullish(v.boolean()),
  label: v.nullish(v.boolean()),
  ml: v.optional(v.union([v.boolean(), v.string(), v.null()])),
  classifications: v.nullish(v.array(ClassificationPostItemSchema)),
});

/**
 * Request body for posting a classification. Either a single classification
 * (top-level fields) or a batch (a list under `classifications`).
 */
export type ClassificationPostBody = v.InferOutput<
  typeof ClassificationPostBodySchema
>;

export const ClassificationPostResponseSchema = v.strictObject({
  classification_id: v.number(),
});

/** Result of posting a classification. */
export type ClassificationPostResponse = v.InferOutput<
  typeof ClassificationPostResponseSchema
>;

export const ClassificationPutBodySchema = v.strictObject({
  obj_id: v.nullish(v.string()),
  classification: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  taxonomy_id: v.nullish(v.number()),
  probability: v.nullish(v.number()),
  ml: v.optional(v.union([v.boolean(), v.string(), v.null()])),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for updating a classification. */
export type ClassificationPutBody = v.InferOutput<
  typeof ClassificationPutBodySchema
>;

export const ClassificationUpdateSchema = v.strictObject({
  classification: v.nullish(v.string()),
  taxonomy_id: v.nullish(v.number()),
  probability: v.nullish(v.number()),
  origin: v.nullish(v.string()),
  ml: v.nullish(v.boolean()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Payload for updating a classification. */
export type ClassificationUpdate = v.InferOutput<
  typeof ClassificationUpdateSchema
>;

export const ClassificationVotePostBodySchema = v.strictObject({
  vote: v.nullish(v.number()),
});

/** Request body for voting on a classification. */
export type ClassificationVotePostBody = v.InferOutput<
  typeof ClassificationVotePostBodySchema
>;

export const ClassificationsPageResponseSchema = v.strictObject({
  classifications: v.optional(v.array(ClassificationResponseSchema)),
  totalMatches: v.optional(v.number()),
});

/** One page of results from a classifications query. */
export type ClassificationsPageResponse = v.InferOutput<
  typeof ClassificationsPageResponseSchema
>;

export const ClassificationsPostResponseSchema = v.strictObject({
  classification_ids: v.optional(v.array(v.number())),
});

/** Result of posting a batch of classifications. */
export type ClassificationsPostResponse = v.InferOutput<
  typeof ClassificationsPostResponseSchema
>;

export const ObjClassificationGetQuerySchema = v.strictObject({
  includeSuperObjs: v.optional(v.boolean()),
});

/** Query parameters for retrieving an object's classifications. */
export type ObjClassificationGetQuery = v.InferOutput<
  typeof ObjClassificationGetQuerySchema
>;

export const ObjClassificationQueryGetQuerySchema = v.strictObject({
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
});

/** Query parameters for finding sources with classifications. */
export type ObjClassificationQueryGetQuery = v.InferOutput<
  typeof ObjClassificationQueryGetQuerySchema
>;
