// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { GroupResponseSchema } from "./_cyclic.js";

export const CommentAttachmentSchema = v.strictObject({
  body: v.nullable(v.string()),
  name: v.string(),
});

/** A comment file attachment (name + base64-encoded body). */
export type CommentAttachment = v.InferOutput<typeof CommentAttachmentSchema>;

export const CommentAttachmentBatchResponseSchema = v.strictObject({
  totalMatches: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/** Result of moving one page of comment attachments to disk. */
export type CommentAttachmentBatchResponse = v.InferOutput<
  typeof CommentAttachmentBatchResponseSchema
>;

export const CommentAttachmentCountsResponseSchema = v.strictObject({
  totalWithoutAttachmentBytes: v.optional(v.number()),
  totalWithAttachmentBytes: v.optional(v.number()),
});

/** How many comments still hold their attachment in the database. */
export type CommentAttachmentCountsResponse = v.InferOutput<
  typeof CommentAttachmentCountsResponseSchema
>;

export const CommentAttachmentGetQuerySchema = v.strictObject({
  download: v.optional(v.boolean()),
  preview: v.optional(v.boolean()),
});

/** Query parameters for retrieving a comment attachment. */
export type CommentAttachmentGetQuery = v.InferOutput<
  typeof CommentAttachmentGetQuerySchema
>;

export const CommentAttachmentResponseSchema = v.strictObject({
  commentId: v.number(),
  attachment: v.nullish(v.string()),
  attachmentName: v.nullish(v.string()),
});

/** The decoded contents of a comment attachment. */
export type CommentAttachmentResponse = v.InferOutput<
  typeof CommentAttachmentResponseSchema
>;

export const CommentAttachmentUpdatePostQuerySchema = v.strictObject({
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/** Query parameters for the comment attachment migration. */
export type CommentAttachmentUpdatePostQuery = v.InferOutput<
  typeof CommentAttachmentUpdatePostQuerySchema
>;

export const CommentDetailResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  text: v.nullish(v.string()),
  channel: v.nullish(v.string()),
  system: v.nullish(v.boolean()),
  attachment_name: v.nullish(v.string()),
  attachment_bytes: v.optional(v.unknown()),
  origin: v.nullish(v.string()),
  bot: v.nullish(v.boolean()),
  author_id: v.nullish(v.number()),
  author: v.nullish(v.record(v.string(), v.unknown())),
  groups: v.nullish(v.array(GroupResponseSchema)),
  obj_id: v.nullish(v.string()),
  spectrum_id: v.nullish(v.number()),
  gcn_id: v.nullish(v.number()),
  earthquake_id: v.nullish(v.number()),
  shift_id: v.nullish(v.number()),
  obj: v.nullish(v.record(v.string(), v.unknown())),
  spectrum: v.nullish(v.record(v.string(), v.unknown())),
  gcn: v.nullish(v.record(v.string(), v.unknown())),
  shift: v.nullish(v.record(v.string(), v.unknown())),
  earthquake: v.nullish(v.record(v.string(), v.unknown())),
  dateobs: v.nullish(v.string()),
  resourceType: v.nullish(v.string()),
});

/** A single comment, as returned by the single-comment endpoint. */
export type CommentDetailResponse = v.InferOutput<
  typeof CommentDetailResponseSchema
>;

export const CommentGetQuerySchema = v.strictObject({
  text: v.nullish(v.string()),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
  channel: v.nullish(v.string()),
});

/** Query parameters for retrieving comments. */
export type CommentGetQuery = v.InferOutput<typeof CommentGetQuerySchema>;

export const CommentPostBodySchema = v.strictObject({
  text: v.string(),
  group_ids: v.nullish(v.array(v.number())),
  attachment: v.nullish(CommentAttachmentSchema),
  channel: v.nullish(v.string()),
  origin: v.nullish(v.literal("scanning")),
});

/** Request body for posting a comment. */
export type CommentPostBody = v.InferOutput<typeof CommentPostBodySchema>;

export const CommentPostResponseSchema = v.object({
  comment_id: v.number(),
});

/** Data payload returned when posting a comment. */
export type CommentPostResponse = v.InferOutput<
  typeof CommentPostResponseSchema
>;

export const CommentPutBodySchema = v.strictObject({
  text: v.nullish(v.string()),
  group_ids: v.nullish(v.array(v.number())),
  attachment: v.nullish(CommentAttachmentSchema),
});

/** Request body for updating a comment. */
export type CommentPutBody = v.InferOutput<typeof CommentPutBodySchema>;
