// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const DataAccessRequestGetQuerySchema = v.strictObject({
  objId: v.nullish(v.string()),
  status: v.nullish(v.string()),
  direction: v.nullish(v.string()),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/** Query parameters for listing data access requests. */
export type DataAccessRequestGetQuery = v.InferOutput<
  typeof DataAccessRequestGetQuerySchema
>;

export const DataAccessRequestPatchBodySchema = v.strictObject({
  status: v.string(),
  groupID: v.nullish(v.number()),
});

/** Request body for answering a request. */
export type DataAccessRequestPatchBody = v.InferOutput<
  typeof DataAccessRequestPatchBodySchema
>;

export const PhotometryDatasetSchema = v.strictObject({
  ownerID: v.number(),
  instrumentID: v.number(),
  filter: v.string(),
});

/** One owner's photometry on an object in a single instrument/filter. */
export type PhotometryDataset = v.InferOutput<typeof PhotometryDatasetSchema>;

export const DataAccessRequestPostBodySchema = v.strictObject({
  objId: v.string(),
  photometry: v.optional(v.array(PhotometryDatasetSchema)),
  spectrumIDs: v.optional(v.array(v.number())),
  message: v.nullish(v.string()),
});

/** Request body for asking an owner for data on an object. */
export type DataAccessRequestPostBody = v.InferOutput<
  typeof DataAccessRequestPostBodySchema
>;
