// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const BulkDataShareResponseSchema = v.strictObject({
  action: v.picklist(["add", "remove"]),
  counts: v.optional(v.record(v.string(), v.number())),
});

/**
 * Result of bulk-sharing data between groups.
 *
 * ``counts`` maps each requested data type (``spectra``/``photometry``) to
 * the number of rows inserted or deleted.
 */
export type BulkDataShareResponse = v.InferOutput<
  typeof BulkDataShareResponseSchema
>;

export const SpectrumGroupRemovalResponseSchema = v.strictObject({
  message: v.nullish(v.string()),
});

/**
 * Result of removing a group from a spectrum.
 *
 * ``message`` only appears on the no-op path, when the group was not on the
 * spectrum; the removal itself returns no data.
 */
export type SpectrumGroupRemovalResponse = v.InferOutput<
  typeof SpectrumGroupRemovalResponseSchema
>;
