// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const CronJobRunSummaryResponseSchema = v.strictObject({
  summary: v.nullish(v.string()),
  output: v.nullish(v.string()),
});

/** The latest run of one cron job script. */
export type CronJobRunSummaryResponse = v.InferOutput<
  typeof CronJobRunSummaryResponseSchema
>;

export const DBStatsHistoryResponseSchema = v.strictObject({
  interval: v.picklist(["hour", "day", "week", "month"]),
  startDate: v.string(),
  endDate: v.string(),
  bins: v.optional(v.array(v.string())),
  tables: v.optional(v.array(v.string())),
  counts: v.optional(v.record(v.string(), v.array(v.number()))),
});

/**
 * Bucketed row counts over time.
 *
 * ``tables`` lists every table the endpoint can count; ``counts`` only
 * carries the tables the query asked for, each list aligned with ``bins``.
 * The dates and bins are naive UTC ISO-8601 strings.
 */
export type DBStatsHistoryResponse = v.InferOutput<
  typeof DBStatsHistoryResponseSchema
>;

export const DBStatsResponseSchema = v.strictObject({
  "Number of photometry (approx)": v.nullish(v.number()),
  "Number of candidates": v.nullish(v.number()),
  "Number of sources": v.nullish(v.number()),
  "Number of source views": v.nullish(v.number()),
  "Number of objs": v.nullish(v.number()),
  "Number of spectra": v.nullish(v.number()),
  "Number of groups": v.nullish(v.number()),
  "Number of users": v.nullish(v.number()),
  "Number of tokens": v.nullish(v.number()),
  "Number of filters": v.nullish(v.number()),
  "Number of telescopes": v.nullish(v.number()),
  "Number of instruments": v.nullish(v.number()),
  "Number of comments": v.nullish(v.number()),
  "Number of annotations": v.nullish(v.number()),
  "Number of thumbnails": v.nullish(v.number()),
  "Number of GCN events": v.nullish(v.number()),
  "Latest cron job run times & statuses": v.optional(
    v.array(CronJobRunSummaryResponseSchema),
  ),
});

/**
 * Row counts of the major tables plus the cron job run log.
 *
 * The wire keys are the human-readable labels the handler builds, spaces
 * and all, hence the aliases.
 */
export type DBStatsResponse = v.InferOutput<typeof DBStatsResponseSchema>;
