// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import {
  CommentResponseSchema,
  ReminderResponseSchema,
  UserResponseSchema,
} from "./_cyclic.js";

export const EarthquakeGetQuerySchema = v.strictObject({
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  statusKeep: v.nullish(v.string()),
  statusRemove: v.nullish(v.string()),
  numPerPage: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
});

/** Query parameters for retrieving Earthquake events. */
export type EarthquakeGetQuery = v.InferOutput<typeof EarthquakeGetQuerySchema>;

export const EarthquakeMeasurementBodySchema = v.strictObject({
  rfamp: v.nullish(v.number()),
  lockloss: v.nullish(v.number()),
});

/**
 * Request body for posting or updating a ground velocity measurement;
 * at least one of rfamp or lockloss must be provided.
 */
export type EarthquakeMeasurementBody = v.InferOutput<
  typeof EarthquakeMeasurementBodySchema
>;

export const EarthquakeMeasurementResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  event_id: v.nullish(v.number()),
  detector_id: v.nullish(v.number()),
  rfamp: v.nullish(v.number()),
  lockloss: v.nullish(v.number()),
});

/** A measured ground velocity (an ``EarthquakeMeasured`` row). */
export type EarthquakeMeasurementResponse = v.InferOutput<
  typeof EarthquakeMeasurementResponseSchema
>;

export const EarthquakeNoticeResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sent_by_id: v.nullish(v.number()),
  sent_by: v.nullish(UserResponseSchema),
  content: v.optional(v.unknown()),
  event_id: v.nullish(v.string()),
  lat: v.nullish(v.number()),
  lon: v.nullish(v.number()),
  depth: v.nullish(v.number()),
  magnitude: v.nullish(v.number()),
  date: v.nullish(v.string()),
  country: v.nullish(v.string()),
});

/**
 * A single notice about an earthquake.
 *
 * ``content`` is the raw QuakeML document, a deferred ``LargeBinary`` column,
 * so it is only present on the single-event endpoint (which undefers it).
 */
export type EarthquakeNoticeResponse = v.InferOutput<
  typeof EarthquakeNoticeResponseSchema
>;

export const EarthquakePostSchema = v.strictObject({
  xml: v.nullish(v.string()),
  event_id: v.nullish(v.string()),
  date: v.nullish(v.string()),
  latitude: v.nullish(v.number()),
  longitude: v.nullish(v.number()),
  depth: v.nullish(v.number()),
  magnitude: v.nullish(v.number()),
});

/** Payload for ingesting an earthquake event. */
export type EarthquakePost = v.InferOutput<typeof EarthquakePostSchema>;

export const EarthquakePostBodySchema = v.strictObject({
  xml: v.nullish(v.string()),
  event_id: v.nullish(v.string()),
  date: v.nullish(v.string()),
  latitude: v.nullish(v.number()),
  longitude: v.nullish(v.number()),
  depth: v.nullish(v.number()),
  magnitude: v.nullish(v.number()),
});

/**
 * Request body for ingesting an earthquake event, either from a QuakeML
 * xml document or from explicit event properties.
 */
export type EarthquakePostBody = v.InferOutput<typeof EarthquakePostBodySchema>;

export const EarthquakePostResponseSchema = v.object({
  id: v.union([v.string(), v.number(), v.null()]),
});

/** ID of the ingested earthquake event. */
export type EarthquakePostResponse = v.InferOutput<
  typeof EarthquakePostResponseSchema
>;

export const EarthquakePredictionResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  event_id: v.nullish(v.number()),
  detector_id: v.nullish(v.number()),
  d: v.nullish(v.number()),
  p: v.nullish(v.string()),
  s: v.nullish(v.string()),
  r2p0: v.nullish(v.string()),
  r3p5: v.nullish(v.string()),
  r5p0: v.nullish(v.string()),
  rfamp: v.nullish(v.number()),
  lockloss: v.nullish(v.number()),
});

/** A predicted seismic arrival. */
export type EarthquakePredictionResponse = v.InferOutput<
  typeof EarthquakePredictionResponseSchema
>;

export const EarthquakeResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sent_by_id: v.nullish(v.number()),
  sent_by: v.nullish(UserResponseSchema),
  event_id: v.nullish(v.string()),
  event_uri: v.nullish(v.string()),
  status: v.nullish(v.string()),
  notices: v.optional(v.array(EarthquakeNoticeResponseSchema)),
  predictions: v.optional(v.array(EarthquakePredictionResponseSchema)),
  measurements: v.optional(v.array(EarthquakeMeasurementResponseSchema)),
  comments: v.optional(v.array(CommentResponseSchema)),
  reminders: v.optional(v.array(ReminderResponseSchema)),
});

/**
 * An earthquake event.
 *
 * The single-event endpoint replaces ``comments`` with hand-built dicts that
 * drop ``attachment_bytes`` and add ``author`` and ``resourceType``.
 */
export type EarthquakeResponse = v.InferOutput<typeof EarthquakeResponseSchema>;

export const EarthquakesPageResponseSchema = v.strictObject({
  events: v.optional(v.array(EarthquakeResponseSchema)),
  totalMatches: v.optional(v.number()),
});

/** One page of results from an earthquake events query. */
export type EarthquakesPageResponse = v.InferOutput<
  typeof EarthquakesPageResponseSchema
>;
