// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { StreamResponseSchema } from "./streams.js";

export const FilterGetQuerySchema = v.strictObject({
  group_id: v.nullish(v.number()),
  stream_id: v.nullish(v.number()),
});

/** Query parameters for listing filters. */
export type FilterGetQuery = v.InferOutput<typeof FilterGetQuerySchema>;

export const FilterPatchSchema = v.strictObject({
  name: v.nullish(v.string()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  group_id: v.nullish(v.number()),
  stream_id: v.nullish(v.number()),
  autosave: v.nullish(v.boolean()),
});

/** Payload for updating a filter. */
export type FilterPatch = v.InferOutput<typeof FilterPatchSchema>;

export const FilterPatchBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  group_id: v.nullish(v.number()),
  stream_id: v.nullish(v.number()),
  broker_id: v.nullish(v.number()),
  autosave: v.nullish(v.boolean()),
});

/** Request body for updating a filter. */
export type FilterPatchBody = v.InferOutput<typeof FilterPatchBodySchema>;

export const FilterPostSchema = v.strictObject({
  name: v.string(),
  stream_id: v.number(),
  group_id: v.number(),
  broker_id: v.nullish(v.number()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
});

/** Payload for creating a filter. */
export type FilterPost = v.InferOutput<typeof FilterPostSchema>;

export const FilterPostBodySchema = v.strictObject({
  name: v.string(),
  stream_id: v.number(),
  group_id: v.number(),
  broker_id: v.nullish(v.number()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
});

/** Request body for creating a filter. */
export type FilterPostBody = v.InferOutput<typeof FilterPostBodySchema>;

export const FilterPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating a filter. */
export type FilterPostResponse = v.InferOutput<typeof FilterPostResponseSchema>;

export const FilterResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  name: v.nullish(v.string()),
  stream_id: v.nullish(v.number()),
  group_id: v.nullish(v.number()),
  broker_id: v.nullish(v.number()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  autosave: v.nullish(v.boolean()),
  stream: v.nullish(StreamResponseSchema),
});

/** An alert-stream filter belonging to a group. */
export type FilterResponse = v.InferOutput<typeof FilterResponseSchema>;
