// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import {
  AllocationResponseSchema,
  FacilityTransactionRequestResponseSchema,
  FacilityTransactionResponseSchema,
  GroupResponseSchema,
  UserResponseSchema,
} from "./_cyclic.js";

export const AssignmentPostBodySchema = v.strictObject({
  run_id: v.number(),
  obj_id: v.string(),
  priority: v.string(),
  status: v.nullish(v.string()),
  comment: v.nullish(v.string()),
});

/** Request body for posting a new observing-run assignment. */
export type AssignmentPostBody = v.InferOutput<typeof AssignmentPostBodySchema>;

export const AssignmentPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when posting a new assignment. */
export type AssignmentPostResponse = v.InferOutput<
  typeof AssignmentPostResponseSchema
>;

export const AssignmentPutBodySchema = v.strictObject({
  run_id: v.nullish(v.number()),
  obj_id: v.nullish(v.string()),
  priority: v.nullish(v.string()),
  status: v.nullish(v.string()),
  comment: v.nullish(v.string()),
});

/** Request body for updating an observing-run assignment. */
export type AssignmentPutBody = v.InferOutput<typeof AssignmentPutBodySchema>;

export const DefaultFollowupRequestPatchBodySchema = v.strictObject({
  payload: v.nullish(v.record(v.string(), v.unknown())),
  allocation_id: v.nullish(v.number()),
  target_group_ids: v.nullish(v.array(v.number())),
  default_followup_name: v.nullish(v.string()),
  source_filter: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  not_if_duplicates: v.nullish(v.boolean()),
  source_group_ids: v.nullish(v.array(v.number())),
  ignore_source_group_ids: v.nullish(v.array(v.number())),
  not_if_classified: v.nullish(v.boolean()),
  not_if_spectra_exist: v.nullish(v.boolean()),
  not_if_tns_classified: v.nullish(v.boolean()),
  not_if_tns_reported: v.nullish(v.number()),
  not_if_assignment_exists: v.nullish(v.boolean()),
  ignore_allocation_ids: v.nullish(v.array(v.number())),
  radius: v.nullish(v.number()),
  priority_order: v.nullish(v.string()),
  validity_days: v.nullish(v.number()),
  comment: v.nullish(v.string()),
  implements_update: v.nullish(v.boolean()),
});

/**
 * Fields to change on a default follow-up request; all are optional.
 *
 * Constraint keys are merged into the stored constraints rather than
 * replacing them, so changing one leaves the rest intact.
 */
export type DefaultFollowupRequestPatchBody = v.InferOutput<
  typeof DefaultFollowupRequestPatchBodySchema
>;

export const DefaultFollowupRequestPostSchema = v.strictObject({
  allocation_id: v.number(),
  payload: v.record(v.string(), v.unknown()),
  default_followup_name: v.string(),
  source_filter: v.record(v.string(), v.unknown()),
  target_group_ids: v.nullish(v.array(v.number())),
  comment: v.nullish(v.string()),
  implements_update: v.nullish(v.boolean()),
  priority_order: v.nullish(v.string()),
  validity_days: v.nullish(v.number()),
  radius: v.nullish(v.number()),
  not_if_duplicates: v.nullish(v.boolean()),
  source_group_ids: v.nullish(v.array(v.number())),
  ignore_source_group_ids: v.nullish(v.array(v.number())),
  not_if_classified: v.nullish(v.boolean()),
  not_if_spectra_exist: v.nullish(v.boolean()),
  not_if_tns_classified: v.nullish(v.boolean()),
  not_if_tns_reported: v.nullish(v.number()),
  not_if_assignment_exists: v.nullish(v.boolean()),
  ignore_allocation_ids: v.nullish(v.array(v.number())),
});

/** Payload for creating a default follow-up request. */
export type DefaultFollowupRequestPost = v.InferOutput<
  typeof DefaultFollowupRequestPostSchema
>;

export const DefaultFollowupRequestPostBodySchema = v.strictObject({
  payload: v.record(v.string(), v.unknown()),
  allocation_id: v.number(),
  target_group_ids: v.nullish(v.array(v.number())),
  default_followup_name: v.string(),
  source_filter: v.union([v.record(v.string(), v.unknown()), v.string()]),
  not_if_duplicates: v.nullish(v.boolean()),
  source_group_ids: v.nullish(v.array(v.number())),
  ignore_source_group_ids: v.nullish(v.array(v.number())),
  not_if_classified: v.nullish(v.boolean()),
  not_if_spectra_exist: v.nullish(v.boolean()),
  not_if_tns_classified: v.nullish(v.boolean()),
  not_if_tns_reported: v.nullish(v.number()),
  not_if_assignment_exists: v.nullish(v.boolean()),
  ignore_allocation_ids: v.nullish(v.array(v.number())),
  radius: v.nullish(v.number()),
  priority_order: v.nullish(v.string()),
  validity_days: v.nullish(v.number()),
  comment: v.nullish(v.string()),
  implements_update: v.nullish(v.boolean()),
});

/** Request body for creating a default follow-up request. */
export type DefaultFollowupRequestPostBody = v.InferOutput<
  typeof DefaultFollowupRequestPostBodySchema
>;

export const DefaultFollowupRequestPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating a default follow-up request. */
export type DefaultFollowupRequestPostResponse = v.InferOutput<
  typeof DefaultFollowupRequestPostResponseSchema
>;

export const DefaultFollowupRequestResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  requester_id: v.nullish(v.number()),
  allocation_id: v.nullish(v.number()),
  payload: v.optional(v.record(v.string(), v.unknown())),
  default_followup_name: v.nullish(v.string()),
  source_filter: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  constraints: v.nullish(v.record(v.string(), v.unknown())),
  priority_order: v.nullish(v.string()),
  validity_days: v.nullish(v.number()),
  comment: v.nullish(v.string()),
  implements_update: v.nullish(v.boolean()),
  allocation: v.nullish(AllocationResponseSchema),
  requester: v.nullish(UserResponseSchema),
  target_groups: v.optional(v.array(GroupResponseSchema)),
});

/** A default follow-up request (``DefaultFollowupRequest``). */
export type DefaultFollowupRequestResponse = v.InferOutput<
  typeof DefaultFollowupRequestResponseSchema
>;

export const FollowupRequestCommentPutBodySchema = v.strictObject({
  comment: v.nullish(v.string()),
});

/** Request body for updating a follow-up request comment. */
export type FollowupRequestCommentPutBody = v.InferOutput<
  typeof FollowupRequestCommentPutBodySchema
>;

export const FollowupRequestCommentPutResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when updating a follow-up request comment. */
export type FollowupRequestCommentPutResponse = v.InferOutput<
  typeof FollowupRequestCommentPutResponseSchema
>;

export const FollowupRequestDeleteBodySchema = v.strictObject({
  refreshSource: v.optional(v.boolean()),
  refreshRequests: v.optional(v.boolean()),
});

/** Request body for deleting a follow-up request. */
export type FollowupRequestDeleteBody = v.InferOutput<
  typeof FollowupRequestDeleteBodySchema
>;

export const FollowupRequestGetQuerySchema = v.strictObject({
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  observationStartDate: v.nullish(v.string()),
  observationEndDate: v.nullish(v.string()),
  sourceID: v.nullish(v.string()),
  instrumentID: v.nullish(v.number()),
  allocationID: v.nullish(v.number()),
  requesters: v.optional(v.array(v.number())),
  priorityThreshold: v.nullish(v.number()),
  status: v.nullish(v.string()),
  includeObjThumbnails: v.optional(v.boolean()),
  sortBy: v.optional(v.picklist(["created_at", "modified", "status", "obj"])),
  sortOrder: v.optional(v.picklist(["asc", "desc"])),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/** Query parameters for retrieving followup requests. */
export type FollowupRequestGetQuery = v.InferOutput<
  typeof FollowupRequestGetQuerySchema
>;

export const FollowupRequestPostSchema = v.strictObject({
  obj_id: v.string(),
  allocation_id: v.number(),
  payload: v.record(v.string(), v.unknown()),
  target_group_ids: v.nullish(v.array(v.number())),
});

/** Payload for submitting a follow-up request. */
export type FollowupRequestPost = v.InferOutput<
  typeof FollowupRequestPostSchema
>;

export const FollowupRequestPostBodySchema = v.strictObject({
  obj_id: v.string(),
  payload: v.nullish(v.record(v.string(), v.unknown())),
  status: v.nullish(v.string()),
  allocation_id: v.number(),
  target_group_ids: v.nullish(v.array(v.number())),
  not_if_duplicates: v.nullish(v.boolean()),
  source_group_ids: v.nullish(v.array(v.number())),
  not_if_classified: v.nullish(v.boolean()),
  not_if_spectra_exist: v.nullish(v.boolean()),
  not_if_tns_classified: v.nullish(v.boolean()),
  not_if_tns_reported: v.nullish(v.number()),
  not_if_assignment_exists: v.nullish(v.boolean()),
  ignore_source_group_ids: v.nullish(v.array(v.number())),
  radius: v.nullish(v.number()),
  ignore_allocation_ids: v.nullish(v.array(v.number())),
  refreshSource: v.optional(v.boolean()),
  refreshRequests: v.optional(v.boolean()),
});

/** Request body for submitting a new follow-up request. */
export type FollowupRequestPostBody = v.InferOutput<
  typeof FollowupRequestPostBodySchema
>;

export const FollowupRequestPostResponseSchema = v.object({
  id: v.nullable(v.number()),
  request_status: v.nullish(v.string()),
  ignored: v.nullish(v.boolean()),
  message: v.nullish(v.string()),
});

/** Data payload returned when posting a follow-up request. */
export type FollowupRequestPostResponse = v.InferOutput<
  typeof FollowupRequestPostResponseSchema
>;

export const FollowupRequestPrioritizationPutBodySchema = v.strictObject({
  requestIds: v.nullish(v.array(v.number())),
  priorityType: v.optional(v.string()),
  magnitudeOrdering: v.optional(v.string()),
  localizationId: v.nullish(v.number()),
  minimumPriority: v.optional(v.number()),
  maximumPriority: v.optional(v.number()),
});

/** Request body for reprioritizing follow-up requests. */
export type FollowupRequestPrioritizationPutBody = v.InferOutput<
  typeof FollowupRequestPrioritizationPutBodySchema
>;

export const FollowupRequestPutBodySchema = v.strictObject({
  obj_id: v.nullish(v.string()),
  payload: v.nullish(v.record(v.string(), v.unknown())),
  status: v.nullish(v.string()),
  allocation_id: v.nullish(v.number()),
  target_group_ids: v.nullish(v.array(v.number())),
  not_if_duplicates: v.nullish(v.boolean()),
  source_group_ids: v.nullish(v.array(v.number())),
  not_if_classified: v.nullish(v.boolean()),
  not_if_spectra_exist: v.nullish(v.boolean()),
  not_if_tns_classified: v.nullish(v.boolean()),
  not_if_tns_reported: v.nullish(v.number()),
  not_if_assignment_exists: v.nullish(v.boolean()),
  ignore_source_group_ids: v.nullish(v.array(v.number())),
  radius: v.nullish(v.number()),
  ignore_allocation_ids: v.nullish(v.array(v.number())),
  refreshSource: v.optional(v.boolean()),
  refreshRequests: v.optional(v.boolean()),
});

/**
 * Request body for updating a follow-up request.
 *
 * Every field is optional: a body containing ``status`` performs a
 * status-only update, otherwise the request is (re)submitted/updated and the
 * marshmallow ``FollowupRequestPost`` schema enforces the required fields.
 */
export type FollowupRequestPutBody = v.InferOutput<
  typeof FollowupRequestPutBodySchema
>;

export const FollowupRequestWatcherResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  followuprequest_id: v.nullish(v.number()),
  user_id: v.nullish(v.number()),
});

/** A user watching a follow-up request (``FollowupRequestUser``). */
export type FollowupRequestWatcherResponse = v.InferOutput<
  typeof FollowupRequestWatcherResponseSchema
>;

export const FollowupRequestResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  allocation_id: v.nullish(v.number()),
  requester_id: v.nullish(v.number()),
  last_modified_by_id: v.nullish(v.number()),
  payload: v.optional(v.record(v.string(), v.unknown())),
  status: v.nullish(v.string()),
  comment: v.nullish(v.string()),
  obj: v.nullish(v.record(v.string(), v.unknown())),
  allocation: v.nullish(AllocationResponseSchema),
  requester: v.nullish(UserResponseSchema),
  last_modified_by: v.nullish(UserResponseSchema),
  target_groups: v.optional(v.array(GroupResponseSchema)),
  watchers: v.optional(v.array(FollowupRequestWatcherResponseSchema)),
  transactions: v.optional(v.array(FacilityTransactionResponseSchema)),
  transaction_requests: v.optional(
    v.array(FacilityTransactionRequestResponseSchema),
  ),
  photometry: v.optional(v.array(v.record(v.string(), v.unknown()))),
  photometric_series: v.optional(v.array(v.record(v.string(), v.unknown()))),
  spectra: v.optional(v.array(v.record(v.string(), v.unknown()))),
  rise_time_utc: v.nullish(v.string()),
  set_time_utc: v.nullish(v.string()),
});

/** A follow-up observation request (``FollowupRequest``). */
export type FollowupRequestResponse = v.InferOutput<
  typeof FollowupRequestResponseSchema
>;

export const FollowupRequestSchedulerGetQuerySchema = v.strictObject({
  sourceID: v.nullish(v.string()),
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  status: v.nullish(v.string()),
  priorityThreshold: v.nullish(v.number()),
  timeResolution: v.optional(v.number()),
  observationStartDate: v.nullish(v.string()),
  observationEndDate: v.nullish(v.string()),
  includeStandards: v.optional(v.boolean()),
  standardsOnly: v.optional(v.boolean()),
  standardType: v.optional(v.string()),
  magnitudeRange: v.nullish(v.string()),
  output_format: v.optional(v.string()),
});

/** Query parameters for retrieving a followup requests schedule. */
export type FollowupRequestSchedulerGetQuery = v.InferOutput<
  typeof FollowupRequestSchedulerGetQuerySchema
>;

export const FollowupRequestWatcherDeleteBodySchema = v.strictObject({
  refreshSource: v.optional(v.boolean()),
  refreshRequests: v.optional(v.boolean()),
});

/** Request body for removing a follow-up request from the watch list. */
export type FollowupRequestWatcherDeleteBody = v.InferOutput<
  typeof FollowupRequestWatcherDeleteBodySchema
>;

export const FollowupRequestWatcherPostBodySchema = v.strictObject({
  refreshSource: v.optional(v.boolean()),
  refreshRequests: v.optional(v.boolean()),
});

/** Request body for adding a follow-up request to the watch list. */
export type FollowupRequestWatcherPostBody = v.InferOutput<
  typeof FollowupRequestWatcherPostBodySchema
>;

export const FollowupRequestsPageResponseSchema = v.strictObject({
  followup_requests: v.optional(v.array(FollowupRequestResponseSchema)),
  totalMatches: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/** One page of results from a follow-up requests query. */
export type FollowupRequestsPageResponse = v.InferOutput<
  typeof FollowupRequestsPageResponseSchema
>;

export const PhotometryRequestGetQuerySchema = v.strictObject({
  refreshSource: v.optional(v.boolean()),
  refreshRequests: v.optional(v.boolean()),
});

/** Query parameters for retrieving a photometry request. */
export type PhotometryRequestGetQuery = v.InferOutput<
  typeof PhotometryRequestGetQuerySchema
>;

export const PhotometryRequestStatusResponseSchema = v.strictObject({
  id: v.number(),
  request_status: v.nullish(v.string()),
});

/** Status of a follow-up request after a photometry retrieval. */
export type PhotometryRequestStatusResponse = v.InferOutput<
  typeof PhotometryRequestStatusResponseSchema
>;
