// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const GalaxyResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  catalog_id: v.nullish(v.number()),
  name: v.nullish(v.string()),
  alt_name: v.nullish(v.string()),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  healpix: v.nullish(v.number()),
  distmpc: v.nullish(v.number()),
  distmpc_unc: v.nullish(v.number()),
  redshift: v.nullish(v.number()),
  redshift_error: v.nullish(v.number()),
  sfr_fuv: v.nullish(v.number()),
  sfr_w4: v.nullish(v.number()),
  mstar: v.nullish(v.number()),
  magb: v.nullish(v.number()),
  magk: v.nullish(v.number()),
  mag_fuv: v.nullish(v.number()),
  mag_nuv: v.nullish(v.number()),
  mag_w1: v.nullish(v.number()),
  mag_w2: v.nullish(v.number()),
  mag_w3: v.nullish(v.number()),
  mag_w4: v.nullish(v.number()),
  a: v.nullish(v.number()),
  b2a: v.nullish(v.number()),
  pa: v.nullish(v.number()),
  btc: v.nullish(v.number()),
  objects: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  probability: v.nullish(v.number()),
});

/** A galaxy from a galaxy catalog (a ``Galaxy`` row). */
export type GalaxyResponse = v.InferOutput<typeof GalaxyResponseSchema>;

export const GalaxiesPageResponseSchema = v.strictObject({
  galaxies: v.optional(v.array(GalaxyResponseSchema)),
  totalMatches: v.optional(v.number()),
  sortBy: v.nullish(v.string()),
  sortOrder: v.nullish(v.string()),
  page: v.nullish(v.number()),
  numPerPage: v.nullish(v.number()),
  geojson: v.nullish(v.record(v.string(), v.unknown())),
});

/** One page of results from a galaxy catalog query. */
export type GalaxiesPageResponse = v.InferOutput<
  typeof GalaxiesPageResponseSchema
>;

export const GalaxyASCIIFilePostBodySchema = v.strictObject({
  catalogName: v.nullish(v.string()),
  catalogDescription: v.nullish(v.string()),
  catalogURL: v.nullish(v.string()),
  catalogData: v.nullish(v.string()),
});

/** Request body for uploading galaxies from an ASCII file. */
export type GalaxyASCIIFilePostBody = v.InferOutput<
  typeof GalaxyASCIIFilePostBodySchema
>;

export const GalaxyCatalogASCIIPostSchema = v.strictObject({
  catalogName: v.string(),
  catalogData: v.string(),
  catalogDescription: v.nullish(v.string()),
  catalogURL: v.nullish(v.string()),
});

/** Payload for uploading a galaxy catalog from an ASCII file. */
export type GalaxyCatalogASCIIPost = v.InferOutput<
  typeof GalaxyCatalogASCIIPostSchema
>;

export const GalaxyCatalogCountResponseSchema = v.strictObject({
  catalog_name: v.string(),
  catalog_count: v.nullish(v.number()),
});

/** A galaxy catalog name with its galaxy count. */
export type GalaxyCatalogCountResponse = v.InferOutput<
  typeof GalaxyCatalogCountResponseSchema
>;

export const GalaxyCatalogFitsPostBodySchema = v.strictObject({
  file_name: v.nullish(v.string()),
  file_url: v.nullish(v.string()),
});

/** Request body for uploading galaxies from a FITS catalog. */
export type GalaxyCatalogFitsPostBody = v.InferOutput<
  typeof GalaxyCatalogFitsPostBodySchema
>;

export const GalaxyCatalogGetQuerySchema = v.strictObject({
  catalog_name: v.nullish(v.string()),
  ra: v.nullish(v.string()),
  dec: v.nullish(v.string()),
  radius: v.nullish(v.string()),
  galaxyName: v.nullish(v.string()),
  minDistance: v.nullish(v.number()),
  maxDistance: v.nullish(v.number()),
  minRedshift: v.nullish(v.number()),
  maxRedshift: v.nullish(v.number()),
  minMstar: v.nullish(v.number()),
  maxMstar: v.nullish(v.number()),
  localizationDateobs: v.nullish(v.string()),
  localizationName: v.nullish(v.string()),
  localizationCumprob: v.optional(v.number()),
  includeGeoJSON: v.optional(v.boolean()),
  numPerPage: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  catalogNamesOnly: v.optional(v.boolean()),
  returnProbability: v.optional(v.boolean()),
  sortBy: v.nullish(v.string()),
  sortOrder: v.nullish(v.string()),
});

/** Query parameters for retrieving galaxies. */
export type GalaxyCatalogGetQuery = v.InferOutput<
  typeof GalaxyCatalogGetQuerySchema
>;

export const GalaxyCatalogPostSchema = v.strictObject({
  catalog_name: v.string(),
  catalog_data: v.record(v.string(), v.array(v.unknown())),
  catalog_description: v.nullish(v.string()),
  catalog_url: v.nullish(v.string()),
});

/** Payload for ingesting a galaxy catalog. */
export type GalaxyCatalogPost = v.InferOutput<typeof GalaxyCatalogPostSchema>;

export const GalaxyCatalogPostBodySchema = v.strictObject({
  catalog_name: v.nullish(v.string()),
  catalog_description: v.nullish(v.string()),
  catalog_url: v.nullish(v.string()),
  catalog_data: v.nullish(v.record(v.string(), v.unknown())),
});

/** Request body for ingesting a galaxy catalog. */
export type GalaxyCatalogPostBody = v.InferOutput<
  typeof GalaxyCatalogPostBodySchema
>;

export const ObjHostPostBodySchema = v.strictObject({
  galaxyName: v.nullish(v.string()),
});

/** Request body for setting an object's host galaxy. */
export type ObjHostPostBody = v.InferOutput<typeof ObjHostPostBodySchema>;
