// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import {
  AllocationResponseSchema,
  GcnEventResponseSchema,
  GroupResponseSchema,
  UserResponseSchema,
} from "./_cyclic.js";
import { SourceResponseSchema } from "./sources.js";

export const DefaultGcnTagPostSchema = v.strictObject({
  default_tag_name: v.string(),
  filters: v.nullish(v.record(v.string(), v.unknown())),
});

/** Payload for creating a default GCN tag. */
export type DefaultGcnTagPost = v.InferOutput<typeof DefaultGcnTagPostSchema>;

export const DefaultGcnTagPostBodySchema = v.strictObject({
  default_tag_name: v.nullish(v.string()),
  filters: v.nullish(v.record(v.string(), v.unknown())),
});

export type DefaultGcnTagPostBody = v.InferOutput<
  typeof DefaultGcnTagPostBodySchema
>;

export const DefaultGcnTagPostResponseSchema = v.object({
  id: v.number(),
});

export type DefaultGcnTagPostResponse = v.InferOutput<
  typeof DefaultGcnTagPostResponseSchema
>;

export const DefaultGcnTagResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  requester_id: v.nullish(v.number()),
  default_tag_name: v.nullish(v.string()),
  filters: v.nullish(v.record(v.string(), v.unknown())),
  requester: v.nullish(UserResponseSchema),
});

/**
 * A rule that automatically tags matching GCN events.
 *
 * ``filters`` is free-form JSON; the ingester reads the keys ``gcn_tags``,
 * ``notice_types`` and ``localization_tags``.
 */
export type DefaultGcnTagResponse = v.InferOutput<
  typeof DefaultGcnTagResponseSchema
>;

export const GcnAssociationRuleBodySchema = v.strictObject({
  group_id: v.number(),
  detector_type_1: v.string(),
  detector_type_2: v.string(),
  tags_1: v.optional(v.array(v.string())),
  tags_2: v.optional(v.array(v.string())),
  days: v.number(),
  min_consistency: v.optional(v.number()),
});

/** One group's cut for a pair of messengers. */
export type GcnAssociationRuleBody = v.InferOutput<
  typeof GcnAssociationRuleBodySchema
>;

export const GcnCatalogQueryResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  requester_id: v.nullish(v.number()),
  allocation_id: v.nullish(v.number()),
  payload: v.optional(v.record(v.string(), v.unknown())),
  status: v.nullish(v.string()),
  requester: v.nullish(UserResponseSchema),
  allocation: v.nullish(AllocationResponseSchema),
  target_groups: v.nullish(v.array(GroupResponseSchema)),
});

/** A catalog query submitted for a GCN event. */
export type GcnCatalogQueryResponse = v.InferOutput<
  typeof GcnCatalogQueryResponseSchema
>;

export const GcnEventAliasDeleteBodySchema = v.strictObject({
  alias: v.nullish(v.string()),
});

export type GcnEventAliasDeleteBody = v.InferOutput<
  typeof GcnEventAliasDeleteBodySchema
>;

export const GcnEventAliasPostBodySchema = v.strictObject({
  alias: v.nullish(v.string()),
});

export type GcnEventAliasPostBody = v.InferOutput<
  typeof GcnEventAliasPostBodySchema
>;

export const GcnEventAssociationsGetQuerySchema = v.strictObject({
  minConsistency: v.nullish(v.number()),
  maxDays: v.nullish(v.number()),
  includeRejected: v.optional(v.boolean()),
});

/** Query parameters for reading an event's associations. */
export type GcnEventAssociationsGetQuery = v.InferOutput<
  typeof GcnEventAssociationsGetQuerySchema
>;

export const GcnEventCrossmatchRequeueResponseSchema = v.strictObject({
  filters_requeued: v.number(),
});

/** Result of requeueing the alert crossmatch of a GCN event. */
export type GcnEventCrossmatchRequeueResponse = v.InferOutput<
  typeof GcnEventCrossmatchRequeueResponseSchema
>;

export const GcnEventExtractionIdResponseSchema = v.strictObject({
  id: v.number(),
});

/** A response carrying only the ID of the affected extraction. */
export type GcnEventExtractionIdResponse = v.InferOutput<
  typeof GcnEventExtractionIdResponseSchema
>;

export const GcnEventExtractionResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sent_by_id: v.nullish(v.number()),
  dateobs: v.nullish(v.string()),
  circular_id: v.nullish(v.number()),
  circular_created_at: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  data: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * A structured extraction attached to a GCN event.
 *
 * ``data`` is the extraction JSON as the producer sent it.
 */
export type GcnEventExtractionResponse = v.InferOutput<
  typeof GcnEventExtractionResponseSchema
>;

export const GcnEventGetQuerySchema = v.strictObject({
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  partialdateobs: v.nullish(v.string()),
  gcnTagKeep: v.nullish(v.array(v.string())),
  gcnTagRemove: v.nullish(v.array(v.string())),
  localizationTagKeep: v.nullish(v.array(v.string())),
  localizationTagRemove: v.nullish(v.array(v.string())),
  gcnPropertiesFilter: v.nullish(v.array(v.string())),
  localizationPropertiesFilter: v.nullish(v.array(v.string())),
  numPerPage: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  sortBy: v.nullish(v.string()),
  sortOrder: v.optional(v.string()),
  excludeNoticeContent: v.optional(v.boolean()),
  groupIds: v.nullish(v.string()),
  mmadetectorIds: v.nullish(v.array(v.number())),
});

/** Query parameters for retrieving GCN events. */
export type GcnEventGetQuery = v.InferOutput<typeof GcnEventGetQuerySchema>;

export const GcnEventIdResponseSchema = v.strictObject({
  id: v.number(),
});

/** A response carrying only the ID of the affected GCN event. */
export type GcnEventIdResponse = v.InferOutput<typeof GcnEventIdResponseSchema>;

export const GcnEventInstrumentFieldGetQuerySchema = v.strictObject({
  localization_name: v.nullish(v.string()),
  integrated_probability: v.optional(v.number()),
});

/** Query parameters for instrument field probabilities for a skymap. */
export type GcnEventInstrumentFieldGetQuery = v.InferOutput<
  typeof GcnEventInstrumentFieldGetQuerySchema
>;

export const GcnEventInstrumentFieldsResponseSchema = v.strictObject({
  field_ids: v.optional(v.array(v.number())),
  probabilities: v.optional(v.array(v.number())),
});

/** Instrument field probabilities for a GCN event localization. */
export type GcnEventInstrumentFieldsResponse = v.InferOutput<
  typeof GcnEventInstrumentFieldsResponseSchema
>;

export const GcnEventObjCrossmatchPostSchema = v.strictObject({
  startDate: v.string(),
  endDate: v.string(),
  probability: v.nullish(v.number()),
  beforeFirstDetection: v.nullish(v.boolean()),
  gcnTagKeep: v.nullish(v.array(v.string())),
  gcnTagRemove: v.nullish(v.array(v.string())),
  localizationTagKeep: v.nullish(v.array(v.string())),
  localizationTagRemove: v.nullish(v.array(v.string())),
  gcnPropertiesFilter: v.nullish(v.array(v.string())),
  localizationPropertiesFilter: v.nullish(v.array(v.string())),
});

/** Payload for crossmatching an object against GCN events. */
export type GcnEventObjCrossmatchPost = v.InferOutput<
  typeof GcnEventObjCrossmatchPostSchema
>;

export const GcnEventObjIdResponseSchema = v.object({
  id: v.number(),
});

/** ID of the affected gcn_event_obj row. */
export type GcnEventObjIdResponse = v.InferOutput<
  typeof GcnEventObjIdResponseSchema
>;

export const GcnEventObjPatchBodySchema = v.strictObject({
  status: v.picklist(["pending", "confirmed", "ambiguous", "rejected"]),
  explanation: v.nullish(v.string()),
  notes: v.nullish(v.string()),
});

/**
 * Request body for updating the confirmed/rejected status of a source in
 * a GCN.
 */
export type GcnEventObjPatchBody = v.InferOutput<
  typeof GcnEventObjPatchBodySchema
>;

export const GcnEventObjPostSchema = v.strictObject({
  source_id: v.string(),
  status: v.picklist(["pending", "confirmed", "ambiguous", "rejected"]),
  localization_name: v.string(),
  localization_cumprob: v.number(),
  start_date: v.string(),
  end_date: v.string(),
  explanation: v.nullish(v.string()),
  notes: v.nullish(v.string()),
});

/** Payload for recording an object's standing against a GCN event. */
export type GcnEventObjPost = v.InferOutput<typeof GcnEventObjPostSchema>;

export const GcnEventObjPostBodySchema = v.strictObject({
  source_id: v.string(),
  localization_name: v.string(),
  localization_cumprob: v.number(),
  status: v.picklist(["pending", "confirmed", "ambiguous", "rejected"]),
  start_date: v.string(),
  end_date: v.string(),
  explanation: v.nullish(v.string()),
  notes: v.nullish(v.string()),
});

/** Request body for confirming or rejecting a source in a GCN. */
export type GcnEventObjPostBody = v.InferOutput<
  typeof GcnEventObjPostBodySchema
>;

export const GcnEventObjResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  dateobs: v.nullish(v.string()),
  status: v.nullish(
    v.picklist(["pending", "confirmed", "ambiguous", "rejected"]),
  ),
  confirmer_id: v.nullish(v.number()),
  explanation: v.nullish(v.string()),
  notes: v.nullish(v.string()),
  obj: v.nullish(SourceResponseSchema),
  confirmer: v.nullish(UserResponseSchema),
  gcnevent: v.nullish(v.record(v.string(), v.unknown())),
});

/** An object's standing against a GCN event. */
export type GcnEventObjResponse = v.InferOutput<
  typeof GcnEventObjResponseSchema
>;

export const GcnEventPatchBodySchema = v.strictObject({
  summary: v.nullish(v.string()),
  summary_origin: v.nullish(v.string()),
  is_bot: v.nullish(v.boolean()),
});

export type GcnEventPatchBody = v.InferOutput<typeof GcnEventPatchBodySchema>;

export const GcnEventPostSchema = v.strictObject({
  xml: v.nullish(v.string()),
  json: v.nullish(v.record(v.string(), v.unknown())),
  dateobs: v.nullish(v.string()),
  trigger_id: v.nullish(v.string()),
  aliases: v.nullish(v.array(v.string())),
  group_ids: v.nullish(v.array(v.number())),
  properties: v.nullish(v.record(v.string(), v.unknown())),
  tags: v.nullish(v.array(v.string())),
  skymap: v.optional(v.unknown()),
});

/** Payload for ingesting a GCN event. */
export type GcnEventPost = v.InferOutput<typeof GcnEventPostSchema>;

export const GcnEventPostBodySchema = v.strictObject({
  xml: v.nullish(v.string()),
  json: v.optional(
    v.union([v.string(), v.record(v.string(), v.unknown()), v.null()]),
  ),
  dateobs: v.nullish(v.string()),
  trigger_id: v.optional(v.union([v.string(), v.number(), v.null()])),
  aliases: v.nullish(v.array(v.string())),
  group_ids: v.nullish(v.array(v.number())),
  tags: v.nullish(v.array(v.string())),
  properties: v.nullish(v.record(v.string(), v.unknown())),
  skymap: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
});

export type GcnEventPostBody = v.InferOutput<typeof GcnEventPostBodySchema>;

export const GcnEventPostResponseSchema = v.object({
  gcnevent_id: v.nullable(v.number()),
  dateobs: v.nullable(v.string()),
  notice_id: v.nullable(v.number()),
});

export type GcnEventPostResponse = v.InferOutput<
  typeof GcnEventPostResponseSchema
>;

export const GcnEventSummarizeResponseSchema = v.strictObject({
  summary: v.string(),
});

/** The machine-generated summary text of a GCN event. */
export type GcnEventSummarizeResponse = v.InferOutput<
  typeof GcnEventSummarizeResponseSchema
>;

export const GcnEventTachInfoResponseSchema = v.strictObject({
  tach_id: v.nullish(v.string()),
  aliases: v.nullish(v.array(v.string())),
  circulars: v.nullish(v.record(v.string(), v.string())),
});

/**
 * The TACH identifiers, aliases and circulars of a GCN event.
 *
 * ``circulars`` maps GCN circular ID to that circular's subject line.
 */
export type GcnEventTachInfoResponse = v.InferOutput<
  typeof GcnEventTachInfoResponseSchema
>;

export const GcnEventTagDeleteBodySchema = v.strictObject({
  tag: v.nullish(v.string()),
});

export type GcnEventTagDeleteBody = v.InferOutput<
  typeof GcnEventTagDeleteBodySchema
>;

export const GcnEventTagPostBodySchema = v.strictObject({
  dateobs: v.nullish(v.string()),
  text: v.nullish(v.string()),
});

export type GcnEventTagPostBody = v.InferOutput<
  typeof GcnEventTagPostBodySchema
>;

export const GcnEventTagPostResponseSchema = v.object({
  gcntag_id: v.number(),
});

export type GcnEventTagPostResponse = v.InferOutput<
  typeof GcnEventTagPostResponseSchema
>;

export const GcnEventTriggerPutBodySchema = v.strictObject({
  triggered: v.optional(v.union([v.boolean(), v.string(), v.null()])),
});

export type GcnEventTriggerPutBody = v.InferOutput<
  typeof GcnEventTriggerPutBodySchema
>;

export const GcnEventUserPostBodySchema = v.strictObject({
  userID: v.nullish(v.number()),
});

export type GcnEventUserPostBody = v.InferOutput<
  typeof GcnEventUserPostBodySchema
>;

export const GcnEventsPageResponseSchema = v.strictObject({
  events: v.optional(v.array(GcnEventResponseSchema)),
  totalMatches: v.optional(v.number()),
});

/** One page of results from a GCN events query. */
export type GcnEventsPageResponse = v.InferOutput<
  typeof GcnEventsPageResponseSchema
>;

export const GcnReportPatchBodySchema = v.strictObject({
  data: v.nullish(v.record(v.string(), v.unknown())),
  published: v.nullish(v.boolean()),
});

export type GcnReportPatchBody = v.InferOutput<typeof GcnReportPatchBodySchema>;

export const GcnReportPostSchema = v.strictObject({
  reportName: v.string(),
  groupId: v.number(),
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  localizationName: v.nullish(v.string()),
  localizationCumprob: v.nullish(v.number()),
  numberDetections: v.nullish(v.number()),
  showSources: v.nullish(v.boolean()),
  showObservations: v.nullish(v.boolean()),
  showSurveyEfficiencies: v.nullish(v.boolean()),
  photometryInWindow: v.nullish(v.boolean()),
  statsMethod: v.nullish(v.string()),
  instrumentIds: v.nullish(v.array(v.number())),
});

/** Payload for generating a GCN event report. */
export type GcnReportPost = v.InferOutput<typeof GcnReportPostSchema>;

export const GcnReportPostBodySchema = v.strictObject({
  reportName: v.nullish(v.string()),
  groupId: v.nullish(v.number()),
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  localizationName: v.nullish(v.string()),
  localizationCumprob: v.optional(v.number()),
  numberDetections: v.nullish(v.number()),
  showSources: v.optional(v.boolean()),
  showObservations: v.optional(v.boolean()),
  showSurveyEfficiencies: v.optional(v.boolean()),
  photometryInWindow: v.optional(v.boolean()),
  statsMethod: v.optional(v.string()),
  instrumentIds: v.nullish(v.array(v.number())),
});

export type GcnReportPostBody = v.InferOutput<typeof GcnReportPostBodySchema>;

export const GcnReportPostResponseSchema = v.object({
  id: v.number(),
});

/** ID of the created GCN report. */
export type GcnReportPostResponse = v.InferOutput<
  typeof GcnReportPostResponseSchema
>;

export const GcnSummaryPatchBodySchema = v.strictObject({
  body: v.nullish(v.string()),
});

export type GcnSummaryPatchBody = v.InferOutput<
  typeof GcnSummaryPatchBodySchema
>;

export const GcnSummaryPostSchema = v.strictObject({
  title: v.string(),
  groupId: v.number(),
  number: v.nullish(v.number()),
  subject: v.nullish(v.string()),
  userIds: v.nullish(v.array(v.number())),
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  localizationName: v.nullish(v.string()),
  localizationCumprob: v.nullish(v.number()),
  numberDetections: v.nullish(v.number()),
  numberObservations: v.nullish(v.number()),
  showSources: v.nullish(v.boolean()),
  showGalaxies: v.nullish(v.boolean()),
  showObservations: v.nullish(v.boolean()),
  noText: v.nullish(v.boolean()),
  photometryInWindow: v.nullish(v.boolean()),
  statsMethod: v.nullish(v.string()),
  instrumentIds: v.nullish(v.array(v.number())),
  acknowledgements: v.nullish(v.string()),
});

/** Payload for generating a GCN event summary. */
export type GcnSummaryPost = v.InferOutput<typeof GcnSummaryPostSchema>;

export const GcnSummaryPostBodySchema = v.strictObject({
  title: v.nullish(v.string()),
  number: v.optional(v.union([v.string(), v.number(), v.null()])),
  subject: v.nullish(v.string()),
  userIds: v.optional(v.union([v.array(v.number()), v.number(), v.null()])),
  groupId: v.nullish(v.number()),
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  localizationName: v.nullish(v.string()),
  localizationCumprob: v.optional(v.number()),
  numberDetections: v.nullish(v.number()),
  numberObservations: v.nullish(v.number()),
  showSources: v.optional(v.boolean()),
  showGalaxies: v.optional(v.boolean()),
  showObservations: v.optional(v.boolean()),
  noText: v.optional(v.boolean()),
  photometryInWindow: v.optional(v.boolean()),
  statsMethod: v.optional(v.string()),
  instrumentIds: v.nullish(v.array(v.number())),
  acknowledgements: v.nullish(v.string()),
});

export type GcnSummaryPostBody = v.InferOutput<typeof GcnSummaryPostBodySchema>;

export const GcnSummaryPostResponseSchema = v.object({
  id: v.number(),
});

export type GcnSummaryPostResponse = v.InferOutput<
  typeof GcnSummaryPostResponseSchema
>;

export const LocalizationCrossmatchGetQuerySchema = v.strictObject({
  id1: v.number(),
  id2: v.number(),
});

/** Query parameters for crossmatching two localizations. */
export type LocalizationCrossmatchGetQuery = v.InferOutput<
  typeof LocalizationCrossmatchGetQuerySchema
>;

export const LocalizationGetQuerySchema = v.strictObject({
  include2DMap: v.optional(v.boolean()),
});

/** Query parameters for retrieving a GCN localization. */
export type LocalizationGetQuery = v.InferOutput<
  typeof LocalizationGetQuerySchema
>;

export const ObjGcnEventPostBodySchema = v.strictObject({
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  probability: v.nullish(v.number()),
  beforeFirstDetection: v.optional(v.boolean()),
  gcnTagKeep: v.optional(v.union([v.array(v.string()), v.string(), v.null()])),
  gcnTagRemove: v.optional(
    v.union([v.array(v.string()), v.string(), v.null()]),
  ),
  localizationTagKeep: v.optional(
    v.union([v.array(v.string()), v.string(), v.null()]),
  ),
  localizationTagRemove: v.optional(
    v.union([v.array(v.string()), v.string(), v.null()]),
  ),
  gcnPropertiesFilter: v.optional(
    v.union([v.array(v.string()), v.string(), v.null()]),
  ),
  localizationPropertiesFilter: v.optional(
    v.union([v.array(v.string()), v.string(), v.null()]),
  ),
});

export type ObjGcnEventPostBody = v.InferOutput<
  typeof ObjGcnEventPostBodySchema
>;

export const RecentGcnExtractionSummaryResponseSchema = v.strictObject({
  event_name: v.nullish(v.string()),
  subject: v.nullish(v.string()),
  n_photometry: v.optional(v.number()),
  n_detections: v.optional(v.number()),
  bandpasses: v.optional(v.array(v.string())),
  redshift: v.nullish(v.number()),
  classification: v.nullish(v.string()),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  n_references: v.optional(v.number()),
});

/**
 * A digest of one extraction's JSON, as derived by the recent-extractions
 * handler (unrelated to ``GcnEvent.summary``).
 *
 * ``event_name``, ``redshift``, ``classification``, ``ra`` and ``dec`` are
 * read straight out of producer-controlled JSON without coercion.
 */
export type RecentGcnExtractionSummaryResponse = v.InferOutput<
  typeof RecentGcnExtractionSummaryResponseSchema
>;

export const RecentGcnExtractionResponseSchema = v.strictObject({
  id: v.number(),
  origin: v.nullish(v.string()),
  circular_id: v.nullish(v.number()),
  created_at: v.nullish(v.string()),
  circular_created_at: v.nullish(v.string()),
  dateobs: v.nullish(v.string()),
  event_aliases: v.optional(v.array(v.string())),
  summary: RecentGcnExtractionSummaryResponseSchema,
});

/** An extraction as listed by ``/api/internal/recent_gcn_extractions``. */
export type RecentGcnExtractionResponse = v.InferOutput<
  typeof RecentGcnExtractionResponseSchema
>;

export const SourcesConfirmedInGCNGetQuerySchema = v.strictObject({
  sourcesIDList: v.optional(v.string()),
});

/** Query parameters for retrieving sources confirmed/rejected in a GCN. */
export type SourcesConfirmedInGCNGetQuery = v.InferOutput<
  typeof SourcesConfirmedInGCNGetQuerySchema
>;
