// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { GroupResponseSchema } from "./_cyclic.js";

export const GroupGetQuerySchema = v.strictObject({
  name: v.nullish(v.string()),
  includeGroupUsers: v.optional(v.boolean()),
  includeSingleUserGroups: v.optional(v.boolean()),
});

/** Query parameters for retrieving groups. */
export type GroupGetQuery = v.InferOutput<typeof GroupGetQuerySchema>;

export const GroupPostSchema = v.strictObject({
  name: v.string(),
  nickname: v.nullish(v.string()),
  description: v.nullish(v.string()),
  auto_accept_requests: v.nullish(v.boolean()),
  group_admins: v.nullish(v.array(v.number())),
});

/** Payload for creating a group. */
export type GroupPost = v.InferOutput<typeof GroupPostSchema>;

export const GroupPostBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  nickname: v.nullish(v.string()),
  description: v.nullish(v.string()),
  auto_accept_requests: v.nullish(v.boolean()),
  group_admins: v.nullish(v.array(v.number())),
});

/** Request body for creating a group. */
export type GroupPostBody = v.InferOutput<typeof GroupPostBodySchema>;

export const GroupPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating a group. */
export type GroupPostResponse = v.InferOutput<typeof GroupPostResponseSchema>;

export const GroupPutBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  nickname: v.nullish(v.string()),
  description: v.nullish(v.string()),
  private: v.nullish(v.boolean()),
  auto_accept_requests: v.nullish(v.boolean()),
  discoverable_data: v.nullish(v.boolean()),
});

/** Request body for updating a group. */
export type GroupPutBody = v.InferOutput<typeof GroupPutBodySchema>;

export const GroupStreamPostBodySchema = v.strictObject({
  stream_id: v.nullish(v.number()),
});

/** Request body for adding an alert stream to a group. */
export type GroupStreamPostBody = v.InferOutput<
  typeof GroupStreamPostBodySchema
>;

export const GroupStreamPostResponseSchema = v.object({
  group_id: v.number(),
  stream_id: v.number(),
});

/** Data payload returned when adding a stream to a group. */
export type GroupStreamPostResponse = v.InferOutput<
  typeof GroupStreamPostResponseSchema
>;

export const GroupUserPatchBodySchema = v.strictObject({
  userID: v.nullish(v.number()),
  admin: v.nullish(v.boolean()),
  canSave: v.nullish(v.boolean()),
  canSharePhotometry: v.nullish(v.boolean()),
});

/** Request body for updating a group user. */
export type GroupUserPatchBody = v.InferOutput<typeof GroupUserPatchBodySchema>;

export const GroupUserPostBodySchema = v.strictObject({
  userID: v.nullish(v.number()),
  admin: v.optional(v.boolean()),
  canSave: v.optional(v.boolean()),
  canSharePhotometry: v.optional(v.boolean()),
});

/** Request body for adding a user to a group. */
export type GroupUserPostBody = v.InferOutput<typeof GroupUserPostBodySchema>;

export const GroupUserPostResponseSchema = v.object({
  group_id: v.number(),
  user_id: v.number(),
  admin: v.boolean(),
});

/** Data payload returned when adding a user to a group. */
export type GroupUserPostResponse = v.InferOutput<
  typeof GroupUserPostResponseSchema
>;

export const GroupUsersFromGroupsPostBodySchema = v.strictObject({
  fromGroupIDs: v.nullish(v.array(v.number())),
});

/** Request body for adding users from other group(s). */
export type GroupUsersFromGroupsPostBody = v.InferOutput<
  typeof GroupUsersFromGroupsPostBodySchema
>;

export const GroupsResponseSchema = v.strictObject({
  user_groups: v.optional(v.array(GroupResponseSchema)),
  user_accessible_groups: v.optional(v.array(GroupResponseSchema)),
  all_groups: v.nullish(v.array(GroupResponseSchema)),
});

/** The groups visible to the token, split by relationship to the user. */
export type GroupsResponse = v.InferOutput<typeof GroupsResponseSchema>;
