// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { GroupResponseSchema, UserResponseSchema } from "./_cyclic.js";

export const GroupAdmissionRequestGetQuerySchema = v.strictObject({
  groupID: v.nullish(v.number()),
});

/** Query parameters for listing group admission requests. */
export type GroupAdmissionRequestGetQuery = v.InferOutput<
  typeof GroupAdmissionRequestGetQuerySchema
>;

export const GroupAdmissionRequestPatchBodySchema = v.strictObject({
  status: v.picklist(["pending", "accepted", "declined"]),
});

/** Request body for updating a group admission request's status. */
export type GroupAdmissionRequestPatchBody = v.InferOutput<
  typeof GroupAdmissionRequestPatchBodySchema
>;

export const GroupAdmissionRequestPostBodySchema = v.strictObject({
  groupID: v.number(),
  userID: v.number(),
});

/** Request body for creating a group admission request. */
export type GroupAdmissionRequestPostBody = v.InferOutput<
  typeof GroupAdmissionRequestPostBodySchema
>;

export const GroupAdmissionRequestPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating a group admission request. */
export type GroupAdmissionRequestPostResponse = v.InferOutput<
  typeof GroupAdmissionRequestPostResponseSchema
>;

export const GroupAdmissionRequestResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  user_id: v.nullish(v.number()),
  group_id: v.nullish(v.number()),
  status: v.nullish(v.picklist(["pending", "accepted", "declined"])),
  user: v.nullish(UserResponseSchema),
  group: v.nullish(GroupResponseSchema),
});

/** A request to join a group. */
export type GroupAdmissionRequestResponse = v.InferOutput<
  typeof GroupAdmissionRequestResponseSchema
>;
