// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const HealpixCountsResponseSchema = v.strictObject({
  totalWithoutHealpix: v.optional(v.number()),
  totalWithHealpix: v.optional(v.number()),
});

/** Counts of objects with and without a HEALPix index. */
export type HealpixCountsResponse = v.InferOutput<
  typeof HealpixCountsResponseSchema
>;

export const HealpixUpdatePostQuerySchema = v.strictObject({
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/** Query parameters for the healpix backfill. */
export type HealpixUpdatePostQuery = v.InferOutput<
  typeof HealpixUpdatePostQuerySchema
>;

export const HealpixUpdateResponseSchema = v.strictObject({
  totalMatches: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/**
 * Result of a HEALPix backfill batch.
 *
 * ``total_matches`` counts the objects still missing a HEALPix index before
 * the batch ran.
 */
export type HealpixUpdateResponse = v.InferOutput<
  typeof HealpixUpdateResponseSchema
>;
