// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { InstrumentResponseSchema } from "./_cyclic.js";

export const InstrumentGetQuerySchema = v.strictObject({
  includeGeoJSON: v.optional(v.boolean()),
  includeGeoJSONSummary: v.optional(v.boolean()),
  includeRegion: v.optional(v.boolean()),
  ignoreCache: v.optional(v.boolean()),
  localizationDateobs: v.nullish(v.string()),
  localizationName: v.nullish(v.string()),
  localizationCumprob: v.optional(v.number()),
  airmassTime: v.nullish(v.string()),
  name: v.nullish(v.string()),
});

/** Query parameters for retrieving one or all instruments. */
export type InstrumentGetQuery = v.InferOutput<typeof InstrumentGetQuerySchema>;

export const InstrumentLogExternalAPIGetQuerySchema = v.strictObject({
  startDate: v.string(),
  endDate: v.string(),
});

/** Query parameters for retrieving instrument logs from an external API. */
export type InstrumentLogExternalAPIGetQuery = v.InferOutput<
  typeof InstrumentLogExternalAPIGetQuerySchema
>;

export const InstrumentLogGetQuerySchema = v.strictObject({
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
});

/** Query parameters for retrieving instrument logs. */
export type InstrumentLogGetQuery = v.InferOutput<
  typeof InstrumentLogGetQuerySchema
>;

export const InstrumentLogPostBodySchema = v.strictObject({
  start_date: v.string(),
  end_date: v.string(),
  log: v.union([v.string(), v.record(v.string(), v.unknown())]),
});

/** Request body for posting instrument logs. */
export type InstrumentLogPostBody = v.InferOutput<
  typeof InstrumentLogPostBodySchema
>;

export const InstrumentLogPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when posting instrument logs. */
export type InstrumentLogPostResponse = v.InferOutput<
  typeof InstrumentLogPostResponseSchema
>;

export const InstrumentLogResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  instrument_id: v.nullish(v.number()),
  instrument: v.nullish(InstrumentResponseSchema),
  start_date: v.nullish(v.string()),
  end_date: v.nullish(v.string()),
  log: v.nullish(v.record(v.string(), v.unknown())),
});

/** A log uploaded for an instrument. */
export type InstrumentLogResponse = v.InferOutput<
  typeof InstrumentLogResponseSchema
>;

export const InstrumentPostSchema = v.strictObject({
  name: v.string(),
  type: v.string(),
  telescope_id: v.number(),
  band: v.nullish(v.string()),
  filters: v.optional(v.array(v.string())),
  sensitivity_data: v.nullish(v.record(v.string(), v.unknown())),
  configuration_data: v.nullish(v.record(v.string(), v.unknown())),
  api_classname: v.nullish(v.string()),
  api_classname_obsplan: v.nullish(v.string()),
  listener_classname: v.nullish(v.string()),
  treasuremap_id: v.nullish(v.number()),
  tns_id: v.nullish(v.number()),
  across_id: v.nullish(v.string()),
  region: v.nullish(v.string()),
  field_data: v.optional(
    v.union([v.record(v.string(), v.array(v.unknown())), v.string(), v.null()]),
  ),
  field_region: v.nullish(v.string()),
  field_fov_type: v.nullish(v.string()),
  field_fov_attributes: v.optional(
    v.union([v.array(v.number()), v.number(), v.null()]),
  ),
  references: v.optional(
    v.union([v.record(v.string(), v.array(v.unknown())), v.string(), v.null()]),
  ),
});

/** Payload for creating an instrument. */
export type InstrumentPost = v.InferOutput<typeof InstrumentPostSchema>;

export const InstrumentPostBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  acknowledgment: v.nullish(v.string()),
  type: v.nullish(v.string()),
  band: v.nullish(v.string()),
  telescope_id: v.nullish(v.number()),
  filters: v.nullish(v.array(v.unknown())),
  sensitivity_data: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  configuration_data: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  field_data: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  field_region: v.nullish(v.string()),
  references: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  field_fov_type: v.nullish(v.string()),
  field_fov_attributes: v.optional(
    v.union([v.array(v.unknown()), v.number(), v.string(), v.null()]),
  ),
  api_classname: v.nullish(v.string()),
  api_classname_obsplan: v.nullish(v.string()),
  listener_classname: v.nullish(v.string()),
  treasuremap_id: v.nullish(v.number()),
  tns_id: v.nullish(v.number()),
  across_id: v.nullish(v.string()),
  region: v.nullish(v.string()),
  status: v.nullish(v.record(v.string(), v.unknown())),
  last_status_update: v.nullish(v.string()),
  has_fields: v.nullish(v.boolean()),
  has_region: v.nullish(v.boolean()),
});

/**
 * Request body for creating an instrument.
 *
 * Pass-through blob fields (sensitivity/configuration/field/reference data)
 * are typed permissively; the handler and marshmallow schema enforce the
 * real validation rules.
 */
export type InstrumentPostBody = v.InferOutput<typeof InstrumentPostBodySchema>;

export const InstrumentPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating an instrument. */
export type InstrumentPostResponse = v.InferOutput<
  typeof InstrumentPostResponseSchema
>;

export const InstrumentPutSchema = v.strictObject({
  name: v.nullish(v.string()),
  type: v.nullish(v.string()),
  telescope_id: v.nullish(v.number()),
  band: v.nullish(v.string()),
  filters: v.nullish(v.array(v.string())),
  sensitivity_data: v.nullish(v.record(v.string(), v.unknown())),
  configuration_data: v.nullish(v.record(v.string(), v.unknown())),
  api_classname: v.nullish(v.string()),
  api_classname_obsplan: v.nullish(v.string()),
  listener_classname: v.nullish(v.string()),
  treasuremap_id: v.nullish(v.number()),
  tns_id: v.nullish(v.number()),
  across_id: v.nullish(v.string()),
  region: v.nullish(v.string()),
  field_data: v.optional(
    v.union([v.record(v.string(), v.array(v.unknown())), v.string(), v.null()]),
  ),
  field_region: v.nullish(v.string()),
  field_fov_type: v.nullish(v.string()),
  field_fov_attributes: v.optional(
    v.union([v.array(v.number()), v.number(), v.null()]),
  ),
  references: v.optional(
    v.union([v.record(v.string(), v.array(v.unknown())), v.string(), v.null()]),
  ),
});

/** Payload for updating an instrument. */
export type InstrumentPut = v.InferOutput<typeof InstrumentPutSchema>;

export const InstrumentPutBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  acknowledgment: v.nullish(v.string()),
  type: v.nullish(v.string()),
  band: v.nullish(v.string()),
  telescope_id: v.nullish(v.number()),
  filters: v.nullish(v.array(v.unknown())),
  sensitivity_data: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  configuration_data: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  field_data: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  field_region: v.nullish(v.string()),
  references: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  field_fov_type: v.nullish(v.string()),
  field_fov_attributes: v.optional(
    v.union([v.array(v.unknown()), v.number(), v.string(), v.null()]),
  ),
  api_classname: v.nullish(v.string()),
  api_classname_obsplan: v.nullish(v.string()),
  listener_classname: v.nullish(v.string()),
  treasuremap_id: v.nullish(v.number()),
  tns_id: v.nullish(v.number()),
  across_id: v.nullish(v.string()),
  region: v.nullish(v.string()),
  status: v.nullish(v.record(v.string(), v.unknown())),
  last_status_update: v.nullish(v.string()),
  has_fields: v.nullish(v.boolean()),
  has_region: v.nullish(v.boolean()),
});

/** Request body for updating an instrument (same shape as the post body). */
export type InstrumentPutBody = v.InferOutput<typeof InstrumentPutBodySchema>;

export const InstrumentStatusPutBodySchema = v.strictObject({
  status: v.optional(
    v.union([v.string(), v.record(v.string(), v.unknown()), v.null()]),
  ),
});

/** Request body for updating an instrument's status. */
export type InstrumentStatusPutBody = v.InferOutput<
  typeof InstrumentStatusPutBodySchema
>;
