// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { GroupResponseSchema, UserResponseSchema } from "./_cyclic.js";
import { RoleResponseSchema } from "./roles.js";
import { StreamResponseSchema } from "./streams.js";

export const InvitationGetQuerySchema = v.strictObject({
  includeUsed: v.optional(v.boolean()),
  numPerPage: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  email: v.nullish(v.string()),
  group: v.nullish(v.string()),
  stream: v.nullish(v.string()),
  invitedBy: v.nullish(v.string()),
});

/** Query parameters for listing invitations. */
export type InvitationGetQuery = v.InferOutput<typeof InvitationGetQuerySchema>;

export const InvitationPatchBodySchema = v.strictObject({
  groupIDs: v.nullish(v.array(v.number())),
  streamIDs: v.nullish(v.array(v.number())),
  role: v.nullish(v.string()),
  userExpirationDate: v.nullish(v.string()),
});

/** Request body for updating a pending invitation. */
export type InvitationPatchBody = v.InferOutput<
  typeof InvitationPatchBodySchema
>;

export const InvitationPostSchema = v.strictObject({
  userEmail: v.string(),
  groupIDs: v.array(v.number()),
  role: v.nullish(v.string()),
  streamIDs: v.nullish(v.array(v.number())),
  groupAdmin: v.nullish(v.array(v.boolean())),
  canSave: v.nullish(v.array(v.boolean())),
  canSharePhotometry: v.nullish(v.array(v.boolean())),
  userExpirationDate: v.nullish(v.string()),
});

/** Payload for inviting a new user. */
export type InvitationPost = v.InferOutput<typeof InvitationPostSchema>;

export const InvitationPostBodySchema = v.strictObject({
  userEmail: v.string(),
  groupIDs: v.array(v.number()),
  role: v.optional(v.string()),
  streamIDs: v.nullish(v.array(v.number())),
  groupAdmin: v.nullish(v.array(v.boolean())),
  canSave: v.nullish(v.array(v.boolean())),
  canSharePhotometry: v.nullish(v.array(v.boolean())),
  userExpirationDate: v.nullish(v.string()),
});

/** Request body for inviting a new user. */
export type InvitationPostBody = v.InferOutput<typeof InvitationPostBodySchema>;

export const InvitationPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating an invitation. */
export type InvitationPostResponse = v.InferOutput<
  typeof InvitationPostResponseSchema
>;

export const InvitationResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  token: v.nullish(v.string()),
  user_email: v.nullish(v.string()),
  role_id: v.nullish(v.string()),
  role: v.nullish(RoleResponseSchema),
  admin_for_groups: v.nullish(v.array(v.boolean())),
  can_save_to_groups: v.nullish(v.array(v.boolean())),
  can_share_photometry_for_groups: v.nullish(v.array(v.boolean())),
  used: v.nullish(v.boolean()),
  user_expiration_date: v.nullish(v.string()),
  groups: v.nullish(v.array(GroupResponseSchema)),
  streams: v.nullish(v.array(StreamResponseSchema)),
  invited_by: v.nullish(UserResponseSchema),
});

/** An invitation for a new user to join the instance. */
export type InvitationResponse = v.InferOutput<typeof InvitationResponseSchema>;

export const InvitationsPageResponseSchema = v.strictObject({
  invitations: v.optional(v.array(InvitationResponseSchema)),
  totalMatches: v.optional(v.number()),
});

/** One page of results from an invitations query. */
export type InvitationsPageResponse = v.InferOutput<
  typeof InvitationsPageResponseSchema
>;
