// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const ListingDeleteBodySchema = v.strictObject({
  user_id: v.nullish(v.number()),
  obj_id: v.nullish(v.string()),
  list_name: v.nullish(v.string()),
});

/**
 * Request body for removing a listing by obj_id and list_name (used when no
 * listing_id path parameter is supplied).
 */
export type ListingDeleteBody = v.InferOutput<typeof ListingDeleteBodySchema>;

export const ListingPatchBodySchema = v.strictObject({
  user_id: v.nullish(v.number()),
  obj_id: v.nullish(v.string()),
  list_name: v.nullish(v.string()),
});

/** Request body for updating a listing. */
export type ListingPatchBody = v.InferOutput<typeof ListingPatchBodySchema>;

export const ListingPostSchema = v.strictObject({
  obj_id: v.string(),
  list_name: v.string(),
  user_id: v.nullish(v.number()),
  params: v.nullish(v.record(v.string(), v.unknown())),
});

/** Payload for adding an object to a user's list. */
export type ListingPost = v.InferOutput<typeof ListingPostSchema>;

export const ListingPostBodySchema = v.strictObject({
  obj_id: v.string(),
  list_name: v.string(),
  user_id: v.nullish(v.number()),
  params: v.nullish(v.record(v.string(), v.unknown())),
});

/** Request body for adding a listing. */
export type ListingPostBody = v.InferOutput<typeof ListingPostBodySchema>;

export const ListingPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when adding a listing. */
export type ListingPostResponse = v.InferOutput<
  typeof ListingPostResponseSchema
>;

export const ListingResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  user_id: v.nullish(v.number()),
  obj_id: v.nullish(v.string()),
  list_name: v.nullish(v.string()),
  params: v.nullish(v.record(v.string(), v.unknown())),
});

/** An object saved by a user to a named list (``Listing``). */
export type ListingResponse = v.InferOutput<typeof ListingResponseSchema>;

export const UserObjListGetQuerySchema = v.strictObject({
  listName: v.nullish(v.string()),
});

/** Query parameters for retrieving sources from a user's lists. */
export type UserObjListGetQuery = v.InferOutput<
  typeof UserObjListGetQuerySchema
>;
