// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const MMADetectorGetQuerySchema = v.strictObject({
  name: v.nullish(v.string()),
});

/** Query parameters for listing MMA Detectors. */
export type MMADetectorGetQuery = v.InferOutput<
  typeof MMADetectorGetQuerySchema
>;

export const MMADetectorPatchBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  nickname: v.nullish(v.string()),
  aliases: v.nullish(v.array(v.string())),
  type: v.nullish(v.string()),
  lat: v.nullish(v.number()),
  lon: v.nullish(v.number()),
  elevation: v.nullish(v.number()),
  fixed_location: v.nullish(v.boolean()),
});

/** Request body for updating an MMADetector. */
export type MMADetectorPatchBody = v.InferOutput<
  typeof MMADetectorPatchBodySchema
>;

export const MMADetectorPostSchema = v.strictObject({
  name: v.string(),
  nickname: v.string(),
  type: v.string(),
  fixed_location: v.boolean(),
  lat: v.nullish(v.number()),
  lon: v.nullish(v.number()),
  elevation: v.nullish(v.number()),
});

/** Payload for creating an MMA detector. */
export type MMADetectorPost = v.InferOutput<typeof MMADetectorPostSchema>;

export const MMADetectorPostBodySchema = v.strictObject({
  name: v.string(),
  nickname: v.string(),
  aliases: v.nullish(v.array(v.string())),
  type: v.string(),
  lat: v.nullish(v.number()),
  lon: v.nullish(v.number()),
  elevation: v.nullish(v.number()),
  fixed_location: v.nullish(v.boolean()),
});

/** Request body for creating an MMADetector. */
export type MMADetectorPostBody = v.InferOutput<
  typeof MMADetectorPostBodySchema
>;

export const MMADetectorPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating an MMADetector. */
export type MMADetectorPostResponse = v.InferOutput<
  typeof MMADetectorPostResponseSchema
>;

/**
 * A multimessenger astronomical detector.
 *
 * ``events`` stays untyped: the GCN event model points back at
 * ``MMADetector``, so typing it would create an import cycle.
 */
export type MMADetectorResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  name?: string | null | undefined;
  nickname?: string | null | undefined;
  aliases?: string[] | null | undefined;
  type?:
    | "gravitational-wave"
    | "neutrino"
    | "gamma-ray-burst"
    | "x-ray"
    | null
    | undefined;
  lat?: number | null | undefined;
  lon?: number | null | undefined;
  elevation?: number | null | undefined;
  fixed_location?: boolean | null | undefined;
  events?: Record<string, unknown>[] | null | undefined;
  spectra?: MMADetectorSpectrumResponse[] | null | undefined;
  time_intervals?: MMADetectorTimeIntervalResponse[] | null | undefined;
};

export const MMADetectorResponseSchema: v.GenericSchema<MMADetectorResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    name: v.nullish(v.string()),
    nickname: v.nullish(v.string()),
    aliases: v.nullish(v.array(v.string())),
    type: v.nullish(
      v.picklist([
        "gravitational-wave",
        "neutrino",
        "gamma-ray-burst",
        "x-ray",
      ]),
    ),
    lat: v.nullish(v.number()),
    lon: v.nullish(v.number()),
    elevation: v.nullish(v.number()),
    fixed_location: v.nullish(v.boolean()),
    events: v.nullish(v.array(v.record(v.string(), v.unknown()))),
    spectra: v.nullish(
      v.array(v.lazy(() => MMADetectorSpectrumResponseSchema)),
    ),
    time_intervals: v.nullish(
      v.array(v.lazy(() => MMADetectorTimeIntervalResponseSchema)),
    ),
  });

/**
 * A sensitivity spectrum of a detector.
 *
 * ``owner`` and ``groups`` stay untyped: the user and group models both own
 * an ``mmadetector_spectra`` relationship, so typing them here would risk an
 * import cycle.
 */
export type MMADetectorSpectrumResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  detector_id?: number | null | undefined;
  detector?: MMADetectorResponse | null | undefined;
  frequencies?: number[] | undefined;
  amplitudes?: number[] | undefined;
  start_time?: string | null | undefined;
  end_time?: string | null | undefined;
  owner_id?: number | null | undefined;
  owner?: Record<string, unknown> | null | undefined;
  groups?: Record<string, unknown>[] | null | undefined;
  original_file_string?: string | null | undefined;
  original_file_filename?: string | null | undefined;
};

export const MMADetectorSpectrumResponseSchema: v.GenericSchema<MMADetectorSpectrumResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    detector_id: v.nullish(v.number()),
    detector: v.nullish(v.lazy(() => MMADetectorResponseSchema)),
    frequencies: v.optional(v.array(v.number())),
    amplitudes: v.optional(v.array(v.number())),
    start_time: v.nullish(v.string()),
    end_time: v.nullish(v.string()),
    owner_id: v.nullish(v.number()),
    owner: v.nullish(v.record(v.string(), v.unknown())),
    groups: v.nullish(v.array(v.record(v.string(), v.unknown()))),
    original_file_string: v.nullish(v.string()),
    original_file_filename: v.nullish(v.string()),
  });

/**
 * A detector data-taking interval.
 *
 * The time-interval endpoints build this payload by hand, so it carries only
 * these five keys rather than the model's full column set. ``owner`` and
 * ``groups`` stay untyped: the user and group models both own an
 * ``mmadetector_time_intervals`` relationship, so typing them here would
 * risk an import cycle.
 */
export type MMADetectorTimeIntervalResponse = {
  id: number;
  time_interval?: string[] | undefined;
  owner?: Record<string, unknown> | null | undefined;
  groups?: Record<string, unknown>[] | null | undefined;
  detector?: MMADetectorResponse | null | undefined;
};

export const MMADetectorTimeIntervalResponseSchema: v.GenericSchema<MMADetectorTimeIntervalResponse> =
  v.strictObject({
    id: v.number(),
    time_interval: v.optional(v.array(v.string())),
    owner: v.nullish(v.record(v.string(), v.unknown())),
    groups: v.nullish(v.array(v.record(v.string(), v.unknown()))),
    detector: v.nullish(v.lazy(() => MMADetectorResponseSchema)),
  });

export const MMADetectorSpectrumGetQuerySchema = v.strictObject({
  observedBefore: v.nullish(v.string()),
  observedAfter: v.nullish(v.string()),
  detectorIDs: v.nullish(v.array(v.number())),
  groupIDs: v.nullish(v.array(v.number())),
});

/** Query parameters for listing MMA Detector spectra. */
export type MMADetectorSpectrumGetQuery = v.InferOutput<
  typeof MMADetectorSpectrumGetQuerySchema
>;

export const MMADetectorSpectrumPatchBodySchema = v.strictObject({
  frequencies: v.nullish(v.array(v.number())),
  amplitudes: v.nullish(v.array(v.number())),
  start_time: v.nullish(v.string()),
  end_time: v.nullish(v.string()),
  detector_id: v.nullish(v.number()),
  group_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
});

/** Request body for updating an MMADetector spectrum. */
export type MMADetectorSpectrumPatchBody = v.InferOutput<
  typeof MMADetectorSpectrumPatchBodySchema
>;

export const MMADetectorSpectrumPostSchema = v.strictObject({
  frequencies: v.array(v.number()),
  amplitudes: v.array(v.number()),
  start_time: v.string(),
  end_time: v.string(),
  detector_id: v.number(),
  group_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
});

/** Payload for uploading an MMA detector spectrum. */
export type MMADetectorSpectrumPost = v.InferOutput<
  typeof MMADetectorSpectrumPostSchema
>;

export const MMADetectorSpectrumPostBodySchema = v.strictObject({
  frequencies: v.array(v.number()),
  amplitudes: v.array(v.number()),
  start_time: v.string(),
  end_time: v.string(),
  detector_id: v.number(),
  group_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
});

/** Request body for uploading an MMADetector spectrum. */
export type MMADetectorSpectrumPostBody = v.InferOutput<
  typeof MMADetectorSpectrumPostBodySchema
>;

export const MMADetectorSpectrumPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when uploading an MMADetector spectrum. */
export type MMADetectorSpectrumPostResponse = v.InferOutput<
  typeof MMADetectorSpectrumPostResponseSchema
>;

export const MMADetectorTimeIntervalGetQuerySchema = v.strictObject({
  observedBefore: v.nullish(v.string()),
  observedAfter: v.nullish(v.string()),
  detectorIDs: v.nullish(v.array(v.number())),
  groupIDs: v.nullish(v.array(v.number())),
});

/** Query parameters for listing MMA Detector time intervals. */
export type MMADetectorTimeIntervalGetQuery = v.InferOutput<
  typeof MMADetectorTimeIntervalGetQuerySchema
>;

export const MMADetectorTimeIntervalPatchBodySchema = v.strictObject({
  detector_id: v.nullish(v.number()),
  time_interval: v.nullish(v.array(v.unknown())),
  group_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
});

/** Request body for updating an MMADetector time interval. */
export type MMADetectorTimeIntervalPatchBody = v.InferOutput<
  typeof MMADetectorTimeIntervalPatchBodySchema
>;

export const MMADetectorTimeIntervalPostBodySchema = v.strictObject({
  detector_id: v.nullish(v.number()),
  time_interval: v.nullish(v.array(v.unknown())),
  time_intervals: v.nullish(v.array(v.unknown())),
  group_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
});

/** Request body for uploading MMADetector time interval(s). */
export type MMADetectorTimeIntervalPostBody = v.InferOutput<
  typeof MMADetectorTimeIntervalPostBodySchema
>;

export const MMADetectorTimeIntervalPostResponseSchema = v.object({
  ids: v.array(v.number()),
});

/** Data payload returned when uploading MMADetector time interval(s). */
export type MMADetectorTimeIntervalPostResponse = v.InferOutput<
  typeof MMADetectorTimeIntervalPostResponseSchema
>;

export const MMADetectorTimeIntervalsPostResponseSchema = v.strictObject({
  ids: v.optional(v.array(v.number())),
});

/** Result of uploading MMA detector time intervals. */
export type MMADetectorTimeIntervalsPostResponse = v.InferOutput<
  typeof MMADetectorTimeIntervalsPostResponseSchema
>;
