// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const MovingObjectFollowupPostSchema = v.strictObject({
  instrument_id: v.number(),
  exposure_count: v.number(),
  exposure_time: v.number(),
  start_time: v.string(),
  end_time: v.string(),
  filter: v.string(),
  primary_only: v.nullish(v.boolean()),
  airmass_limit: v.nullish(v.number()),
  moon_distance_limit: v.nullish(v.number()),
  sun_altitude_limit: v.nullish(v.number()),
  references_only: v.nullish(v.boolean()),
});

/** Payload for scheduling follow-up of a moving object. */
export type MovingObjectFollowupPost = v.InferOutput<
  typeof MovingObjectFollowupPostSchema
>;

export const MovingObjectFollowupPostBodySchema = v.strictObject({
  instrument_id: v.nullish(v.number()),
  exposure_count: v.nullish(v.number()),
  exposure_time: v.nullish(v.number()),
  start_time: v.nullish(v.string()),
  end_time: v.nullish(v.string()),
  filter: v.nullish(v.string()),
  primary_only: v.optional(v.boolean()),
  airmass_limit: v.optional(v.number()),
  moon_distance_limit: v.optional(v.number()),
  sun_altitude_limit: v.optional(v.number()),
  references_only: v.optional(v.boolean()),
});

/** Request body for a moving object follow-up observation plan. */
export type MovingObjectFollowupPostBody = v.InferOutput<
  typeof MovingObjectFollowupPostBodySchema
>;

export const MovingObjectObservationResponseSchema = v.strictObject({
  start_time: v.nullish(v.string()),
  end_time: v.nullish(v.string()),
  band: v.nullish(v.string()),
  field_id: v.nullish(v.number()),
  airmass: v.nullish(v.number()),
  sun_altitude: v.nullish(v.number()),
  moon_distance: v.nullish(v.number()),
});

/**
 * A scheduled exposure from ``find_observable_sequence``.
 *
 * This is not a database model: the handler returns the plain dicts built
 * by ``skyportal.utils.moving_objects.find_observable_sequence``, nothing is
 * persisted, and the keys below are the complete set.
 */
export type MovingObjectObservationResponse = v.InferOutput<
  typeof MovingObjectObservationResponseSchema
>;
