// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const NewsFeedAuthorInfoResponseSchema = v.strictObject({
  id: v.nullish(v.number()),
  username: v.nullish(v.string()),
  first_name: v.nullish(v.string()),
  last_name: v.nullish(v.string()),
  gravatar_url: v.nullish(v.string()),
  is_bot: v.nullish(v.boolean()),
});

/**
 * Display information about the user behind a news feed item.
 *
 * Exactly the fields ``basic_user_display_info`` (and
 * ``Comment.construct_author_info_dict``) copies off the ``User``.
 */
export type NewsFeedAuthorInfoResponse = v.InferOutput<
  typeof NewsFeedAuthorInfoResponseSchema
>;

export const NewsFeedGetQuerySchema = v.strictObject({
  numItems: v.nullish(v.number()),
  teamID: v.nullish(v.number()),
});

/** Query parameters for the news feed. */
export type NewsFeedGetQuery = v.InferOutput<typeof NewsFeedGetQuerySchema>;

export const NewsFeedItemResponseSchema = v.strictObject({
  type: v.picklist([
    "source",
    "comment",
    "classification",
    "spectrum",
    "photometry",
  ]),
  time: v.nullish(v.string()),
  message: v.nullish(v.string()),
  source_id: v.nullish(v.string()),
  classification: v.nullish(v.string()),
  author: v.nullish(v.string()),
  author_info: v.nullish(NewsFeedAuthorInfoResponseSchema),
});

/**
 * One entry in the news feed (no database model; built by the handler).
 *
 * ``author`` is only set on comment items; ``author_info`` is absent on
 * source items.
 */
export type NewsFeedItemResponse = v.InferOutput<
  typeof NewsFeedItemResponseSchema
>;
