// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const NotificationPatchBodySchema = v.strictObject({
  viewed: v.boolean(),
});

/**
 * Request body for updating a notification (or all of a user's
 * notifications).
 */
export type NotificationPatchBody = v.InferOutput<
  typeof NotificationPatchBodySchema
>;

export const NotificationTestPostBodySchema = v.strictObject({
  notification_type: v.nullish(v.string()),
  user_id: v.nullish(v.number()),
});

/** Request body for sending a test notification. */
export type NotificationTestPostBody = v.InferOutput<
  typeof NotificationTestPostBodySchema
>;
