// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const ObjAcknowledgmentGetQuerySchema = v.strictObject({
  exclude_filter_ids: v.nullish(v.array(v.number())),
  exclude_instrument_ids: v.nullish(v.array(v.number())),
  exclude_allocation_ids: v.nullish(v.array(v.number())),
});

/** Which detected components to include in the assembled text. */
export type ObjAcknowledgmentGetQuery = v.InferOutput<
  typeof ObjAcknowledgmentGetQuerySchema
>;

export const ObjBodySchema = v.strictObject({
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_dis: v.nullish(v.number()),
  dec_dis: v.nullish(v.number()),
  ra_err: v.nullish(v.number()),
  dec_err: v.nullish(v.number()),
  offset: v.nullish(v.number()),
  t0: v.nullish(v.number()),
  redshift: v.nullish(v.number()),
  redshift_error: v.nullish(v.number()),
  redshift_origin: v.nullish(v.string()),
  redshift_history: v.optional(v.unknown()),
  host_id: v.nullish(v.number()),
  summary: v.nullish(v.string()),
  summary_history: v.optional(v.unknown()),
  altdata: v.optional(v.unknown()),
  dist_nearest_source: v.nullish(v.number()),
  mag_nearest_source: v.nullish(v.number()),
  e_mag_nearest_source: v.nullish(v.number()),
  transient: v.nullish(v.boolean()),
  varstar: v.nullish(v.boolean()),
  is_roid: v.nullish(v.boolean()),
  mpc_name: v.nullish(v.string()),
  tns_name: v.nullish(v.string()),
  tns_info: v.optional(v.unknown()),
  score: v.nullish(v.number()),
  origin: v.nullish(v.string()),
  alias: v.nullish(v.array(v.string())),
});

/**
 * Shared optional `Obj` fields accepted by the Obj marshmallow schema
 * (``Obj.__schema__()``) on source/candidate writes. Deep validation and
 * coercion are still performed by that schema; this only constrains the
 * top-level shape.
 */
export type ObjBody = v.InferOutput<typeof ObjBodySchema>;

export const ObjMPCPostBodySchema = v.strictObject({
  obscode: v.optional(v.string()),
  date: v.nullish(v.string()),
  limiting_magnitude: v.optional(v.number()),
  search_radius: v.optional(v.number()),
});

/** Request body for crossmatching an object with the Minor Planet Center. */
export type ObjMPCPostBody = v.InferOutput<typeof ObjMPCPostBodySchema>;

export const ObjPositionGetQuerySchema = v.strictObject({
  instrument_ids: v.nullish(v.array(v.number())),
  stream_ids: v.nullish(v.array(v.number())),
  stream_only: v.optional(v.boolean()),
  snr_threshold: v.optional(v.number()),
  method: v.optional(v.picklist(["snr2", "invvar"])),
});

/** Query parameters for computing an Obj's photometry-based position. */
export type ObjPositionGetQuery = v.InferOutput<
  typeof ObjPositionGetQuerySchema
>;

export const ObjPositionResponseSchema = v.strictObject({
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  gal_lon: v.nullish(v.number()),
  gal_lat: v.nullish(v.number()),
  ebv: v.nullish(v.number()),
  separation: v.nullish(v.number()),
  discovery_ra: v.nullish(v.number()),
  discovery_dec: v.nullish(v.number()),
});

/**
 * An object's photometry-derived position, with the discovery position it
 * is measured against.
 */
export type ObjPositionResponse = v.InferOutput<
  typeof ObjPositionResponseSchema
>;

export const ObjTNSGetQuerySchema = v.strictObject({
  radius: v.optional(v.number()),
});

/** Query parameters for retrieving TNS information for an object. */
export type ObjTNSGetQuery = v.InferOutput<typeof ObjTNSGetQuerySchema>;

export const SuperObjGetQuerySchema = v.strictObject({
  name: v.nullish(v.string()),
  isRoid: v.nullish(v.boolean()),
  objID: v.nullish(v.string()),
  includeEpochs: v.optional(v.boolean()),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/** Query parameters for retrieving SuperObjs. */
export type SuperObjGetQuery = v.InferOutput<typeof SuperObjGetQuerySchema>;

export const SuperObjMemberResponseSchema = v.strictObject({
  id: v.string(),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
});

/** An object linked to a super-object, with its position. */
export type SuperObjMemberResponse = v.InferOutput<
  typeof SuperObjMemberResponseSchema
>;

export const SuperObjPatchBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  is_roid: v.nullish(v.boolean()),
  obj_ids: v.nullish(v.array(v.string())),
  add_obj_ids: v.nullish(v.array(v.string())),
  remove_obj_ids: v.nullish(v.array(v.string())),
});

/** Request body for updating a SuperObj. */
export type SuperObjPatchBody = v.InferOutput<typeof SuperObjPatchBodySchema>;

export const SuperObjPostBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  is_roid: v.optional(v.boolean()),
  obj_ids: v.optional(v.array(v.string())),
});

/** Request body for creating a SuperObj. */
export type SuperObjPostBody = v.InferOutput<typeof SuperObjPostBodySchema>;

export const SuperObjPostResponseSchema = v.strictObject({
  id: v.number(),
});

/** Result of creating a super-object. */
export type SuperObjPostResponse = v.InferOutput<
  typeof SuperObjPostResponseSchema
>;

export const SuperObjResponseSchema = v.strictObject({
  id: v.number(),
  name: v.nullish(v.string()),
  is_roid: v.nullish(v.boolean()),
  created_at: v.nullish(v.string()),
  objs: v.optional(v.array(SuperObjMemberResponseSchema)),
});

/** Several objects that are one astrophysical source. */
export type SuperObjResponse = v.InferOutput<typeof SuperObjResponseSchema>;
