// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import {
  EphemerisResponseSchema,
  GroupResponseSchema,
  InstrumentResponseSchema,
  UserResponseSchema,
} from "./_cyclic.js";
import { AssignmentResponseSchema } from "./assignments.js";

export const ObservingRunBulkEditBodySchema = v.strictObject({
  current_status: v.nullish(v.string()),
  new_status: v.nullish(v.string()),
});

/** Request body for bulk-updating the assignments of an observing run. */
export type ObservingRunBulkEditBody = v.InferOutput<
  typeof ObservingRunBulkEditBodySchema
>;

export const ObservingRunGetQuerySchema = v.strictObject({
  upcomingOnly: v.optional(v.boolean()),
  numPerPage: v.nullish(v.number()),
  pageNumber: v.optional(v.number()),
});

/** Query parameters for listing observing runs. */
export type ObservingRunGetQuery = v.InferOutput<
  typeof ObservingRunGetQuerySchema
>;

export const ObservingRunPostSchema = v.strictObject({
  instrument_id: v.number(),
  calendar_date: v.string(),
  pi: v.nullish(v.string()),
  observers: v.nullish(v.string()),
  duration: v.nullish(v.number()),
  group_id: v.nullish(v.number()),
});

/** Payload for creating an observing run. */
export type ObservingRunPost = v.InferOutput<typeof ObservingRunPostSchema>;

export const ObservingRunPostBodySchema = v.strictObject({
  instrument_id: v.number(),
  calendar_date: v.string(),
  pi: v.nullish(v.string()),
  observers: v.nullish(v.string()),
  duration: v.nullish(v.number()),
  group_id: v.nullish(v.number()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for creating an observing run. */
export type ObservingRunPostBody = v.InferOutput<
  typeof ObservingRunPostBodySchema
>;

export const ObservingRunPostResponseSchema = v.object({
  id: v.number(),
});

/** ID of the newly created observing run. */
export type ObservingRunPostResponse = v.InferOutput<
  typeof ObservingRunPostResponseSchema
>;

export const ObservingRunPutBodySchema = v.strictObject({
  instrument_id: v.nullish(v.number()),
  calendar_date: v.nullish(v.string()),
  pi: v.nullish(v.string()),
  observers: v.nullish(v.string()),
  duration: v.nullish(v.number()),
  group_id: v.nullish(v.number()),
});

/** Request body for updating an observing run. */
export type ObservingRunPutBody = v.InferOutput<
  typeof ObservingRunPutBodySchema
>;

export const ObservingRunResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  instrument_id: v.nullish(v.number()),
  calendar_date: v.nullish(v.string()),
  run_end_utc: v.nullish(v.string()),
  pi: v.nullish(v.string()),
  observers: v.nullish(v.string()),
  duration: v.nullish(v.number()),
  group_id: v.nullish(v.number()),
  owner_id: v.nullish(v.number()),
  ephemeris: v.nullish(EphemerisResponseSchema),
  instrument: v.nullish(InstrumentResponseSchema),
  group: v.nullish(GroupResponseSchema),
  owner: v.nullish(UserResponseSchema),
  assignments: v.optional(v.array(AssignmentResponseSchema)),
  sources: v.optional(v.array(v.record(v.string(), v.unknown()))),
});

/**
 * A classical observing run (``ObservingRun``).
 *
 * The list endpoint returns ``to_dict()`` output (columns plus the
 * eager-loaded ``instrument``); the single-run endpoint returns a hand-built
 * dict that swaps ``created_at``/``modified``/``run_end_utc`` for
 * ``ephemeris`` and the run's ``assignments``.
 */
export type ObservingRunResponse = v.InferOutput<
  typeof ObservingRunResponseSchema
>;

export const ObservingRunUpdateSchema = v.strictObject({
  instrument_id: v.nullish(v.number()),
  calendar_date: v.nullish(v.string()),
  pi: v.nullish(v.string()),
  observers: v.nullish(v.string()),
  duration: v.nullish(v.number()),
  group_id: v.nullish(v.number()),
});

/** Payload for updating an observing run; every field is optional. */
export type ObservingRunUpdate = v.InferOutput<typeof ObservingRunUpdateSchema>;
