// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import {
  AllocationResponseSchema,
  type AllocationResponse,
  GroupResponseSchema,
  type GroupResponse,
  ObservationPlanRequestResponseSchema,
  UserResponseSchema,
  type UserResponse,
} from "./_cyclic.js";

export const AllocationObservationPlansPageResponseSchema = v.strictObject({
  observation_plan_requests: v.optional(
    v.array(ObservationPlanRequestResponseSchema),
  ),
  totalMatches: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  numPerPage: v.nullish(v.number()),
});

/** One page of observation plan requests under an allocation. */
export type AllocationObservationPlansPageResponse = v.InferOutput<
  typeof AllocationObservationPlansPageResponseSchema
>;

export const DefaultObservationPlanPostSchema = v.strictObject({
  allocation_id: v.number(),
  default_plan_name: v.string(),
  payload: v.record(v.string(), v.unknown()),
  auto_send: v.nullish(v.boolean()),
  filters: v.nullish(v.record(v.string(), v.unknown())),
  target_group_ids: v.nullish(v.array(v.number())),
  requester_id: v.nullish(v.number()),
});

/** Payload for creating a default observation plan request. */
export type DefaultObservationPlanPost = v.InferOutput<
  typeof DefaultObservationPlanPostSchema
>;

export const DefaultObservationPlanPostBodySchema = v.strictObject({
  allocation_id: v.nullish(v.number()),
  default_plan_name: v.nullish(v.string()),
  payload: v.nullish(v.record(v.string(), v.unknown())),
  target_group_ids: v.nullish(v.array(v.number())),
  filters: v.nullish(v.record(v.string(), v.unknown())),
  auto_send: v.nullish(v.boolean()),
  requester_id: v.nullish(v.number()),
});

/** Request body for creating a default observation plan request. */
export type DefaultObservationPlanPostBody = v.InferOutput<
  typeof DefaultObservationPlanPostBodySchema
>;

export const DefaultObservationPlanPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating a default observation plan request. */
export type DefaultObservationPlanPostResponse = v.InferOutput<
  typeof DefaultObservationPlanPostResponseSchema
>;

/** A default observation plan request. */
export type DefaultObservationPlanRequestResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  requester_id?: number | null | undefined;
  payload?: Record<string, unknown> | undefined;
  filters?: Record<string, unknown> | null | undefined;
  allocation_id?: number | null | undefined;
  default_plan_name?: string | null | undefined;
  auto_send?: boolean | null | undefined;
  allocation?: AllocationResponse | null | undefined;
  requester?: UserResponse | null | undefined;
  target_groups?: GroupResponse[] | undefined;
  default_survey_efficiencies?:
    DefaultSurveyEfficiencyRequestResponse[] | undefined;
};

export const DefaultObservationPlanRequestResponseSchema: v.GenericSchema<DefaultObservationPlanRequestResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    requester_id: v.nullish(v.number()),
    payload: v.optional(v.record(v.string(), v.unknown())),
    filters: v.nullish(v.record(v.string(), v.unknown())),
    allocation_id: v.nullish(v.number()),
    default_plan_name: v.nullish(v.string()),
    auto_send: v.nullish(v.boolean()),
    allocation: v.nullish(AllocationResponseSchema),
    requester: v.nullish(UserResponseSchema),
    target_groups: v.optional(v.array(GroupResponseSchema)),
    default_survey_efficiencies: v.optional(
      v.array(v.lazy(() => DefaultSurveyEfficiencyRequestResponseSchema)),
    ),
  });

/** A default efficiency request attached to a default observation plan. */
export type DefaultSurveyEfficiencyRequestResponse = {
  id: number;
  created_at?: string | null | undefined;
  modified?: string | null | undefined;
  payload?: Record<string, unknown> | undefined;
  default_observationplan_request_id?: number | null | undefined;
  default_observationplan_request?:
    DefaultObservationPlanRequestResponse | null | undefined;
};

export const DefaultSurveyEfficiencyRequestResponseSchema: v.GenericSchema<DefaultSurveyEfficiencyRequestResponse> =
  v.strictObject({
    id: v.number(),
    created_at: v.nullish(v.string()),
    modified: v.nullish(v.string()),
    payload: v.optional(v.record(v.string(), v.unknown())),
    default_observationplan_request_id: v.nullish(v.number()),
    default_observationplan_request: v.nullish(
      v.lazy(() => DefaultObservationPlanRequestResponseSchema),
    ),
  });

export const ObservationPlanCreateObservingRunPostBodySchema = v.strictObject({
  groupIds: v.nullish(v.array(v.number())),
});

/** Request body for creating an observing run from an observation plan. */
export type ObservationPlanCreateObservingRunPostBody = v.InferOutput<
  typeof ObservationPlanCreateObservingRunPostBodySchema
>;

export const ObservationPlanFieldsDeleteBodySchema = v.strictObject({
  fieldIds: v.nullish(v.array(v.number())),
});

/** Request body for removing fields from an observation plan. */
export type ObservationPlanFieldsDeleteBody = v.InferOutput<
  typeof ObservationPlanFieldsDeleteBodySchema
>;

export const ObservationPlanGeoJSONResponseSchema = v.strictObject({
  geojson: v.optional(v.array(v.record(v.string(), v.unknown()))),
});

/** GeoJSON contours of the fields of an observation plan. */
export type ObservationPlanGeoJSONResponse = v.InferOutput<
  typeof ObservationPlanGeoJSONResponseSchema
>;

export const ObservationPlanIdsResponseSchema = v.strictObject({
  ids: v.optional(v.array(v.number())),
});

/** Result of submitting observation plan requests. */
export type ObservationPlanIdsResponse = v.InferOutput<
  typeof ObservationPlanIdsResponseSchema
>;

export const ObservationPlanManualPostSchema = v.strictObject({
  allocation_id: v.number(),
  plan_name: v.string(),
  status: v.string(),
  payload: v.record(v.string(), v.unknown()),
  observation_plans: v.array(v.record(v.string(), v.unknown())),
  gcnevent_id: v.nullish(v.number()),
  dateobs: v.nullish(v.string()),
  localization_id: v.nullish(v.number()),
  localization_name: v.nullish(v.string()),
});

/** Payload for submitting a manually-built observation plan. */
export type ObservationPlanManualPost = v.InferOutput<
  typeof ObservationPlanManualPostSchema
>;

export const ObservationPlanManualPostBodySchema = v.strictObject({
  gcnevent_id: v.nullish(v.number()),
  dateobs: v.nullish(v.string()),
  localization_id: v.nullish(v.number()),
  localization_name: v.nullish(v.string()),
  allocation_id: v.nullish(v.number()),
  status: v.nullish(v.string()),
  payload: v.nullish(v.record(v.string(), v.unknown())),
  plan_name: v.nullish(v.string()),
  observation_plans: v.nullish(v.array(v.record(v.string(), v.unknown()))),
});

/** Request body for submitting a manual observation plan request. */
export type ObservationPlanManualPostBody = v.InferOutput<
  typeof ObservationPlanManualPostBodySchema
>;

export const ObservationPlanManualPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when submitting a manual observation plan request. */
export type ObservationPlanManualPostResponse = v.InferOutput<
  typeof ObservationPlanManualPostResponseSchema
>;

export const ObservationPlanNameGetQuerySchema = v.strictObject({
  name: v.nullish(v.string()),
});

/** Query parameters for retrieving observation plan names. */
export type ObservationPlanNameGetQuery = v.InferOutput<
  typeof ObservationPlanNameGetQuerySchema
>;

export const ObservationPlanPlotGetQuerySchema = v.strictObject({
  maxAirmass: v.optional(v.number()),
  twilight: v.optional(v.picklist(["astronomical", "nautical", "civil"])),
});

/** Query parameters for the worldmap and observability plots. */
export type ObservationPlanPlotGetQuery = v.InferOutput<
  typeof ObservationPlanPlotGetQuerySchema
>;

export const ObservationPlanPostSchema = v.strictObject({
  gcnevent_id: v.number(),
  allocation_id: v.number(),
  localization_id: v.number(),
  payload: v.record(v.string(), v.unknown()),
  status: v.nullish(v.string()),
  target_group_ids: v.nullish(v.array(v.number())),
  requester_id: v.nullish(v.number()),
});

/** Payload for submitting an observation plan request. */
export type ObservationPlanPost = v.InferOutput<
  typeof ObservationPlanPostSchema
>;

export const ObservationPlanRequestGetQuerySchema = v.strictObject({
  includePlannedObservations: v.optional(v.boolean()),
  rubinFormat: v.optional(v.boolean()),
  dateobs: v.nullish(v.string()),
  instrumentID: v.nullish(v.number()),
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  status: v.nullish(v.string()),
  numPerPage: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
});

/** Query parameters for retrieving observation plan requests. */
export type ObservationPlanRequestGetQuery = v.InferOutput<
  typeof ObservationPlanRequestGetQuerySchema
>;

export const ObservationPlanRequestPostBodySchema = v.strictObject({
  observation_plans: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  combine_plans: v.optional(v.boolean()),
  gcnevent_id: v.nullish(v.number()),
  payload: v.nullish(v.record(v.string(), v.unknown())),
  status: v.nullish(v.string()),
  allocation_id: v.nullish(v.number()),
  localization_id: v.nullish(v.number()),
  target_group_ids: v.nullish(v.array(v.number())),
  requester_id: v.nullish(v.number()),
});

/**
 * Request body for submitting one or more observation plan requests.
 *
 * Accepts either a single plan (the plan fields at the top level) or a
 * `observation_plans` list together with `combine_plans`.
 */
export type ObservationPlanRequestPostBody = v.InferOutput<
  typeof ObservationPlanRequestPostBodySchema
>;

export const ObservationPlanRequestPostResponseSchema = v.object({
  ids: v.array(v.number()),
});

/** Data payload returned when submitting observation plan requests. */
export type ObservationPlanRequestPostResponse = v.InferOutput<
  typeof ObservationPlanRequestPostResponseSchema
>;

export const ObservationPlanRequestsPageResponseSchema = v.strictObject({
  requests: v.optional(v.array(ObservationPlanRequestResponseSchema)),
  totalMatches: v.optional(v.number()),
});

/** One page of results from an observation plan requests query. */
export type ObservationPlanRequestsPageResponse = v.InferOutput<
  typeof ObservationPlanRequestsPageResponseSchema
>;

export const ObservationPlanSimSurveyGetQuerySchema = v.strictObject({
  numberInjections: v.optional(v.number()),
  numberDetections: v.optional(v.number()),
  detectionThreshold: v.optional(v.number()),
  minimumPhase: v.optional(v.number()),
  maximumPhase: v.optional(v.number()),
  modelName: v.optional(v.string()),
  optionalInjectionParameters: v.optional(v.string()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Query parameters for running a simsurvey efficiency analysis. */
export type ObservationPlanSimSurveyGetQuery = v.InferOutput<
  typeof ObservationPlanSimSurveyGetQuerySchema
>;

export const ObservationPlanSimSurveyResponseSchema = v.strictObject({
  id: v.number(),
});

/** Result of starting a simsurvey efficiency analysis. */
export type ObservationPlanSimSurveyResponse = v.InferOutput<
  typeof ObservationPlanSimSurveyResponseSchema
>;
