// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import {
  InstrumentFieldResponseSchema,
  InstrumentResponseSchema,
} from "./_cyclic.js";

export const ObservationASCIIFilePostBodySchema = v.strictObject({
  instrumentID: v.optional(v.union([v.number(), v.string(), v.null()])),
  observationData: v.nullish(v.string()),
});

/** Request body for uploading observations from an ASCII file. */
export type ObservationASCIIFilePostBody = v.InferOutput<
  typeof ObservationASCIIFilePostBodySchema
>;

export const ObservationExternalAPIDeleteBodySchema = v.strictObject({
  queueName: v.nullish(v.string()),
});

/** Request body for deleting queued observations from an external API. */
export type ObservationExternalAPIDeleteBody = v.InferOutput<
  typeof ObservationExternalAPIDeleteBodySchema
>;

export const ObservationExternalAPIGetQuerySchema = v.strictObject({
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  queuesOnly: v.optional(v.boolean()),
});

/** Query parameters for retrieving queued observations from an external API. */
export type ObservationExternalAPIGetQuery = v.InferOutput<
  typeof ObservationExternalAPIGetQuerySchema
>;

export const ObservationExternalAPIPostBodySchema = v.strictObject({
  start_date: v.nullish(v.string()),
  end_date: v.nullish(v.string()),
  allocation_id: v.nullish(v.number()),
});

/** Request body for retrieving observations from an external API. */
export type ObservationExternalAPIPostBody = v.InferOutput<
  typeof ObservationExternalAPIPostBodySchema
>;

export const ObservationGetQuerySchema = v.strictObject({
  telescopeName: v.nullish(v.string()),
  instrumentName: v.nullish(v.string()),
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  localizationDateobs: v.nullish(v.string()),
  localizationName: v.nullish(v.string()),
  localizationCumprob: v.optional(v.number()),
  numberObservations: v.optional(v.number()),
  returnStatistics: v.optional(v.boolean()),
  statsMethod: v.optional(v.picklist(["python", "db"])),
  statsLogging: v.optional(v.boolean()),
  includeGeoJSON: v.optional(v.boolean()),
  observationStatus: v.optional(v.picklist(["executed", "queued"])),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
  sortBy: v.nullish(v.string()),
  sortOrder: v.optional(v.string()),
});

/** Query parameters for retrieving observations. */
export type ObservationGetQuery = v.InferOutput<
  typeof ObservationGetQuerySchema
>;

export const ObservationPostSchema = v.strictObject({
  telescopeName: v.string(),
  instrumentName: v.string(),
  observationData: v.record(v.string(), v.array(v.unknown())),
});

/** Payload for ingesting a set of executed observations. */
export type ObservationPost = v.InferOutput<typeof ObservationPostSchema>;

export const ObservationPostBodySchema = v.strictObject({
  telescopeName: v.nullish(v.string()),
  instrumentName: v.nullish(v.string()),
  observationData: v.nullish(v.record(v.string(), v.unknown())),
});

/** Request body for ingesting a set of ExecutedObservations. */
export type ObservationPostBody = v.InferOutput<
  typeof ObservationPostBodySchema
>;

export const ObservationQueuesResponseSchema = v.strictObject({
  queue_names: v.optional(v.array(v.string())),
});

/** Queue names retrieved from an instrument's external API. */
export type ObservationQueuesResponse = v.InferOutput<
  typeof ObservationQueuesResponseSchema
>;

export const ObservationResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  instrument_id: v.nullish(v.number()),
  instrument_field_id: v.nullish(v.number()),
  observation_id: v.nullish(v.number()),
  obstime: v.nullish(v.string()),
  filt: v.nullish(v.string()),
  exposure_time: v.nullish(v.number()),
  airmass: v.nullish(v.number()),
  seeing: v.nullish(v.number()),
  limmag: v.nullish(v.number()),
  target_name: v.nullish(v.string()),
  processed_fraction: v.nullish(v.number()),
  queue_name: v.nullish(v.string()),
  validity_window_start: v.nullish(v.string()),
  validity_window_end: v.nullish(v.string()),
  field: v.nullish(InstrumentFieldResponseSchema),
  instrument: v.nullish(InstrumentResponseSchema),
});

/**
 * A survey observation, either executed or queued.
 *
 * The endpoint returns either kind depending on ``observationStatus``, so
 * the executed-only fields (``observation_id``, ``airmass``, ``seeing``,
 * ``limmag``, ``target_name``, ``processed_fraction``) and the queued-only
 * ones (``queue_name``, ``validity_window_start``, ``validity_window_end``)
 * are all optional.
 */
export type ObservationResponse = v.InferOutput<
  typeof ObservationResponseSchema
>;

export const ObservationSimSurveyGetQuerySchema = v.strictObject({
  startDate: v.string(),
  endDate: v.string(),
  localizationDateobs: v.string(),
  localizationName: v.nullish(v.string()),
  localizationCumprob: v.optional(v.number()),
  numberInjections: v.optional(v.number()),
  numberDetections: v.optional(v.number()),
  detectionThreshold: v.optional(v.number()),
  minimumPhase: v.optional(v.number()),
  maximumPhase: v.optional(v.number()),
  modelName: v.optional(v.string()),
  optionalInjectionParameters: v.optional(v.string()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Query parameters for performing a simsurvey efficiency calculation. */
export type ObservationSimSurveyGetQuery = v.InferOutput<
  typeof ObservationSimSurveyGetQuerySchema
>;

export const ObservationSimSurveyResponseSchema = v.strictObject({
  id: v.number(),
});

/** Result of starting a SimSurvey efficiency calculation. */
export type ObservationSimSurveyResponse = v.InferOutput<
  typeof ObservationSimSurveyResponseSchema
>;

export const ObservationTreasureMapDeleteBodySchema = v.strictObject({
  localizationDateobs: v.nullish(v.string()),
});

/** Request body for removing executed observations from TreasureMap. */
export type ObservationTreasureMapDeleteBody = v.InferOutput<
  typeof ObservationTreasureMapDeleteBodySchema
>;

export const ObservationTreasureMapPostBodySchema = v.strictObject({
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  localizationDateobs: v.nullish(v.string()),
  localizationName: v.nullish(v.string()),
  localizationCumprob: v.optional(v.number()),
});

/** Request body for submitting executed observations to TreasureMap. */
export type ObservationTreasureMapPostBody = v.InferOutput<
  typeof ObservationTreasureMapPostBodySchema
>;

export const ObservationTreasureMapPostQuerySchema = v.strictObject({
  numberObservations: v.optional(v.number()),
});

/**
 * Query parameters for submitting observations to TreasureMap.
 *
 * Everything else this endpoint reads comes from the JSON body.
 */
export type ObservationTreasureMapPostQuery = v.InferOutput<
  typeof ObservationTreasureMapPostQuerySchema
>;

export const ObservationsPageResponseSchema = v.strictObject({
  observations: v.optional(v.array(ObservationResponseSchema)),
  totalMatches: v.optional(v.number()),
  probability: v.nullish(v.number()),
  area: v.nullish(v.number()),
  geojson: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  field_ids: v.nullish(v.array(v.number())),
  min_observations_per_field: v.nullish(v.number()),
});

/**
 * One page of results from an observations query.
 *
 * The statistics and GeoJSON keys are only present when the request asked
 * for them.
 */
export type ObservationsPageResponse = v.InferOutput<
  typeof ObservationsPageResponseSchema
>;
