// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { GroupResponseSchema } from "./_cyclic.js";
import { StreamResponseSchema } from "./streams.js";

export const PhotometricSeriesDetailResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  series_name: v.nullish(v.string()),
  series_obj_id: v.nullish(v.string()),
  filter: v.nullish(v.string()),
  channel: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  filename: v.nullish(v.string()),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_unc: v.nullish(v.number()),
  dec_unc: v.nullish(v.number()),
  mjd_first: v.nullish(v.number()),
  mjd_mid: v.nullish(v.number()),
  mjd_last: v.nullish(v.number()),
  mjd_last_detected: v.nullish(v.number()),
  mag_first: v.nullish(v.number()),
  mag_last: v.nullish(v.number()),
  mag_last_detected: v.nullish(v.number()),
  is_detected: v.nullish(v.boolean()),
  exp_time: v.nullish(v.number()),
  frame_rate: v.nullish(v.number()),
  num_exp: v.nullish(v.number()),
  time_stamp_alignment: v.nullish(v.picklist(["start", "middle", "end"])),
  limiting_mag: v.nullish(v.number()),
  ref_flux: v.nullish(v.number()),
  ref_fluxerr: v.nullish(v.number()),
  mean_mag: v.nullish(v.number()),
  rms_mag: v.nullish(v.number()),
  robust_mag: v.nullish(v.number()),
  robust_rms: v.nullish(v.number()),
  median_snr: v.nullish(v.number()),
  best_snr: v.nullish(v.number()),
  worst_snr: v.nullish(v.number()),
  medians: v.nullish(v.record(v.string(), v.unknown())),
  maxima: v.nullish(v.record(v.string(), v.unknown())),
  minima: v.nullish(v.record(v.string(), v.unknown())),
  stds: v.nullish(v.record(v.string(), v.unknown())),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  hash: v.nullish(v.string()),
  autodelete: v.nullish(v.boolean()),
  instrument_id: v.nullish(v.number()),
  followup_request_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
  owner_id: v.nullish(v.number()),
  group_ids: v.optional(v.array(v.number())),
  stream_ids: v.optional(v.array(v.number())),
  groups: v.optional(v.array(GroupResponseSchema)),
  streams: v.optional(v.array(StreamResponseSchema)),
  data: v.optional(
    v.union([v.record(v.string(), v.array(v.unknown())), v.string(), v.null()]),
  ),
});

/** A photometric series: one light curve of one object in one series. */
export type PhotometricSeriesDetailResponse = v.InferOutput<
  typeof PhotometricSeriesDetailResponseSchema
>;

export const PhotometricSeriesGetQuerySchema = v.strictObject({
  dataFormat: v.nullish(v.picklist(["json", "hdf5", "none"])),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  radius: v.nullish(v.number()),
  objectID: v.nullish(v.string()),
  rejectedObjectID: v.nullish(v.string()),
  seriesName: v.nullish(v.string()),
  seriesObjID: v.nullish(v.string()),
  filter: v.nullish(v.string()),
  channel: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  filename: v.nullish(v.string()),
  startBefore: v.nullish(v.string()),
  startAfter: v.nullish(v.string()),
  midBefore: v.nullish(v.string()),
  midAfter: v.nullish(v.string()),
  endBefore: v.nullish(v.string()),
  endAfter: v.nullish(v.string()),
  detected: v.nullish(v.boolean()),
  expTime: v.nullish(v.number()),
  minExpTime: v.nullish(v.number()),
  maxExpTime: v.nullish(v.number()),
  minFrameRate: v.nullish(v.number()),
  maxFrameRate: v.nullish(v.number()),
  minNumExposures: v.nullish(v.number()),
  maxNumExposures: v.nullish(v.number()),
  instrumentID: v.nullish(v.number()),
  followupRequestID: v.nullish(v.number()),
  assignmentID: v.nullish(v.number()),
  ownerID: v.nullish(v.number()),
  magBrighterThan: v.nullish(v.number()),
  magFainterThan: v.nullish(v.number()),
  limitingMagBrighterThan: v.nullish(v.number()),
  limitingMagFainterThan: v.nullish(v.number()),
  limitingMagIsNaN: v.optional(v.boolean()),
  magrefBrighterThan: v.nullish(v.number()),
  magrefFainterThan: v.nullish(v.number()),
  maxRMS: v.nullish(v.number()),
  minRMS: v.nullish(v.number()),
  useRobustMagAndRMS: v.optional(v.boolean()),
  maxMedianSNR: v.nullish(v.number()),
  minMedianSNR: v.nullish(v.number()),
  maxBestSNR: v.nullish(v.number()),
  minBestSNR: v.nullish(v.number()),
  maxWorstSNR: v.nullish(v.number()),
  minWorstSNR: v.nullish(v.number()),
  hash: v.nullish(v.string()),
  sortBy: v.optional(v.string()),
  sortOrder: v.optional(v.picklist(["asc", "desc"])),
  numPerPage: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
});

/** Query parameters for retrieving photometric series. */
export type PhotometricSeriesGetQuery = v.InferOutput<
  typeof PhotometricSeriesGetQuerySchema
>;

export const PhotometricSeriesPageResponseSchema = v.strictObject({
  series: v.optional(v.array(PhotometricSeriesDetailResponseSchema)),
  totalMatches: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/** One page of results from a photometric series query. */
export type PhotometricSeriesPageResponse = v.InferOutput<
  typeof PhotometricSeriesPageResponseSchema
>;

export const PhotometricSeriesPatchBodySchema = v.strictObject({
  data: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  series_name: v.nullish(v.string()),
  series_obj_id: v.optional(v.union([v.string(), v.number(), v.null()])),
  obj_id: v.optional(v.union([v.string(), v.number(), v.null()])),
  instrument_id: v.nullish(v.number()),
  group_ids: v.optional(
    v.union([v.array(v.unknown()), v.number(), v.string(), v.null()]),
  ),
  stream_ids: v.optional(v.union([v.array(v.unknown()), v.string(), v.null()])),
  ra: v.optional(v.union([v.number(), v.string(), v.null()])),
  dec: v.optional(v.union([v.number(), v.string(), v.null()])),
  exp_time: v.optional(v.union([v.number(), v.string(), v.null()])),
  filter: v.nullish(v.string()),
  channel: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  limiting_mag: v.optional(v.union([v.number(), v.string(), v.null()])),
  magref: v.optional(v.union([v.number(), v.string(), v.null()])),
  e_magref: v.optional(v.union([v.number(), v.string(), v.null()])),
  ref_flux: v.optional(v.union([v.number(), v.string(), v.null()])),
  ref_fluxerr: v.optional(v.union([v.number(), v.string(), v.null()])),
  ra_unc: v.optional(v.union([v.number(), v.string(), v.null()])),
  dec_unc: v.optional(v.union([v.number(), v.string(), v.null()])),
  followup_request_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
  time_stamp_alignment: v.nullish(v.string()),
  altdata: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
});

/** Request body for updating a photometric series (all inputs optional). */
export type PhotometricSeriesPatchBody = v.InferOutput<
  typeof PhotometricSeriesPatchBodySchema
>;

export const PhotometricSeriesPostSchema = v.strictObject({
  data: v.optional(
    v.union([v.record(v.string(), v.array(v.unknown())), v.string(), v.null()]),
  ),
  series_name: v.nullish(v.string()),
  series_obj_id: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  instrument_id: v.nullish(v.number()),
  group_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
  stream_ids: v.nullish(v.array(v.number())),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_unc: v.nullish(v.number()),
  dec_unc: v.nullish(v.number()),
  exp_time: v.nullish(v.number()),
  filter: v.nullish(v.string()),
  channel: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  limiting_mag: v.nullish(v.number()),
  magref: v.nullish(v.number()),
  e_magref: v.nullish(v.number()),
  ref_flux: v.nullish(v.number()),
  ref_fluxerr: v.nullish(v.number()),
  followup_request_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
  time_stamp_alignment: v.nullish(v.picklist(["start", "middle", "end"])),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * Payload for uploading or updating a photometric series.
 *
 * ``data`` is either a mapping of column name to list of values, or a
 * base64-encoded HDF5 bytestream written with ``pandas.HDFStore``. It must
 * contain an ``mjd`` column and either a ``flux`` or a ``mag`` column.
 * ``ra``, ``dec``, ``exp_time`` and ``filter`` are inferred from the data
 * columns when not given explicitly. ``data`` is required when creating a
 * series and optional when updating one.
 */
export type PhotometricSeriesPost = v.InferOutput<
  typeof PhotometricSeriesPostSchema
>;

export const PhotometricSeriesPostBodySchema = v.strictObject({
  data: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  series_name: v.nullish(v.string()),
  series_obj_id: v.optional(v.union([v.string(), v.number(), v.null()])),
  obj_id: v.optional(v.union([v.string(), v.number(), v.null()])),
  instrument_id: v.nullish(v.number()),
  group_ids: v.optional(
    v.union([v.array(v.unknown()), v.number(), v.string(), v.null()]),
  ),
  stream_ids: v.optional(v.union([v.array(v.unknown()), v.string(), v.null()])),
  ra: v.optional(v.union([v.number(), v.string(), v.null()])),
  dec: v.optional(v.union([v.number(), v.string(), v.null()])),
  exp_time: v.optional(v.union([v.number(), v.string(), v.null()])),
  filter: v.nullish(v.string()),
  channel: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  limiting_mag: v.optional(v.union([v.number(), v.string(), v.null()])),
  magref: v.optional(v.union([v.number(), v.string(), v.null()])),
  e_magref: v.optional(v.union([v.number(), v.string(), v.null()])),
  ref_flux: v.optional(v.union([v.number(), v.string(), v.null()])),
  ref_fluxerr: v.optional(v.union([v.number(), v.string(), v.null()])),
  ra_unc: v.optional(v.union([v.number(), v.string(), v.null()])),
  dec_unc: v.optional(v.union([v.number(), v.string(), v.null()])),
  followup_request_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
  time_stamp_alignment: v.nullish(v.string()),
  altdata: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
});

/**
 * Request body for uploading a photometric series.
 *
 * Every field is optional at this layer; the required set and per-value
 * type coercion are enforced downstream by ``verify_data`` / ``verify_metadata``
 * and the handler (which errors if ``data`` is missing).
 */
export type PhotometricSeriesPostBody = v.InferOutput<
  typeof PhotometricSeriesPostBodySchema
>;

export const PhotometricSeriesResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating/updating a photometric series. */
export type PhotometricSeriesResponse = v.InferOutput<
  typeof PhotometricSeriesResponseSchema
>;
