// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { GroupResponseSchema, UserResponseSchema } from "./_cyclic.js";
import { AnnotationDetailResponseSchema } from "./annotations.js";
import { StreamResponseSchema } from "./streams.js";

export const ObjPhotometryGetQuerySchema = v.strictObject({
  format: v.optional(v.picklist(["mag", "flux", "both", "plot"])),
  magsys: v.optional(
    v.picklist(["jla1", "ab", "vega", "bd17", "csp", "ab-b12"]),
  ),
  individualOrSeries: v.optional(v.picklist(["individual", "series", "both"])),
  phaseFoldData: v.optional(v.boolean()),
  deduplicatePhotometry: v.optional(v.boolean()),
  includeOwnerInfo: v.optional(v.boolean()),
  includeStreamInfo: v.optional(v.boolean()),
  includeValidationInfo: v.optional(v.boolean()),
  includeAnnotationInfo: v.optional(v.boolean()),
  includeExtinction: v.optional(v.boolean()),
  includeSuperObjsPhotometry: v.optional(v.boolean()),
});

/** Query parameters for getting an object's photometry. */
export type ObjPhotometryGetQuery = v.InferOutput<
  typeof ObjPhotometryGetQuerySchema
>;

export const PhotometryFlexibleBodySchema = v.strictObject({
  obj_id: v.optional(
    v.union([
      v.string(),
      v.number(),
      v.array(v.union([v.string(), v.number(), v.null()])),
      v.null(),
    ]),
  ),
  mjd: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  instrument_id: v.optional(
    v.union([
      v.number(),
      v.string(),
      v.array(v.union([v.number(), v.string(), v.null()])),
      v.null(),
    ]),
  ),
  filter: v.optional(
    v.union([v.string(), v.array(v.nullable(v.string())), v.null()]),
  ),
  magsys: v.optional(
    v.union([v.string(), v.array(v.nullable(v.string())), v.null()]),
  ),
  assignment_id: v.nullish(v.number()),
  ra: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  dec: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ra_unc: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  dec_unc: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  origin: v.optional(
    v.union([v.string(), v.array(v.nullable(v.string())), v.null()]),
  ),
  group_ids: v.optional(v.union([v.array(v.unknown()), v.string(), v.null()])),
  stream_ids: v.nullish(v.array(v.unknown())),
  altdata: v.optional(
    v.union([
      v.record(v.string(), v.unknown()),
      v.array(v.unknown()),
      v.null(),
    ]),
  ),
  extinction_corrected: v.optional(
    v.union([v.boolean(), v.string(), v.null()]),
  ),
  flux: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  fluxerr: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  zp: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ref_flux: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ref_fluxerr: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ref_zp: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  mag: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  magerr: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  limiting_mag: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  limiting_mag_nsigma: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  magref: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  e_magref: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
});

/**
 * Request body for bulk photometry upload (POST/PUT).
 *
 * Union of the flux-space and magnitude-space payloads; a valid request must
 * match one of them (enforced downstream by the marshmallow schemas).
 */
export type PhotometryFlexibleBody = v.InferOutput<
  typeof PhotometryFlexibleBodySchema
>;

export const PhotometryGetQuerySchema = v.strictObject({
  format: v.optional(v.picklist(["mag", "flux", "both"])),
  magsys: v.optional(
    v.picklist(["jla1", "ab", "vega", "bd17", "csp", "ab-b12"]),
  ),
});

/** Query parameters for getting a single photometry point. */
export type PhotometryGetQuery = v.InferOutput<typeof PhotometryGetQuerySchema>;

export const PhotometryPatchBodySchema = v.strictObject({
  obj_id: v.nullish(v.string()),
  mjd: v.nullish(v.number()),
  instrument_id: v.nullish(v.number()),
  filter: v.nullish(v.string()),
  magsys: v.nullish(v.string()),
  assignment_id: v.nullish(v.number()),
  alert_id: v.nullish(v.number()),
  origin: v.nullish(v.string()),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_unc: v.nullish(v.number()),
  dec_unc: v.nullish(v.number()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  group_ids: v.nullish(v.array(v.unknown())),
  stream_ids: v.nullish(v.array(v.unknown())),
  flux: v.nullish(v.number()),
  fluxerr: v.nullish(v.number()),
  zp: v.nullish(v.number()),
  ref_flux: v.nullish(v.number()),
  ref_fluxerr: v.nullish(v.number()),
  ref_zp: v.nullish(v.number()),
  mag: v.nullish(v.number()),
  magerr: v.nullish(v.number()),
  limiting_mag: v.nullish(v.number()),
  magref: v.nullish(v.number()),
  e_magref: v.nullish(v.number()),
});

/**
 * Request body for updating a single photometry point (PATCH).
 *
 * Single-point (scalar) counterpart of the bulk body; the deep validation is
 * still done by the marshmallow PhotometryFlux/PhotometryMag schemas. Every
 * field is optional so those schemas keep emitting their exact error messages.
 */
export type PhotometryPatchBody = v.InferOutput<
  typeof PhotometryPatchBodySchema
>;

export const PhotometryPatchQuerySchema = v.strictObject({
  refresh: v.optional(v.boolean()),
});

/** Query parameters for updating a photometry point. */
export type PhotometryPatchQuery = v.InferOutput<
  typeof PhotometryPatchQuerySchema
>;

export const PhotometryPointValidationResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  photometry_id: v.nullish(v.number()),
  validated: v.nullish(v.boolean()),
  validator_id: v.nullish(v.number()),
  explanation: v.nullish(v.string()),
  notes: v.nullish(v.string()),
});

/** A validated/rejected mark on a photometry point. */
export type PhotometryPointValidationResponse = v.InferOutput<
  typeof PhotometryPointValidationResponseSchema
>;

export const PhotometryPointResponseSchema = v.looseObject({
  id: v.number(),
  obj_id: v.nullish(v.string()),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_unc: v.nullish(v.number()),
  dec_unc: v.nullish(v.number()),
  filter: v.nullish(v.string()),
  mjd: v.nullish(v.number()),
  snr: v.nullish(v.number()),
  instrument_id: v.nullish(v.number()),
  instrument_name: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  altdata: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  created_at: v.nullish(v.string()),
  groups: v.optional(v.array(GroupResponseSchema)),
  annotations: v.optional(v.array(AnnotationDetailResponseSchema)),
  owner: v.nullish(UserResponseSchema),
  streams: v.optional(v.array(StreamResponseSchema)),
  validations: v.optional(v.array(PhotometryPointValidationResponseSchema)),
  magsys: v.nullish(v.string()),
  mag: v.nullish(v.number()),
  magerr: v.nullish(v.number()),
  limiting_mag: v.nullish(v.number()),
  flux: v.nullish(v.number()),
  fluxerr: v.nullish(v.number()),
  zp: v.nullish(v.number()),
  ref_flux: v.nullish(v.number()),
  ref_fluxerr: v.nullish(v.number()),
  tot_flux: v.nullish(v.number()),
  tot_fluxerr: v.nullish(v.number()),
  magref: v.nullish(v.number()),
  magtot: v.nullish(v.number()),
  e_magref: v.nullish(v.number()),
  e_magtot: v.nullish(v.number()),
  extinction: v.nullish(v.number()),
  mag_corr: v.nullish(v.number()),
  flux_corr: v.nullish(v.number()),
  instrument: v.nullish(v.string()),
  telescope: v.nullish(v.string()),
  phase: v.nullish(v.number()),
});

/** A single photometry point of a source. */
export type PhotometryPointResponse = v.InferOutput<
  typeof PhotometryPointResponseSchema
>;

export const PhotometryPostSchema = v.strictObject({
  obj_id: v.union([v.string(), v.array(v.string())]),
  mjd: v.union([v.number(), v.array(v.number())]),
  instrument_id: v.union([v.number(), v.array(v.number())]),
  filter: v.union([v.string(), v.array(v.string())]),
  magsys: v.optional(v.union([v.string(), v.array(v.string())])),
  mag: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  magerr: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  limiting_mag: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  limiting_mag_nsigma: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  magref: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  e_magref: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  flux: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  fluxerr: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  zp: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ref_flux: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ref_fluxerr: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ref_zp: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ra: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  dec: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ra_unc: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  dec_unc: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  origin: v.optional(
    v.union([v.string(), v.array(v.nullable(v.string())), v.null()]),
  ),
  assignment_id: v.nullish(v.number()),
  altdata: v.optional(
    v.union([
      v.record(v.string(), v.unknown()),
      v.array(v.nullable(v.record(v.string(), v.unknown()))),
      v.null(),
    ]),
  ),
  extinction_corrected: v.nullish(v.boolean()),
  group_ids: v.optional(
    v.union([v.array(v.number()), v.literal("all"), v.null()]),
  ),
  stream_ids: v.nullish(v.array(v.number())),
});

/**
 * Payload for posting one or many photometry points.
 *
 * Provide either ``mag``/``magerr`` (magnitude space) or
 * ``flux``/``fluxerr``/``zp`` (flux space). For non-detections, leave the
 * measurement fields unset and provide ``limiting_mag``. Every measurement
 * field also accepts a 1D list to upload many points at once; scalars are
 * broadcast across the lists, and a None entry inside a ``mag``/``flux``
 * list marks that point as a non-detection.
 */
export type PhotometryPost = v.InferOutput<typeof PhotometryPostSchema>;

export const PhotometryPostBodySchema = v.strictObject({
  obj_id: v.optional(
    v.union([
      v.string(),
      v.number(),
      v.array(v.union([v.string(), v.number(), v.null()])),
      v.null(),
    ]),
  ),
  mjd: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  instrument_id: v.optional(
    v.union([
      v.number(),
      v.string(),
      v.array(v.union([v.number(), v.string(), v.null()])),
      v.null(),
    ]),
  ),
  filter: v.optional(
    v.union([v.string(), v.array(v.nullable(v.string())), v.null()]),
  ),
  magsys: v.optional(
    v.union([v.string(), v.array(v.nullable(v.string())), v.null()]),
  ),
  assignment_id: v.nullish(v.number()),
  ra: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  dec: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ra_unc: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  dec_unc: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  origin: v.optional(
    v.union([v.string(), v.array(v.nullable(v.string())), v.null()]),
  ),
  group_ids: v.optional(v.union([v.array(v.unknown()), v.string(), v.null()])),
  stream_ids: v.nullish(v.array(v.unknown())),
  altdata: v.optional(
    v.union([
      v.record(v.string(), v.unknown()),
      v.array(v.unknown()),
      v.null(),
    ]),
  ),
  extinction_corrected: v.optional(
    v.union([v.boolean(), v.string(), v.null()]),
  ),
  flux: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  fluxerr: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  zp: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ref_flux: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ref_fluxerr: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ref_zp: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  mag: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  magerr: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  limiting_mag: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  limiting_mag_nsigma: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  magref: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  e_magref: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
});

/** Request body for uploading photometry (POST). */
export type PhotometryPostBody = v.InferOutput<typeof PhotometryPostBodySchema>;

export const PhotometryPostQuerySchema = v.strictObject({
  refresh: v.optional(v.boolean()),
});

/** Query parameters for uploading photometry. */
export type PhotometryPostQuery = v.InferOutput<
  typeof PhotometryPostQuerySchema
>;

export const PhotometryPostResponseSchema = v.object({
  ids: v.array(v.number()),
  upload_id: v.string(),
});

/** Data payload returned when uploading photometry (POST). */
export type PhotometryPostResponse = v.InferOutput<
  typeof PhotometryPostResponseSchema
>;

export const PhotometryPutBodySchema = v.strictObject({
  obj_id: v.optional(
    v.union([
      v.string(),
      v.number(),
      v.array(v.union([v.string(), v.number(), v.null()])),
      v.null(),
    ]),
  ),
  mjd: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  instrument_id: v.optional(
    v.union([
      v.number(),
      v.string(),
      v.array(v.union([v.number(), v.string(), v.null()])),
      v.null(),
    ]),
  ),
  filter: v.optional(
    v.union([v.string(), v.array(v.nullable(v.string())), v.null()]),
  ),
  magsys: v.optional(
    v.union([v.string(), v.array(v.nullable(v.string())), v.null()]),
  ),
  assignment_id: v.nullish(v.number()),
  ra: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  dec: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ra_unc: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  dec_unc: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  origin: v.optional(
    v.union([v.string(), v.array(v.nullable(v.string())), v.null()]),
  ),
  group_ids: v.optional(v.union([v.array(v.unknown()), v.string(), v.null()])),
  stream_ids: v.nullish(v.array(v.unknown())),
  altdata: v.optional(
    v.union([
      v.record(v.string(), v.unknown()),
      v.array(v.unknown()),
      v.null(),
    ]),
  ),
  extinction_corrected: v.optional(
    v.union([v.boolean(), v.string(), v.null()]),
  ),
  flux: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  fluxerr: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  zp: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ref_flux: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ref_fluxerr: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  ref_zp: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  mag: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  magerr: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  limiting_mag: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  limiting_mag_nsigma: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  magref: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
  e_magref: v.optional(
    v.union([v.number(), v.array(v.nullable(v.number())), v.null()]),
  ),
});

/** Request body for updating and/or uploading photometry (PUT). */
export type PhotometryPutBody = v.InferOutput<typeof PhotometryPutBodySchema>;

export const PhotometryPutQuerySchema = v.strictObject({
  refresh: v.optional(v.boolean()),
  duplicate_ignore_flux: v.optional(v.boolean()),
  overwrite_flux: v.optional(v.boolean()),
  overwrite_altdata: v.optional(v.boolean()),
});

/** Query parameters for updating and/or uploading photometry. */
export type PhotometryPutQuery = v.InferOutput<typeof PhotometryPutQuerySchema>;

export const PhotometryPutResponseSchema = v.object({
  ids: v.array(v.number()),
});

/** Data payload returned when updating and/or uploading photometry (PUT). */
export type PhotometryPutResponse = v.InferOutput<
  typeof PhotometryPutResponseSchema
>;

export const PhotometryRangeGetQuerySchema = v.strictObject({
  format: v.optional(v.picklist(["mag", "flux"])),
  magsys: v.optional(
    v.picklist(["jla1", "ab", "vega", "bd17", "csp", "ab-b12"]),
  ),
});

/** Query parameters for getting photometry over a date range. */
export type PhotometryRangeGetQuery = v.InferOutput<
  typeof PhotometryRangeGetQuerySchema
>;

export const PhotometryRangePointResponseSchema = v.strictObject({
  id: v.number(),
  obj_id: v.nullish(v.string()),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_unc: v.nullish(v.number()),
  dec_unc: v.nullish(v.number()),
  filter: v.nullish(v.string()),
  mjd: v.nullish(v.number()),
  snr: v.nullish(v.number()),
  instrument_id: v.nullish(v.number()),
  instrument_name: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  altdata: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  created_at: v.nullish(v.string()),
  groups: v.optional(v.array(GroupResponseSchema)),
  annotations: v.optional(v.array(AnnotationDetailResponseSchema)),
  owner: v.nullish(UserResponseSchema),
  streams: v.optional(v.array(StreamResponseSchema)),
  validations: v.optional(v.array(PhotometryPointValidationResponseSchema)),
  magsys: v.nullish(v.string()),
  mag: v.nullish(v.number()),
  magerr: v.nullish(v.number()),
  limiting_mag: v.nullish(v.number()),
  flux: v.nullish(v.number()),
  fluxerr: v.nullish(v.number()),
  zp: v.nullish(v.number()),
  ref_flux: v.nullish(v.number()),
  ref_fluxerr: v.nullish(v.number()),
  tot_flux: v.nullish(v.number()),
  tot_fluxerr: v.nullish(v.number()),
  magref: v.nullish(v.number()),
  magtot: v.nullish(v.number()),
  e_magref: v.nullish(v.number()),
  e_magtot: v.nullish(v.number()),
  extinction: v.nullish(v.number()),
  mag_corr: v.nullish(v.number()),
  flux_corr: v.nullish(v.number()),
});

/** A photometry point as serialized by the date-range query. */
export type PhotometryRangePointResponse = v.InferOutput<
  typeof PhotometryRangePointResponseSchema
>;

export const PhotometryUpdateSchema = v.strictObject({
  obj_id: v.nullish(v.string()),
  mjd: v.nullish(v.number()),
  instrument_id: v.nullish(v.number()),
  filter: v.nullish(v.string()),
  magsys: v.nullish(v.string()),
  mag: v.nullish(v.number()),
  magerr: v.nullish(v.number()),
  limiting_mag: v.nullish(v.number()),
  magref: v.nullish(v.number()),
  e_magref: v.nullish(v.number()),
  flux: v.nullish(v.number()),
  fluxerr: v.nullish(v.number()),
  zp: v.nullish(v.number()),
  ref_flux: v.nullish(v.number()),
  ref_fluxerr: v.nullish(v.number()),
  ref_zp: v.nullish(v.number()),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_unc: v.nullish(v.number()),
  dec_unc: v.nullish(v.number()),
  origin: v.nullish(v.string()),
  alert_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  group_ids: v.nullish(v.array(v.number())),
  stream_ids: v.nullish(v.array(v.number())),
});

/**
 * Payload for updating an existing photometry point.
 *
 * Every field is optional: the server loads the point, applies the given
 * fields, and re-validates the result as either a flux-space
 * (``flux``/``fluxerr``/``zp``) or magnitude-space (``mag``/``magerr``)
 * measurement. Only the fields explicitly set on the payload are sent, so
 * passing ``None`` explicitly (e.g. ``mag=None, magerr=None`` to turn a
 * detection into a non-detection) sends a null, while omitting a field
 * leaves it unchanged.
 */
export type PhotometryUpdate = v.InferOutput<typeof PhotometryUpdateSchema>;

export const PhotometryValidationResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when validating/rejecting a photometry point. */
export type PhotometryValidationResponse = v.InferOutput<
  typeof PhotometryValidationResponseSchema
>;

export const _SerializedPhotometryResponseSchema = v.strictObject({
  id: v.number(),
  obj_id: v.nullish(v.string()),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_unc: v.nullish(v.number()),
  dec_unc: v.nullish(v.number()),
  filter: v.nullish(v.string()),
  mjd: v.nullish(v.number()),
  snr: v.nullish(v.number()),
  instrument_id: v.nullish(v.number()),
  instrument_name: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  altdata: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  created_at: v.nullish(v.string()),
  groups: v.optional(v.array(GroupResponseSchema)),
  annotations: v.optional(v.array(AnnotationDetailResponseSchema)),
  owner: v.nullish(UserResponseSchema),
  streams: v.optional(v.array(StreamResponseSchema)),
  validations: v.optional(v.array(PhotometryPointValidationResponseSchema)),
  magsys: v.nullish(v.string()),
  mag: v.nullish(v.number()),
  magerr: v.nullish(v.number()),
  limiting_mag: v.nullish(v.number()),
  flux: v.nullish(v.number()),
  fluxerr: v.nullish(v.number()),
  zp: v.nullish(v.number()),
  ref_flux: v.nullish(v.number()),
  ref_fluxerr: v.nullish(v.number()),
  tot_flux: v.nullish(v.number()),
  tot_fluxerr: v.nullish(v.number()),
  magref: v.nullish(v.number()),
  magtot: v.nullish(v.number()),
  e_magref: v.nullish(v.number()),
  e_magtot: v.nullish(v.number()),
  extinction: v.nullish(v.number()),
  mag_corr: v.nullish(v.number()),
  flux_corr: v.nullish(v.number()),
});

/** A photometry point as built by the ``serialize`` helper. */
export type _SerializedPhotometryResponse = v.InferOutput<
  typeof _SerializedPhotometryResponseSchema
>;
