// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { GroupAdmissionRequestResponseSchema } from "./group_admission_requests.js";
import { StreamResponseSchema } from "./streams.js";

export const ProfilePatchSchema = v.strictObject({
  username: v.nullish(v.string()),
  first_name: v.nullish(v.string()),
  last_name: v.nullish(v.string()),
  affiliations: v.nullish(v.array(v.string())),
  contact_email: v.nullish(v.string()),
  contact_phone: v.nullish(v.string()),
  bio: v.nullish(v.string()),
  is_bot: v.nullish(v.boolean()),
  preferences: v.nullish(v.record(v.string(), v.unknown())),
});

/** Payload for updating the token user's profile and preferences. */
export type ProfilePatch = v.InferOutput<typeof ProfilePatchSchema>;

export const ProfilePatchBodySchema = v.strictObject({
  username: v.nullish(v.string()),
  first_name: v.nullish(v.string()),
  last_name: v.nullish(v.string()),
  affiliations: v.nullish(v.array(v.string())),
  contact_email: v.nullish(v.string()),
  contact_phone: v.nullish(v.string()),
  bio: v.nullish(v.string()),
  is_bot: v.nullish(v.boolean()),
  preferences: v.nullish(v.record(v.string(), v.unknown())),
});

/** Request body for updating a user's profile and preferences. */
export type ProfilePatchBody = v.InferOutput<typeof ProfilePatchBodySchema>;

export const ProfileTokenResponseSchema = v.strictObject({
  id: v.nullish(v.string()),
  name: v.nullish(v.string()),
  acls: v.optional(v.array(v.string())),
  created_at: v.nullish(v.string()),
});

/** An API token of the profile's user (baselayer ``Token``). */
export type ProfileTokenResponse = v.InferOutput<
  typeof ProfileTokenResponseSchema
>;

export const UserProfileResponseSchema = v.strictObject({
  id: v.nullish(v.number()),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  username: v.string(),
  first_name: v.nullish(v.string()),
  last_name: v.nullish(v.string()),
  bio: v.nullish(v.string()),
  affiliations: v.optional(v.array(v.string())),
  contact_email: v.nullish(v.string()),
  contact_phone: v.nullish(v.string()),
  oauth_uid: v.nullish(v.string()),
  is_bot: v.nullish(v.boolean()),
  expiration_date: v.nullish(v.string()),
  roles: v.optional(v.array(v.string())),
  permissions: v.optional(v.array(v.string())),
  acls: v.optional(v.array(v.string())),
  tokens: v.optional(v.array(ProfileTokenResponseSchema)),
  preferences: v.optional(v.record(v.string(), v.unknown())),
  gravatar_url: v.nullish(v.string()),
  groupAdmissionRequests: v.optional(
    v.array(GroupAdmissionRequestResponseSchema),
  ),
  streams: v.optional(v.array(StreamResponseSchema)),
  is_anonymous: v.nullish(v.boolean()),
});

/** The user associated with the API token (baselayer ``User``). */
export type UserProfileResponse = v.InferOutput<
  typeof UserProfileResponseSchema
>;
