// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { GroupResponseSchema } from "./_cyclic.js";

export const PublicReleasePatchBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  group_ids: v.nullish(v.array(v.number())),
  description: v.optional(v.string()),
  is_visible: v.optional(v.boolean()),
  auto_publish_enabled: v.optional(v.boolean()),
  options: v.optional(v.record(v.string(), v.unknown())),
});

/** Request body for updating a public release. */
export type PublicReleasePatchBody = v.InferOutput<
  typeof PublicReleasePatchBodySchema
>;

export const PublicReleasePostSchema = v.strictObject({
  name: v.string(),
  link_name: v.string(),
  group_ids: v.array(v.number()),
  description: v.nullish(v.string()),
  options: v.nullish(v.record(v.string(), v.unknown())),
  is_visible: v.nullish(v.boolean()),
  auto_publish_enabled: v.nullish(v.boolean()),
});

/** Payload for creating a public release. */
export type PublicReleasePost = v.InferOutput<typeof PublicReleasePostSchema>;

export const PublicReleasePostBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  link_name: v.nullish(v.string()),
  group_ids: v.nullish(v.array(v.number())),
  description: v.optional(v.string()),
  is_visible: v.optional(v.boolean()),
  auto_publish_enabled: v.optional(v.boolean()),
  options: v.optional(v.record(v.string(), v.unknown())),
});

/** Request body for creating a public release. */
export type PublicReleasePostBody = v.InferOutput<
  typeof PublicReleasePostBodySchema
>;

export const PublicReleasePostResponseSchema = v.object({
  id: v.number(),
});

/** ID of the newly created public release. */
export type PublicReleasePostResponse = v.InferOutput<
  typeof PublicReleasePostResponseSchema
>;

export const PublicSourcePageOptionsResponseSchema = v.strictObject({
  photometry: v.nullish(v.picklist(["public", "private", "no data"])),
  classifications: v.nullish(v.picklist(["public", "private", "no data"])),
  spectroscopy: v.nullish(v.picklist(["public", "private", "no data"])),
  summary: v.nullish(v.picklist(["public", "private", "no data"])),
});

/** Visibility state of each data section of a public source page. */
export type PublicSourcePageOptionsResponse = v.InferOutput<
  typeof PublicSourcePageOptionsResponseSchema
>;

export const PublicSourcePageResponseSchema = v.strictObject({
  id: v.number(),
  source_id: v.nullish(v.string()),
  release_link_name: v.nullish(v.string()),
  is_visible: v.nullish(v.boolean()),
  created_at: v.nullish(v.string()),
  hash: v.nullish(v.string()),
  options: v.nullish(PublicSourcePageOptionsResponseSchema),
});

/**
 * A published snapshot of a source (``PublicSourcePage``).
 *
 * ``PublicSourcePage.to_dict`` returns exactly these keys, so the ``data``,
 * ``is_auto_published`` and ``release_id`` columns and the ``release``
 * relationship never reach the client; ``release_link_name`` is derived from
 * the release instead.
 */
export type PublicSourcePageResponse = v.InferOutput<
  typeof PublicSourcePageResponseSchema
>;

export const PublicReleaseResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  name: v.nullish(v.string()),
  link_name: v.nullish(v.string()),
  description: v.nullish(v.string()),
  is_visible: v.nullish(v.boolean()),
  auto_publish_enabled: v.nullish(v.boolean()),
  options: v.nullish(v.record(v.string(), v.unknown())),
  group_ids: v.optional(v.array(v.number())),
  groups: v.nullish(v.array(GroupResponseSchema)),
  source_pages: v.nullish(v.array(PublicSourcePageResponseSchema)),
});

/**
 * A public release of source pages (``PublicRelease``).
 *
 * ``group_ids`` is injected by the handler and lists only the owning groups
 * the calling user can access; ``groups`` and ``source_pages`` are
 * relationships that only appear when a handler eager-loads them.
 */
export type PublicReleaseResponse = v.InferOutput<
  typeof PublicReleaseResponseSchema
>;

export const PublicReleaseUpdateSchema = v.strictObject({
  name: v.string(),
  group_ids: v.array(v.number()),
  description: v.nullish(v.string()),
  options: v.nullish(v.record(v.string(), v.unknown())),
  is_visible: v.nullish(v.boolean()),
  auto_publish_enabled: v.nullish(v.boolean()),
});

/** Payload for updating a public release. */
export type PublicReleaseUpdate = v.InferOutput<
  typeof PublicReleaseUpdateSchema
>;

export const PublicSourcePagePostBodySchema = v.strictObject({
  options: v.nullish(v.record(v.string(), v.unknown())),
  release_id: v.optional(v.unknown()),
});

/** Request body for creating a public page for a source. */
export type PublicSourcePagePostBody = v.InferOutput<
  typeof PublicSourcePagePostBodySchema
>;

export const PublicSourcePagePostResponseSchema = v.object({
  id: v.number(),
});

/** ID of the newly created public source page. */
export type PublicSourcePagePostResponse = v.InferOutput<
  typeof PublicSourcePagePostResponseSchema
>;
