// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { UserResponseSchema } from "./_cyclic.js";

export const RecurringAPIPostSchema = v.strictObject({
  endpoint: v.string(),
  method: v.string(),
  next_call: v.string(),
  call_delay: v.number(),
  payload: v.string(),
  number_of_retries: v.nullish(v.number()),
});

/** Payload for scheduling a recurring API call. */
export type RecurringAPIPost = v.InferOutput<typeof RecurringAPIPostSchema>;

export const RecurringAPIPostBodySchema = v.strictObject({
  endpoint: v.string(),
  method: v.string(),
  next_call: v.string(),
  call_delay: v.number(),
  payload: v.string(),
  number_of_retries: v.nullish(v.number()),
});

/** Request body for creating a recurring API. */
export type RecurringAPIPostBody = v.InferOutput<
  typeof RecurringAPIPostBodySchema
>;

export const RecurringAPIPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating a recurring API. */
export type RecurringAPIPostResponse = v.InferOutput<
  typeof RecurringAPIPostResponseSchema
>;

export const RecurringAPIResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  endpoint: v.nullish(v.string()),
  method: v.nullish(v.string()),
  payload: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  next_call: v.nullish(v.string()),
  call_delay: v.nullish(v.number()),
  number_of_retries: v.nullish(v.number()),
  active: v.nullish(v.boolean()),
  owner_id: v.nullish(v.number()),
  owner: v.nullish(UserResponseSchema),
});

/**
 * A recurring API call scheduled by a user.
 *
 * ``owner`` is always loaded. The multiple-object endpoint decodes
 * ``payload`` from its stored JSON string, while the single-object one
 * returns it exactly as stored.
 */
export type RecurringAPIResponse = v.InferOutput<
  typeof RecurringAPIResponseSchema
>;
