// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { ReminderResponseSchema } from "./_cyclic.js";

export const ReminderPatchBodySchema = v.strictObject({
  text: v.nullish(v.string()),
  next_reminder: v.nullish(v.string()),
  reminder_delay: v.nullish(v.number()),
  number_of_reminders: v.nullish(v.number()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for updating a reminder. */
export type ReminderPatchBody = v.InferOutput<typeof ReminderPatchBodySchema>;

export const ReminderPostSchema = v.strictObject({
  text: v.string(),
  next_reminder: v.string(),
  reminder_delay: v.nullish(v.number()),
  number_of_reminders: v.nullish(v.number()),
  group_ids: v.nullish(v.array(v.number())),
  user_ids: v.nullish(v.array(v.number())),
});

/** Payload for creating reminders on a resource. */
export type ReminderPost = v.InferOutput<typeof ReminderPostSchema>;

export const ReminderPostBodySchema = v.strictObject({
  text: v.string(),
  next_reminder: v.string(),
  reminder_delay: v.optional(v.number()),
  number_of_reminders: v.optional(v.number()),
  group_ids: v.nullish(v.array(v.number())),
  user_ids: v.nullish(v.array(v.number())),
});

/** Request body for creating reminder(s). */
export type ReminderPostBody = v.InferOutput<typeof ReminderPostBodySchema>;

export const ReminderPostResponseSchema = v.object({
  reminder_ids: v.array(v.number()),
});

/** IDs of the newly created reminders. */
export type ReminderPostResponse = v.InferOutput<
  typeof ReminderPostResponseSchema
>;

export const ReminderUpdateSchema = v.strictObject({
  text: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  bot: v.nullish(v.boolean()),
  next_reminder: v.nullish(v.string()),
  reminder_delay: v.nullish(v.number()),
  number_of_reminders: v.nullish(v.number()),
  group_ids: v.nullish(v.array(v.number())),
  user_ids: v.nullish(v.array(v.number())),
});

/** Payload for updating an existing reminder. */
export type ReminderUpdate = v.InferOutput<typeof ReminderUpdateSchema>;

export const RemindersResponseSchema = v.strictObject({
  resourceId: v.string(),
  resourceType: v.string(),
  reminders: v.optional(v.array(ReminderResponseSchema)),
});

/** All reminders attached to one resource. */
export type RemindersResponse = v.InferOutput<typeof RemindersResponseSchema>;
