// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const RoleResponseSchema = v.strictObject({
  id: v.string(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  acls: v.optional(v.array(v.string())),
});

/** A named collection of ACLs (the baselayer ``Role`` model). */
export type RoleResponse = v.InferOutput<typeof RoleResponseSchema>;

export const UserRolePostBodySchema = v.strictObject({
  roleIds: v.array(v.string()),
});

/** Request body for granting roles to a user. */
export type UserRolePostBody = v.InferOutput<typeof UserRolePostBodySchema>;
