// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const ScoutEphemerisRowResponseSchema = v.strictObject({
  time: v.nullish(v.string()),
  ra: v.number(),
  dec: v.number(),
  sigma_pos_arcmin: v.nullish(v.number()),
  vmag: v.nullish(v.number()),
  rate_arcsec_per_min: v.nullish(v.number()),
  position_angle: v.nullish(v.number()),
  ra_sigma_limits: v.nullish(v.record(v.string(), v.string())),
  dec_sigma_limits: v.nullish(v.record(v.string(), v.string())),
});

/**
 * One ephemeris row from JPL Scout.
 *
 * ``time`` is Scout's raw ``YYYY-MM-DD HH:MM:SS`` string, and the two
 * ``*_sigma_limits`` dicts are passed through verbatim, with their
 * ``min``/``max`` values still strings.
 */
export type ScoutEphemerisRowResponse = v.InferOutput<
  typeof ScoutEphemerisRowResponseSchema
>;

export const ScoutEphemerisResponseSchema = v.strictObject({
  obj_id: v.string(),
  tdes: v.string(),
  obs_code: v.string(),
  step_minutes: v.number(),
  hours: v.number(),
  count: v.number(),
  ephemeris: v.optional(v.array(ScoutEphemerisRowResponseSchema)),
});

/**
 * A Scout ephemeris for an unconfirmed solar-system candidate.
 *
 * ``hours`` may come back shorter than requested when the window was
 * clamped; ``ephemeris`` is never empty on the success path.
 */
export type ScoutEphemerisResponse = v.InferOutput<
  typeof ScoutEphemerisResponseSchema
>;
