// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const SharingPostBodySchema = v.strictObject({
  groupIDs: v.array(v.number()),
  photometryIDs: v.nullish(v.array(v.number())),
  spectrumIDs: v.nullish(v.array(v.number())),
});

/** Request body for sharing data with additional groups/users. */
export type SharingPostBody = v.InferOutput<typeof SharingPostBodySchema>;
