// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { InstrumentResponseSchema } from "./_cyclic.js";
import { SourceResponseSchema } from "./sources.js";
import { StreamResponseSchema } from "./streams.js";

export const PhotometryOptionsSchema = v.strictObject({
  first_and_last_detections: v.nullish(v.boolean()),
  auto_sharing_allow_archival: v.nullish(v.boolean()),
});

/**
 * Which photometry a sharing service publishes (upstream ``PHOTOMETRY_OPTIONS``).
 *
 * The server fills in every option it knows about, defaulting each to true,
 * so a stored value always carries the full set.
 */
export type PhotometryOptions = v.InferOutput<typeof PhotometryOptionsSchema>;

export const PhotometryOptionsResponseSchema = v.strictObject({
  first_and_last_detections: v.nullish(v.boolean()),
  auto_sharing_allow_archival: v.nullish(v.boolean()),
});

/**
 * Which photometry a sharing service publishes (``PHOTOMETRY_OPTIONS``).
 *
 * The server fills in every option it knows about, defaulting each to true,
 * so a stored value always carries the full set.
 */
export type PhotometryOptionsResponse = v.InferOutput<
  typeof PhotometryOptionsResponseSchema
>;

export const SharingServiceAutoPublishersPostResponseSchema = v.strictObject({
  ids: v.optional(v.array(v.number())),
});

/** Result of adding auto-publishers to a sharing service group. */
export type SharingServiceAutoPublishersPostResponse = v.InferOutput<
  typeof SharingServiceAutoPublishersPostResponseSchema
>;

export const SharingServiceCoauthorPatchBodySchema = v.strictObject({
  user_ids: v.array(v.number()),
});

/** Request body for reordering the coauthors of an external sharing service. */
export type SharingServiceCoauthorPatchBody = v.InferOutput<
  typeof SharingServiceCoauthorPatchBodySchema
>;

export const SharingServiceCoauthorPostBodySchema = v.strictObject({
  user_id: v.nullish(v.number()),
});

/** Request body for adding a coauthor to an external sharing service. */
export type SharingServiceCoauthorPostBody = v.InferOutput<
  typeof SharingServiceCoauthorPostBodySchema
>;

export const SharingServiceCoauthorPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when adding a coauthor. */
export type SharingServiceCoauthorPostResponse = v.InferOutput<
  typeof SharingServiceCoauthorPostResponseSchema
>;

export const SharingServiceCoauthorResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sharing_service_id: v.nullish(v.number()),
  user_id: v.nullish(v.number()),
});

/** A coauthor of a service's submissions (``SharingServiceCoauthor``). */
export type SharingServiceCoauthorResponse = v.InferOutput<
  typeof SharingServiceCoauthorResponseSchema
>;

export const SharingServiceGroupAutoPublisherDeleteBodySchema = v.strictObject({
  user_id: v.nullish(v.number()),
  user_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
});

/** Request body for removing auto_publisher(s) from a SharingServiceGroup. */
export type SharingServiceGroupAutoPublisherDeleteBody = v.InferOutput<
  typeof SharingServiceGroupAutoPublisherDeleteBodySchema
>;

export const SharingServiceGroupAutoPublisherPostBodySchema = v.strictObject({
  user_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
  user_id: v.nullish(v.number()),
});

/** Request body for adding auto_publisher(s) to a SharingServiceGroup. */
export type SharingServiceGroupAutoPublisherPostBody = v.InferOutput<
  typeof SharingServiceGroupAutoPublisherPostBodySchema
>;

export const SharingServiceGroupAutoPublisherPostResponseSchema = v.object({
  ids: v.array(v.number()),
});

/** Data payload returned when adding auto_publisher(s). */
export type SharingServiceGroupAutoPublisherPostResponse = v.InferOutput<
  typeof SharingServiceGroupAutoPublisherPostResponseSchema
>;

export const SharingServiceGroupAutoPublisherResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sharing_service_group_id: v.nullish(v.number()),
  group_user_id: v.nullish(v.number()),
  user_id: v.nullish(v.number()),
});

/**
 * An auto-publisher (``SharingServiceGroupAutoPublisher``).
 *
 * ``user_id`` is a column property derived from ``group_user_id`` rather
 * than a stored column.
 */
export type SharingServiceGroupAutoPublisherResponse = v.InferOutput<
  typeof SharingServiceGroupAutoPublisherResponseSchema
>;

export const SharingServiceGroupPutBodySchema = v.strictObject({
  group_id: v.nullish(v.number()),
  auto_share_to_tns: v.optional(v.union([v.boolean(), v.string(), v.null()])),
  auto_share_to_hermes: v.optional(
    v.union([v.boolean(), v.string(), v.null()]),
  ),
  auto_sharing_allow_bots: v.optional(
    v.union([v.boolean(), v.string(), v.null()]),
  ),
  owner: v.optional(v.union([v.boolean(), v.string(), v.null()])),
});

/** Request body for adding or editing a group of an external sharing service. */
export type SharingServiceGroupPutBody = v.InferOutput<
  typeof SharingServiceGroupPutBodySchema
>;

export const SharingServiceGroupPutResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when adding or editing a sharing service group. */
export type SharingServiceGroupPutResponse = v.InferOutput<
  typeof SharingServiceGroupPutResponseSchema
>;

export const SharingServiceGroupResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sharing_service_id: v.nullish(v.number()),
  group_id: v.nullish(v.number()),
  owner: v.nullish(v.boolean()),
  auto_share_to_tns: v.nullish(v.boolean()),
  auto_share_to_hermes: v.nullish(v.boolean()),
  auto_sharing_allow_bots: v.nullish(v.boolean()),
  auto_publishers: v.optional(
    v.array(SharingServiceGroupAutoPublisherResponseSchema),
  ),
});

/**
 * A group's access to a service (``SharingServiceGroup``).
 *
 * The ``group`` and ``sharing_service`` relationships are never eager-loaded
 * by the endpoints, so they never appear and are not declared.
 */
export type SharingServiceGroupResponse = v.InferOutput<
  typeof SharingServiceGroupResponseSchema
>;

export const SharingServicePostSchema = v.strictObject({
  name: v.string(),
  owner_group_ids: v.nullish(v.array(v.number())),
  instrument_ids: v.nullish(v.array(v.number())),
  stream_ids: v.nullish(v.array(v.number())),
  acknowledgments: v.nullish(v.string()),
  testing: v.nullish(v.boolean()),
  photometry_options: v.nullish(PhotometryOptionsSchema),
  enable_sharing_with_tns: v.nullish(v.boolean()),
  enable_sharing_with_hermes: v.nullish(v.boolean()),
  tns_bot_name: v.nullish(v.string()),
  tns_bot_id: v.nullish(v.number()),
  tns_source_group_id: v.nullish(v.number()),
  _tns_altdata: v.nullish(v.record(v.string(), v.unknown())),
  publish_existing_tns_objects: v.nullish(v.boolean()),
});

/** Payload for creating or updating a sharing service. */
export type SharingServicePost = v.InferOutput<typeof SharingServicePostSchema>;

export const SharingServicePutBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  owner_group_ids: v.optional(
    v.union([v.array(v.number()), v.string(), v.null()]),
  ),
  instrument_ids: v.optional(
    v.union([v.array(v.number()), v.string(), v.null()]),
  ),
  stream_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
  acknowledgments: v.nullish(v.string()),
  testing: v.optional(v.union([v.boolean(), v.string(), v.null()])),
  photometry_options: v.nullish(v.record(v.string(), v.unknown())),
  enable_sharing_with_hermes: v.nullish(v.boolean()),
  enable_sharing_with_tns: v.nullish(v.boolean()),
  tns_bot_name: v.nullish(v.string()),
  tns_bot_id: v.nullish(v.number()),
  tns_source_group_id: v.nullish(v.number()),
  _tns_altdata: v.optional(
    v.union([v.record(v.string(), v.unknown()), v.string(), v.null()]),
  ),
  publish_existing_tns_objects: v.optional(
    v.union([v.boolean(), v.string(), v.null()]),
  ),
});

/**
 * Request body for creating or updating a sharing service. On update, only
 * the provided fields are changed.
 */
export type SharingServicePutBody = v.InferOutput<
  typeof SharingServicePutBodySchema
>;

export const SharingServicePutResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating or updating a sharing service. */
export type SharingServicePutResponse = v.InferOutput<
  typeof SharingServicePutResponseSchema
>;

export const SharingServiceResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  name: v.nullish(v.string()),
  acknowledgments: v.nullish(v.string()),
  testing: v.nullish(v.boolean()),
  photometry_options: v.nullish(PhotometryOptionsResponseSchema),
  enable_sharing_with_tns: v.nullish(v.boolean()),
  enable_sharing_with_hermes: v.nullish(v.boolean()),
  tns_bot_name: v.nullish(v.string()),
  tns_bot_id: v.nullish(v.number()),
  tns_source_group_id: v.nullish(v.number()),
  publish_existing_tns_objects: v.nullish(v.boolean()),
  owner_group_ids: v.optional(v.array(v.number())),
  groups: v.optional(v.array(SharingServiceGroupResponseSchema)),
  coauthors: v.optional(v.array(SharingServiceCoauthorResponseSchema)),
  instruments: v.optional(v.array(InstrumentResponseSchema)),
  streams: v.optional(v.array(StreamResponseSchema)),
});

/**
 * A service publishing objects externally (``SharingService``).
 *
 * ``owner_group_ids`` is not a column: the endpoint derives it from the
 * owning entries of ``groups`` and injects it. The encrypted TNS credentials
 * (``_tns_altdata``) are never serialized, and the ``submissions``
 * relationship is never eager-loaded, so neither is declared.
 */
export type SharingServiceResponse = v.InferOutput<
  typeof SharingServiceResponseSchema
>;

export const SharingServiceSubmissionGetQuerySchema = v.strictObject({
  sharing_service_id: v.number(),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
  include_payload: v.optional(v.boolean()),
  include_response: v.optional(v.boolean()),
  objectID: v.nullish(v.string()),
});

/** Query parameters for retrieving sharing service submissions. */
export type SharingServiceSubmissionGetQuery = v.InferOutput<
  typeof SharingServiceSubmissionGetQuerySchema
>;

export const SharingServiceSubmissionPostSchema = v.strictObject({
  obj_id: v.string(),
  sharing_service_id: v.number(),
  publishers: v.string(),
  remarks: v.nullish(v.string()),
  archival: v.nullish(v.boolean()),
  archival_comment: v.nullish(v.string()),
  instrument_ids: v.nullish(v.array(v.number())),
  stream_ids: v.nullish(v.array(v.number())),
  photometry_options: v.nullish(PhotometryOptionsSchema),
  publish_to_tns: v.nullish(v.boolean()),
  publish_to_hermes: v.nullish(v.boolean()),
});

/** Payload for requesting the publication of an object. */
export type SharingServiceSubmissionPost = v.InferOutput<
  typeof SharingServiceSubmissionPostSchema
>;

export const SharingServiceSubmissionPostBodySchema = v.strictObject({
  obj_id: v.nullish(v.string()),
  sharing_service_id: v.nullish(v.number()),
  publishers: v.nullish(v.string()),
  remarks: v.nullish(v.string()),
  archival: v.nullish(v.boolean()),
  archival_comment: v.nullish(v.string()),
  instrument_ids: v.nullish(v.array(v.number())),
  stream_ids: v.nullish(v.array(v.number())),
  photometry_options: v.nullish(v.record(v.string(), v.unknown())),
  publish_to_tns: v.nullish(v.boolean()),
  publish_to_hermes: v.nullish(v.boolean()),
});

/** Request body for publishing an Obj to TNS or Hermes via a sharing service. */
export type SharingServiceSubmissionPostBody = v.InferOutput<
  typeof SharingServiceSubmissionPostBodySchema
>;

export const SharingServiceSubmissionResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  sharing_service_id: v.nullish(v.number()),
  obj_id: v.nullish(v.string()),
  obj: v.nullish(SourceResponseSchema),
  tns_name: v.nullish(v.string()),
  user_id: v.nullish(v.number()),
  custom_publishing_string: v.nullish(v.string()),
  custom_remarks_string: v.nullish(v.string()),
  publish_to_tns: v.nullish(v.boolean()),
  tns_status: v.nullish(v.string()),
  tns_submission_id: v.nullish(v.number()),
  tns_payload: v.nullish(v.record(v.string(), v.unknown())),
  tns_response: v.nullish(v.record(v.string(), v.unknown())),
  publish_to_hermes: v.nullish(v.boolean()),
  hermes_status: v.nullish(v.string()),
  hermes_response: v.nullish(v.record(v.string(), v.unknown())),
  archival: v.nullish(v.boolean()),
  archival_comment: v.nullish(v.string()),
  auto_submission: v.nullish(v.boolean()),
  instrument_ids: v.nullish(v.array(v.number())),
  stream_ids: v.nullish(v.array(v.number())),
  photometry_options: v.nullish(PhotometryOptionsResponseSchema),
});

/**
 * A publication request (``SharingServiceSubmission``).
 *
 * ``tns_name`` is not a column: the endpoint copies it off the submitted
 * object. ``tns_payload``, ``tns_response`` and ``hermes_response`` are
 * deferred and only appear when explicitly requested. The ``user`` and
 * ``sharing_service`` relationships are never eager-loaded, so they are
 * not declared.
 */
export type SharingServiceSubmissionResponse = v.InferOutput<
  typeof SharingServiceSubmissionResponseSchema
>;

export const SharingServiceSubmissionsPageResponseSchema = v.strictObject({
  sharing_service_id: v.nullish(v.number()),
  submissions: v.optional(v.array(SharingServiceSubmissionResponseSchema)),
  totalMatches: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/** One page of results from a sharing service submissions query. */
export type SharingServiceSubmissionsPageResponse = v.InferOutput<
  typeof SharingServiceSubmissionsPageResponseSchema
>;
