// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { GroupResponseSchema, UserResponseSchema } from "./_cyclic.js";

export const ShiftCommentResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  text: v.nullish(v.string()),
  attachment_name: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  bot: v.nullish(v.boolean()),
  author_id: v.nullish(v.number()),
  shift_id: v.nullish(v.number()),
  author: v.nullish(UserResponseSchema),
  groups: v.optional(v.array(GroupResponseSchema)),
  resourceType: v.nullish(v.string()),
});

/**
 * A comment posted about a shift (the ``CommentOnShift`` model).
 *
 * The handler strips ``attachment_bytes`` and tags each comment with
 * ``resourceType``.
 */
export type ShiftCommentResponse = v.InferOutput<
  typeof ShiftCommentResponseSchema
>;

export const ShiftGetQuerySchema = v.strictObject({
  group_id: v.nullish(v.number()),
  start_date_limit: v.nullish(v.string()),
  end_date_limit: v.nullish(v.string()),
});

/** Query parameters for retrieving shifts. */
export type ShiftGetQuery = v.InferOutput<typeof ShiftGetQuerySchema>;

export const ShiftGroupMemberResponseSchema = v.strictObject({
  id: v.number(),
  username: v.nullish(v.string()),
  first_name: v.nullish(v.string()),
  last_name: v.nullish(v.string()),
  expiration_date: v.nullish(v.string()),
});

/** A member of a shift's group, as returned alongside a single shift. */
export type ShiftGroupMemberResponse = v.InferOutput<
  typeof ShiftGroupMemberResponseSchema
>;

export const ShiftGroupResponseSchema = v.strictObject({
  id: v.number(),
  name: v.nullish(v.string()),
  has_admin_access: v.nullish(v.boolean()),
  group_users: v.optional(v.array(ShiftGroupMemberResponseSchema)),
});

/** A shift's group, as hand-assembled by the single-shift handler. */
export type ShiftGroupResponse = v.InferOutput<typeof ShiftGroupResponseSchema>;

export const ShiftPatchBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  description: v.nullish(v.string()),
  required_users_number: v.nullish(v.number()),
});

/** Request body for updating a shift. */
export type ShiftPatchBody = v.InferOutput<typeof ShiftPatchBodySchema>;

export const ShiftPostSchema = v.strictObject({
  name: v.string(),
  start_date: v.string(),
  end_date: v.string(),
  group_id: v.number(),
  description: v.nullish(v.string()),
  required_users_number: v.nullish(v.number()),
  shift_admins: v.nullish(v.array(v.number())),
});

/** Payload for creating a new shift. */
export type ShiftPost = v.InferOutput<typeof ShiftPostSchema>;

export const ShiftPostBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  group_id: v.number(),
  start_date: v.string(),
  end_date: v.string(),
  description: v.nullish(v.string()),
  required_users_number: v.nullish(v.number()),
  shift_admins: v.nullish(v.array(v.number())),
});

/** Request body for creating a shift. */
export type ShiftPostBody = v.InferOutput<typeof ShiftPostBodySchema>;

export const ShiftPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating a shift. */
export type ShiftPostResponse = v.InferOutput<typeof ShiftPostResponseSchema>;

export const ShiftUserMembershipResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  shift_id: v.nullish(v.number()),
  user_id: v.nullish(v.number()),
  admin: v.nullish(v.boolean()),
  needs_replacement: v.nullish(v.boolean()),
  user: v.nullish(UserResponseSchema),
  username: v.nullish(v.string()),
  first_name: v.nullish(v.string()),
  last_name: v.nullish(v.string()),
});

/**
 * A user's membership in a shift (the ``ShiftUser`` join model).
 *
 * ``username``, ``first_name`` and ``last_name`` are copied up from the
 * nested ``user`` by the single-shift handler.
 */
export type ShiftUserMembershipResponse = v.InferOutput<
  typeof ShiftUserMembershipResponseSchema
>;

export const ShiftResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  name: v.nullish(v.string()),
  description: v.nullish(v.string()),
  start_date: v.string(),
  end_date: v.string(),
  group_id: v.number(),
  required_users_number: v.nullish(v.number()),
  shift_users_ids: v.nullish(v.array(v.number())),
  shift_users: v.optional(v.array(ShiftUserMembershipResponseSchema)),
  users: v.optional(v.array(UserResponseSchema)),
  comments: v.optional(v.array(ShiftCommentResponseSchema)),
  reminders: v.optional(v.array(v.record(v.string(), v.unknown()))),
  group: v.nullish(ShiftGroupResponseSchema),
});

/**
 * A group scanning shift.
 *
 * ``shift_users_ids`` is a column property (an aggregate of the shift's
 * user IDs), so it is present even when no relationship is loaded.
 */
export type ShiftResponse = v.InferOutput<typeof ShiftResponseSchema>;

export const ShiftSummaryGetQuerySchema = v.strictObject({
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
});

/** Query parameters for summarizing shift activity. */
export type ShiftSummaryGetQuery = v.InferOutput<
  typeof ShiftSummaryGetQuerySchema
>;

export const ShiftSummarySectionResponseSchema = v.strictObject({
  total: v.nullish(v.number()),
  data: v.optional(v.array(v.record(v.string(), v.unknown()))),
});

/** One section (shifts or GCN events) of a shift summary report. */
export type ShiftSummarySectionResponse = v.InferOutput<
  typeof ShiftSummarySectionResponseSchema
>;

export const ShiftSummaryReportResponseSchema = v.strictObject({
  shifts: v.nullish(ShiftSummarySectionResponseSchema),
  gcns: v.nullish(ShiftSummarySectionResponseSchema),
});

/** Summary of shift-user activity over a period. */
export type ShiftSummaryReportResponse = v.InferOutput<
  typeof ShiftSummaryReportResponseSchema
>;

export const ShiftUserPatchBodySchema = v.strictObject({
  admin: v.nullish(v.boolean()),
  needs_replacement: v.nullish(v.boolean()),
});

/** Request body for updating a shift user. */
export type ShiftUserPatchBody = v.InferOutput<typeof ShiftUserPatchBodySchema>;

export const ShiftUserPostBodySchema = v.strictObject({
  userID: v.number(),
  admin: v.optional(v.boolean()),
  needs_replacement: v.optional(v.boolean()),
});

/** Request body for adding a user to a shift. */
export type ShiftUserPostBody = v.InferOutput<typeof ShiftUserPostBodySchema>;

export const ShiftUserPostResponseSchema = v.object({
  shift_id: v.number(),
  user_id: v.number(),
  admin: v.boolean(),
});

/** Data payload returned when adding a user to a shift. */
export type ShiftUserPostResponse = v.InferOutput<
  typeof ShiftUserPostResponseSchema
>;
