// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const SkymapTriggerDeleteBodySchema = v.strictObject({
  trigger_name: v.nullish(v.string()),
});

/** Request body for deleting a skymap-based trigger. */
export type SkymapTriggerDeleteBody = v.InferOutput<
  typeof SkymapTriggerDeleteBodySchema
>;

export const SkymapTriggerPostBodySchema = v.strictObject({
  allocation_id: v.number(),
  localization_id: v.number(),
  integrated_probability: v.optional(v.number()),
});

/** Request body for posting a skymap-based trigger. */
export type SkymapTriggerPostBody = v.InferOutput<
  typeof SkymapTriggerPostBodySchema
>;

export const SkymapTriggerQueueResponseSchema = v.strictObject({
  trigger_names: v.optional(v.array(v.string())),
});

/**
 * The skymap-based triggers currently queued on a remote facility.
 *
 * The names come straight back from the instrument's remote observation
 * plan API, so there is no corresponding database model.
 */
export type SkymapTriggerQueueResponse = v.InferOutput<
  typeof SkymapTriggerQueueResponseSchema
>;
