// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import {
  AllocationResponseSchema,
  ClassificationResponseSchema,
  CommentResponseSchema,
  FacilityTransactionRequestResponseSchema,
  GroupMemberResponseSchema,
  GroupResponseSchema,
  GroupUserResponseSchema,
  UserResponseSchema,
} from "./_cyclic.js";
import { ObjAnalysisResponseSchema } from "./analysis.js";
import { AnnotationResponseSchema } from "./annotations.js";
import { AssignmentResponseSchema } from "./assignments.js";
import { FilterResponseSchema } from "./filters.js";
import { FollowupRequestWatcherResponseSchema } from "./followup_requests.js";
import { GalaxyResponseSchema } from "./galaxies.js";
import { PhotometryPointResponseSchema } from "./photometry.js";
import { StreamResponseSchema } from "./streams.js";
import { ObjTagResponseSchema } from "./tags.js";
import { ThumbnailResponseSchema } from "./thumbnails.js";

export const FinderChartFacilityResponseSchema = v.strictObject({
  radius_degrees: v.nullish(v.number()),
  mag_limit: v.nullish(v.number()),
  mag_min: v.nullish(v.number()),
  min_sep_arcsec: v.nullish(v.number()),
});

/** Default offset-star parameters for one finding-chart facility. */
export type FinderChartFacilityResponse = v.InferOutput<
  typeof FinderChartFacilityResponseSchema
>;

export const ObjColorMagGetQuerySchema = v.strictObject({
  catalog: v.nullish(v.string()),
  apparentMagKey: v.nullish(v.string()),
  parallaxKey: v.nullish(v.string()),
  absorptionKey: v.nullish(v.string()),
  absoluteMagKey: v.nullish(v.string()),
  blueMagKey: v.nullish(v.string()),
  redMagKey: v.nullish(v.string()),
  colorKey: v.nullish(v.string()),
});

/** Query parameters for getting the color and absolute magnitude of a source. */
export type ObjColorMagGetQuery = v.InferOutput<
  typeof ObjColorMagGetQuerySchema
>;

export const PhotStatAggregateFieldResponseSchema = v.strictObject({
  value: v.string(),
  label: v.nullish(v.string()),
});

/** A photometry-statistics field that can be plotted. */
export type PhotStatAggregateFieldResponse = v.InferOutput<
  typeof PhotStatAggregateFieldResponseSchema
>;

export const PhotStatAggregateGetQuerySchema = v.strictObject({
  xField: v.nullish(v.string()),
  yField: v.nullish(v.string()),
  zField: v.nullish(v.string()),
  classifications: v.nullish(v.string()),
  classificationProbThreshold: v.nullish(v.number()),
  group_id: v.nullish(v.number()),
  obj_ids: v.nullish(v.string()),
  maxMatches: v.optional(v.number()),
});

/** Query parameters for bulk photometry statistics. */
export type PhotStatAggregateGetQuery = v.InferOutput<
  typeof PhotStatAggregateGetQuerySchema
>;

export const PhotStatAggregatePointResponseSchema = v.strictObject({
  id: v.string(),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  redshift: v.nullish(v.number()),
  classification: v.nullish(v.string()),
  first_detected_mjd: v.nullish(v.number()),
  peak_mjd: v.nullish(v.number()),
  tns_discovery_date: v.nullish(v.string()),
  x: v.nullish(v.number()),
  y: v.nullish(v.number()),
  z: v.nullish(v.number()),
});

/** One source's photometry statistics, ready for plotting. */
export type PhotStatAggregatePointResponse = v.InferOutput<
  typeof PhotStatAggregatePointResponseSchema
>;

export const PhotStatAggregateResponseSchema = v.strictObject({
  fields: v.optional(v.array(PhotStatAggregateFieldResponseSchema)),
  points: v.optional(v.array(PhotStatAggregatePointResponseSchema)),
  count: v.optional(v.number()),
  truncated: v.optional(v.boolean()),
});

/** Bulk photometry statistics across many sources. */
export type PhotStatAggregateResponse = v.InferOutput<
  typeof PhotStatAggregateResponseSchema
>;

export const PhotStatCountsResponseSchema = v.strictObject({
  totalWithPhotStats: v.number(),
  totalWithoutPhotStats: v.number(),
});

/** Counts of objects with and without photometry statistics. */
export type PhotStatCountsResponse = v.InferOutput<
  typeof PhotStatCountsResponseSchema
>;

export const PhotStatResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  last_update: v.nullish(v.string()),
  last_full_update: v.nullish(v.string()),
  last_phot_add_time: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  num_obs_global: v.nullish(v.number()),
  num_obs_per_filter: v.nullish(v.record(v.string(), v.unknown())),
  num_det_global: v.nullish(v.number()),
  num_det_no_forced_phot_global: v.nullish(v.number()),
  num_det_per_filter: v.nullish(v.record(v.string(), v.unknown())),
  first_detected_mjd: v.nullish(v.number()),
  first_detected_mag: v.nullish(v.number()),
  first_detected_filter: v.nullish(v.string()),
  last_detected_mjd: v.nullish(v.number()),
  last_detected_mag: v.nullish(v.number()),
  last_detected_filter: v.nullish(v.string()),
  first_detected_no_forced_phot_mjd: v.nullish(v.number()),
  first_detected_no_forced_phot_mag: v.nullish(v.number()),
  first_detected_no_forced_phot_filter: v.nullish(v.string()),
  last_detected_no_forced_phot_mjd: v.nullish(v.number()),
  last_detected_no_forced_phot_mag: v.nullish(v.number()),
  last_detected_no_forced_phot_filter: v.nullish(v.string()),
  recent_obs_mjd: v.nullish(v.number()),
  predetection_mjds: v.nullish(v.array(v.number())),
  last_non_detection_mjd: v.nullish(v.number()),
  time_to_non_detection: v.nullish(v.number()),
  mean_mag_global: v.nullish(v.number()),
  mean_mag_per_filter: v.nullish(v.record(v.string(), v.unknown())),
  mean_color: v.nullish(v.record(v.string(), v.unknown())),
  peak_mjd_global: v.nullish(v.number()),
  peak_mjd_per_filter: v.nullish(v.record(v.string(), v.unknown())),
  peak_mag_global: v.nullish(v.number()),
  peak_mag_per_filter: v.nullish(v.record(v.string(), v.unknown())),
  faintest_mag_global: v.nullish(v.number()),
  faintest_mag_per_filter: v.nullish(v.record(v.string(), v.unknown())),
  deepest_limit_global: v.nullish(v.number()),
  deepest_limit_per_filter: v.nullish(v.record(v.string(), v.unknown())),
  rise_rate: v.nullish(v.number()),
  decay_rate: v.nullish(v.number()),
  mag_rms_global: v.nullish(v.number()),
  mag_rms_per_filter: v.nullish(v.record(v.string(), v.unknown())),
});

/** Aggregate photometry statistics for one object (a ``PhotStat`` row). */
export type PhotStatResponse = v.InferOutput<typeof PhotStatResponseSchema>;

export const PhotStatUpdateGetQuerySchema = v.strictObject({
  createdAtStartTime: v.nullish(v.string()),
  createdAtEndTime: v.nullish(v.string()),
  quickUpdateStartTime: v.nullish(v.string()),
  quickUpdateEndTime: v.nullish(v.string()),
  fullUpdateStartTime: v.nullish(v.string()),
  fullUpdateEndTime: v.nullish(v.string()),
});

/** Query parameters for counting sources with and without PhotStats. */
export type PhotStatUpdateGetQuery = v.InferOutput<
  typeof PhotStatUpdateGetQuerySchema
>;

export const PhotStatUpdatePatchQuerySchema = v.strictObject({
  numPerPage: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  createdAtStartTime: v.nullish(v.string()),
  createdAtEndTime: v.nullish(v.string()),
  quickUpdateStartTime: v.nullish(v.string()),
  quickUpdateEndTime: v.nullish(v.string()),
  fullUpdateStartTime: v.nullish(v.string()),
  fullUpdateEndTime: v.nullish(v.string()),
});

/** Query parameters for recalculating PhotStats for a batch of sources. */
export type PhotStatUpdatePatchQuery = v.InferOutput<
  typeof PhotStatUpdatePatchQuerySchema
>;

export const PhotStatUpdatePostQuerySchema = v.strictObject({
  numPerPage: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  createdAtStartTime: v.nullish(v.string()),
  createdAtEndTime: v.nullish(v.string()),
});

/** Query parameters for calculating PhotStats for a batch of sources. */
export type PhotStatUpdatePostQuery = v.InferOutput<
  typeof PhotStatUpdatePostQuerySchema
>;

export const PhotStatsBatchResponseSchema = v.strictObject({
  totalMatches: v.number(),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/** Pagination summary of a batch photometry-statistics update. */
export type PhotStatsBatchResponse = v.InferOutput<
  typeof PhotStatsBatchResponseSchema
>;

export const SavedSourceResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.string(),
  group_id: v.nullish(v.number()),
  saved_by_id: v.nullish(v.number()),
  saved_at: v.nullish(v.string()),
  active: v.nullish(v.boolean()),
  requested: v.nullish(v.boolean()),
  unsaved_by_id: v.nullish(v.number()),
  unsaved_at: v.nullish(v.string()),
});

/**
 * A row of the save-summary form of the sources query: the ``Source``
 * join-table record between an object and the group it is saved to.
 */
export type SavedSourceResponse = v.InferOutput<
  typeof SavedSourceResponseSchema
>;

export const SourceAssociatedObjResponseSchema = v.strictObject({
  obj_id: v.string(),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  separation: v.nullish(v.number()),
  super_obj_id: v.nullish(v.number()),
  super_obj_name: v.nullish(v.string()),
});

/** An object linked to this source through a ``SuperObj``. */
export type SourceAssociatedObjResponse = v.InferOutput<
  typeof SourceAssociatedObjResponseSchema
>;

export const SourceCandidateResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  filter_id: v.nullish(v.number()),
  passed_at: v.nullish(v.string()),
  passing_alert_id: v.nullish(v.number()),
  uploader_id: v.nullish(v.number()),
  filter: v.nullish(FilterResponseSchema),
});

/** A filter passage as returned on a source (a ``Candidate``). */
export type SourceCandidateResponse = v.InferOutput<
  typeof SourceCandidateResponseSchema
>;

export const SourceColorMagResponseSchema = v.strictObject({
  origin: v.nullish(v.string()),
  color: v.nullish(v.number()),
  abs_mag: v.nullish(v.number()),
});

/** A color and absolute magnitude derived from one catalog cross-match. */
export type SourceColorMagResponse = v.InferOutput<
  typeof SourceColorMagResponseSchema
>;

export const SourceCopyPhotometryPostBodySchema = v.strictObject({
  group_ids: v.array(v.number()),
  origin_id: v.string(),
});

/** Request body for copying photometry from one source to another. */
export type SourceCopyPhotometryPostBody = v.InferOutput<
  typeof SourceCopyPhotometryPostBodySchema
>;

export const SourceDeleteBodySchema = v.strictObject({
  group_id: v.nullish(v.number()),
});

/** Request body for unsaving a source from a group. */
export type SourceDeleteBody = v.InferOutput<typeof SourceDeleteBodySchema>;

export const SourceDuplicateResponseSchema = v.strictObject({
  obj_id: v.string(),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  separation: v.nullish(v.number()),
});

/** Another saved source within 4 arcsec of this one (an ``Obj``). */
export type SourceDuplicateResponse = v.InferOutput<
  typeof SourceDuplicateResponseSchema
>;

export const SourceExistsGetQuerySchema = v.strictObject({
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  radius: v.nullish(v.number()),
});

/** Query parameters for checking whether a source already exists. */
export type SourceExistsGetQuery = v.InferOutput<
  typeof SourceExistsGetQuerySchema
>;

export const SourceExistsResponseSchema = v.strictObject({
  source_exists: v.boolean(),
  message: v.nullish(v.string()),
});

/** Whether a source already exists by name or by position. */
export type SourceExistsResponse = v.InferOutput<
  typeof SourceExistsResponseSchema
>;

export const SourceOffsetStarResponseSchema = v.strictObject({
  str: v.string(),
  name: v.nullish(v.string()),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  dras: v.nullish(v.string()),
  ddecs: v.nullish(v.string()),
  mag: v.nullish(v.number()),
  pa: v.nullish(v.number()),
});

/** One line of an offset-star starlist. */
export type SourceOffsetStarResponse = v.InferOutput<
  typeof SourceOffsetStarResponseSchema
>;

export const SourceFinderChartResponseSchema = v.strictObject({
  finding_chart: v.string(),
  starlist: v.optional(v.array(SourceOffsetStarResponseSchema)),
  public_url: v.nullish(v.string()),
  public_url_expires_at: v.nullish(v.string()),
});

/**
 * A finding chart returned as JSON rather than as a file.
 *
 * public_url is only present when the chart was cached.
 */
export type SourceFinderChartResponse = v.InferOutput<
  typeof SourceFinderChartResponseSchema
>;

export const SourceFollowupRequestResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  allocation_id: v.nullish(v.number()),
  requester_id: v.nullish(v.number()),
  last_modified_by_id: v.nullish(v.number()),
  payload: v.optional(v.record(v.string(), v.unknown())),
  status: v.nullish(v.string()),
  comment: v.nullish(v.string()),
  obj: v.nullish(v.record(v.string(), v.unknown())),
  allocation: v.nullish(AllocationResponseSchema),
  requester: v.nullish(UserResponseSchema),
  last_modified_by: v.nullish(UserResponseSchema),
  target_groups: v.optional(v.array(GroupResponseSchema)),
  watchers: v.optional(v.array(FollowupRequestWatcherResponseSchema)),
  transactions: v.optional(v.array(v.unknown())),
  transaction_requests: v.optional(
    v.array(FacilityTransactionRequestResponseSchema),
  ),
  photometry: v.optional(v.array(v.record(v.string(), v.unknown()))),
  photometric_series: v.optional(v.array(v.record(v.string(), v.unknown()))),
  spectra: v.optional(v.array(v.record(v.string(), v.unknown()))),
  rise_time_utc: v.nullish(v.string()),
  set_time_utc: v.nullish(v.string()),
});

/** A follow-up request as returned on a source. */
export type SourceFollowupRequestResponse = v.InferOutput<
  typeof SourceFollowupRequestResponseSchema
>;

export const SourceGcnEventCrossmatchPostSchema = v.strictObject({
  startDate: v.string(),
  endDate: v.string(),
  probability: v.nullish(v.number()),
  beforeFirstDetection: v.nullish(v.boolean()),
  gcnTagKeep: v.nullish(v.array(v.string())),
  gcnTagRemove: v.nullish(v.array(v.string())),
  localizationTagKeep: v.nullish(v.array(v.string())),
  localizationTagRemove: v.nullish(v.array(v.string())),
  gcnPropertiesFilter: v.nullish(v.array(v.string())),
  localizationPropertiesFilter: v.nullish(v.array(v.string())),
});

/** Payload for crossmatching a source against GCN events. */
export type SourceGcnEventCrossmatchPost = v.InferOutput<
  typeof SourceGcnEventCrossmatchPostSchema
>;

export const SourceGcnNoteResponseSchema = v.strictObject({
  dateobs: v.nullish(v.string()),
  explanation: v.nullish(v.string()),
  notes: v.nullish(v.string()),
  status: v.nullish(
    v.picklist([
      "highlighted",
      "rejected",
      "ambiguous",
      "pending",
      "not vetted",
    ]),
  ),
});

/** A source's vetting note for one GCN event (a ``GcnEventObj``). */
export type SourceGcnNoteResponse = v.InferOutput<
  typeof SourceGcnNoteResponseSchema
>;

export const SourceGetQuerySchema = v.strictObject({
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
  TNSname: v.nullish(v.string()),
  ra: v.nullish(v.string()),
  dec: v.nullish(v.string()),
  radius: v.nullish(v.string()),
  startDate: v.nullish(v.string()),
  endDate: v.nullish(v.string()),
  detectedWindowStart: v.nullish(v.string()),
  detectedWindowEnd: v.nullish(v.string()),
  listName: v.nullish(v.string()),
  sourceID: v.nullish(v.string()),
  rejectedSourceIDs: v.nullish(v.array(v.string())),
  includePhotometry: v.optional(v.boolean()),
  deduplicatePhotometry: v.optional(v.boolean()),
  includeColorMagnitude: v.optional(v.boolean()),
  includeRequested: v.optional(v.boolean()),
  includeThumbnails: v.optional(v.boolean()),
  pendingOnly: v.optional(v.boolean()),
  savedAfter: v.nullish(v.string()),
  savedBefore: v.nullish(v.string()),
  savedByCurrentUser: v.optional(v.boolean()),
  saveSummary: v.optional(v.boolean()),
  sortBy: v.nullish(v.string()),
  sortOrder: v.optional(v.string()),
  includeComments: v.optional(v.boolean()),
  includeAnalyses: v.optional(v.boolean()),
  includePhotometryExists: v.optional(v.boolean()),
  includeSpectrumExists: v.optional(v.boolean()),
  includeCommentExists: v.optional(v.boolean()),
  includePeriodExists: v.optional(v.boolean()),
  includeLabellers: v.optional(v.boolean()),
  includeHosts: v.optional(v.boolean()),
  includeGCNCrossmatches: v.optional(v.boolean()),
  includeGCNNotes: v.optional(v.boolean()),
  excludeForcedPhotometry: v.optional(v.boolean()),
  requireDetections: v.optional(v.boolean()),
  removeNested: v.optional(v.boolean()),
  includeDetectionStats: v.optional(v.boolean()),
  classifications: v.nullish(v.string()),
  classifications_simul: v.optional(v.boolean()),
  nonclassifications: v.nullish(v.string()),
  classified: v.optional(v.boolean()),
  unclassified: v.optional(v.boolean()),
  annotationsFilter: v.nullish(v.string()),
  annotationsFilterOrigin: v.nullish(v.string()),
  annotationsFilterAfter: v.nullish(v.string()),
  annotationsFilterBefore: v.nullish(v.string()),
  commentsFilter: v.nullish(v.string()),
  commentsFilterAuthor: v.nullish(v.number()),
  commentsFilterAfter: v.nullish(v.string()),
  commentsFilterBefore: v.nullish(v.string()),
  minRedshift: v.nullish(v.number()),
  maxRedshift: v.nullish(v.number()),
  minPeakMagnitude: v.nullish(v.number()),
  maxPeakMagnitude: v.nullish(v.number()),
  minLatestMagnitude: v.nullish(v.number()),
  maxLatestMagnitude: v.nullish(v.number()),
  hasSpectrum: v.optional(v.boolean()),
  hasNoSpectrum: v.optional(v.boolean()),
  hasSpectrumAfter: v.nullish(v.string()),
  hasSpectrumBefore: v.nullish(v.string()),
  hasFollowupRequest: v.optional(v.boolean()),
  followupRequestStatus: v.nullish(v.string()),
  createdOrModifiedAfter: v.nullish(v.string()),
  numberDetections: v.nullish(v.number()),
  localizationDateobs: v.nullish(v.string()),
  localizationName: v.nullish(v.string()),
  localizationCumprob: v.optional(v.number()),
  localizationRejectSources: v.optional(v.boolean()),
  includeSourcesInGcn: v.optional(v.boolean()),
  spatialCatalogName: v.nullish(v.string()),
  spatialCatalogEntryName: v.nullish(v.string()),
  includeGeoJSON: v.optional(v.boolean()),
  includeCandidates: v.optional(v.boolean()),
  includeTags: v.optional(v.boolean()),
  includeAssociatedObjs: v.optional(v.boolean()),
  includeSuperObjs: v.optional(v.boolean()),
  useCache: v.optional(v.boolean()),
  queryID: v.nullish(v.string()),
  group_ids: v.nullish(v.array(v.number())),
  simbadClass: v.nullish(v.string()),
  minAbsGalacticLatitude: v.nullish(v.number()),
  maxDeltaT: v.nullish(v.number()),
  promptDeltaT: v.nullish(v.number()),
  alias: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  hasTNSname: v.optional(v.boolean()),
  hasNoTNSname: v.optional(v.boolean()),
  isRoid: v.optional(v.boolean()),
  isNotRoid: v.optional(v.boolean()),
  hasBeenLabelled: v.optional(v.boolean()),
  hasNotBeenLabelled: v.optional(v.boolean()),
  currentUserLabeller: v.optional(v.boolean()),
});

/** Query parameters for retrieving a single source or querying sources. */
export type SourceGetQuery = v.InferOutput<typeof SourceGetQuerySchema>;

export const SourceInterestPostBodySchema = v.strictObject({
  title: v.string(),
  description: v.nullish(v.string()),
  link: v.nullish(v.string()),
});

/** Request body for registering an interest in a source. */
export type SourceInterestPostBody = v.InferOutput<
  typeof SourceInterestPostBodySchema
>;

export const SourceLabelsDeleteBodySchema = v.strictObject({
  groupIds: v.array(v.number()),
});

/** Request body for deleting source labels. */
export type SourceLabelsDeleteBody = v.InferOutput<
  typeof SourceLabelsDeleteBodySchema
>;

export const SourceLabelsPostBodySchema = v.strictObject({
  groupIds: v.array(v.number()),
});

/** Request body for labelling a source. */
export type SourceLabelsPostBody = v.InferOutput<
  typeof SourceLabelsPostBodySchema
>;

export const SourceMpcQueryPostSchema = v.strictObject({
  obscode: v.nullish(v.string()),
  date: v.nullish(v.string()),
  limiting_magnitude: v.nullish(v.number()),
  search_radius: v.nullish(v.number()),
});

/** Payload for a Minor Planet Center crossmatch. */
export type SourceMpcQueryPost = v.InferOutput<typeof SourceMpcQueryPostSchema>;

export const SourceNotificationPostSchema = v.strictObject({
  sourceId: v.string(),
  groupIds: v.array(v.number()),
  level: v.picklist(["soft", "hard"]),
  additionalNotes: v.nullish(v.string()),
});

/** Payload for sending a source notification. */
export type SourceNotificationPost = v.InferOutput<
  typeof SourceNotificationPostSchema
>;

export const SourceNotificationPostBodySchema = v.strictObject({
  groupIds: v.array(v.number()),
  sourceId: v.string(),
  level: v.picklist(["soft", "hard"]),
  additionalNotes: v.nullish(v.string()),
});

/** Request body for sending a source notification. */
export type SourceNotificationPostBody = v.InferOutput<
  typeof SourceNotificationPostBodySchema
>;

export const SourceNotificationPostResponseSchema = v.strictObject({
  id: v.number(),
});

/** Result of sending a source notification. */
export type SourceNotificationPostResponse = v.InferOutput<
  typeof SourceNotificationPostResponseSchema
>;

export const SourceObservabilityPlotGetQuerySchema = v.strictObject({
  maxAirmass: v.optional(v.number()),
  twilight: v.optional(v.picklist(["astronomical", "nautical", "civil"])),
});

/** Query parameters for a source's observability plot. */
export type SourceObservabilityPlotGetQuery = v.InferOutput<
  typeof SourceObservabilityPlotGetQuerySchema
>;

export const SourceOffsetsResponseSchema = v.strictObject({
  facility: v.nullish(v.string()),
  starlist_str: v.nullish(v.string()),
  starlist_info: v.optional(v.array(SourceOffsetStarResponseSchema)),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  noffsets: v.nullish(v.number()),
  queries_issued: v.nullish(v.number()),
  query: v.nullish(v.string()),
  used_ztfref: v.nullish(v.boolean()),
  gaia_available: v.nullish(v.boolean()),
});

/** Offset stars for a source, in a facility's starlist format. */
export type SourceOffsetsResponse = v.InferOutput<
  typeof SourceOffsetsResponseSchema
>;

export const SourcePatchBodySchema = v.strictObject({
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_dis: v.nullish(v.number()),
  dec_dis: v.nullish(v.number()),
  ra_err: v.nullish(v.number()),
  dec_err: v.nullish(v.number()),
  offset: v.nullish(v.number()),
  t0: v.nullish(v.number()),
  redshift: v.nullish(v.number()),
  redshift_error: v.nullish(v.number()),
  redshift_origin: v.nullish(v.string()),
  redshift_history: v.optional(v.unknown()),
  host_id: v.nullish(v.number()),
  summary: v.nullish(v.string()),
  summary_history: v.optional(v.unknown()),
  altdata: v.optional(v.unknown()),
  dist_nearest_source: v.nullish(v.number()),
  mag_nearest_source: v.nullish(v.number()),
  e_mag_nearest_source: v.nullish(v.number()),
  transient: v.nullish(v.boolean()),
  varstar: v.nullish(v.boolean()),
  is_roid: v.nullish(v.boolean()),
  mpc_name: v.nullish(v.string()),
  tns_name: v.nullish(v.string()),
  tns_info: v.optional(v.unknown()),
  score: v.nullish(v.number()),
  origin: v.nullish(v.string()),
  alias: v.nullish(v.array(v.string())),
});

/** Request body for updating an existing source (obj_id comes from the path). */
export type SourcePatchBody = v.InferOutput<typeof SourcePatchBodySchema>;

export const SourcePostSchema = v.strictObject({
  id: v.string(),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_dis: v.nullish(v.number()),
  dec_dis: v.nullish(v.number()),
  ra_err: v.nullish(v.number()),
  dec_err: v.nullish(v.number()),
  offset: v.nullish(v.number()),
  t0: v.nullish(v.number()),
  redshift: v.nullish(v.number()),
  redshift_error: v.nullish(v.number()),
  redshift_origin: v.nullish(v.string()),
  host_id: v.nullish(v.number()),
  summary: v.nullish(v.string()),
  summary_history: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  dist_nearest_source: v.nullish(v.number()),
  mag_nearest_source: v.nullish(v.number()),
  e_mag_nearest_source: v.nullish(v.number()),
  transient: v.nullish(v.boolean()),
  varstar: v.nullish(v.boolean()),
  is_roid: v.nullish(v.boolean()),
  mpc_name: v.nullish(v.string()),
  tns_name: v.nullish(v.string()),
  tns_info: v.nullish(v.record(v.string(), v.unknown())),
  score: v.nullish(v.number()),
  origin: v.nullish(v.string()),
  alias: v.nullish(v.array(v.string())),
  detect_photometry_count: v.nullish(v.number()),
  group_ids: v.nullish(v.array(v.number())),
  refresh_source: v.nullish(v.boolean()),
  ignore_if_in_group_ids: v.nullish(v.record(v.string(), v.array(v.number()))),
  saver_per_group_id: v.nullish(v.record(v.string(), v.number())),
});

/** Payload for saving a new source (upstream ``ObjPost``). */
export type SourcePost = v.InferOutput<typeof SourcePostSchema>;

export const SourcePostBodySchema = v.strictObject({
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_dis: v.nullish(v.number()),
  dec_dis: v.nullish(v.number()),
  ra_err: v.nullish(v.number()),
  dec_err: v.nullish(v.number()),
  offset: v.nullish(v.number()),
  t0: v.nullish(v.number()),
  redshift: v.nullish(v.number()),
  redshift_error: v.nullish(v.number()),
  redshift_origin: v.nullish(v.string()),
  redshift_history: v.optional(v.unknown()),
  host_id: v.nullish(v.number()),
  summary: v.nullish(v.string()),
  summary_history: v.optional(v.unknown()),
  altdata: v.optional(v.unknown()),
  dist_nearest_source: v.nullish(v.number()),
  mag_nearest_source: v.nullish(v.number()),
  e_mag_nearest_source: v.nullish(v.number()),
  transient: v.nullish(v.boolean()),
  varstar: v.nullish(v.boolean()),
  is_roid: v.nullish(v.boolean()),
  mpc_name: v.nullish(v.string()),
  tns_name: v.nullish(v.string()),
  tns_info: v.optional(v.unknown()),
  score: v.nullish(v.number()),
  origin: v.nullish(v.string()),
  alias: v.nullish(v.array(v.string())),
  id: v.string(),
  group_ids: v.nullish(v.array(v.number())),
  refresh_source: v.optional(v.boolean()),
  ignore_if_in_group_ids: v.nullish(v.record(v.string(), v.unknown())),
  saver_per_group_id: v.nullish(v.record(v.string(), v.unknown())),
});

/** Request body for saving a new (or existing) source. */
export type SourcePostBody = v.InferOutput<typeof SourcePostBodySchema>;

export const SourcePostResponseSchema = v.strictObject({
  id: v.string(),
  saved_to_groups: v.optional(v.array(v.number())),
  warnings: v.optional(v.array(v.string())),
});

/** Result of saving a new source. */
export type SourcePostResponse = v.InferOutput<typeof SourcePostResponseSchema>;

export const SourceSavedGroupResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  name: v.string(),
  nickname: v.nullish(v.string()),
  description: v.nullish(v.string()),
  private: v.nullish(v.boolean()),
  auto_accept_requests: v.nullish(v.boolean()),
  discoverable_data: v.nullish(v.boolean()),
  single_user_group: v.optional(v.boolean()),
  streams: v.nullish(v.array(StreamResponseSchema)),
  filters: v.nullish(v.array(FilterResponseSchema)),
  group_users: v.nullish(v.array(GroupUserResponseSchema)),
  users: v.nullish(v.array(GroupMemberResponseSchema)),
  active: v.nullish(v.boolean()),
  requested: v.nullish(v.boolean()),
  saved_at: v.nullish(v.string()),
  saved_by: v.nullish(UserResponseSchema),
});

/** A group a source is saved to, with its ``sources`` join-table record. */
export type SourceSavedGroupResponse = v.InferOutput<
  typeof SourceSavedGroupResponseSchema
>;

export const SourceResponseSchema = v.strictObject({
  id: v.string(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  ra: v.nullish(v.number()),
  dec: v.nullish(v.number()),
  ra_dis: v.nullish(v.number()),
  dec_dis: v.nullish(v.number()),
  ra_err: v.nullish(v.number()),
  dec_err: v.nullish(v.number()),
  offset: v.nullish(v.number()),
  t0: v.nullish(v.number()),
  redshift: v.nullish(v.number()),
  redshift_error: v.nullish(v.number()),
  redshift_origin: v.nullish(v.string()),
  redshift_history: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  host_id: v.nullish(v.number()),
  summary: v.nullish(v.string()),
  summary_history: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  dist_nearest_source: v.nullish(v.number()),
  mag_nearest_source: v.nullish(v.number()),
  e_mag_nearest_source: v.nullish(v.number()),
  transient: v.nullish(v.boolean()),
  varstar: v.nullish(v.boolean()),
  is_roid: v.nullish(v.boolean()),
  mpc_name: v.nullish(v.string()),
  tns_name: v.nullish(v.string()),
  tns_info: v.nullish(v.record(v.string(), v.unknown())),
  score: v.nullish(v.number()),
  origin: v.nullish(v.string()),
  alias: v.nullish(v.array(v.string())),
  healpix: v.nullish(v.number()),
  detect_photometry_count: v.nullish(v.number()),
  internal_key: v.nullish(v.string()),
  gal_lat: v.nullish(v.number()),
  gal_lon: v.nullish(v.number()),
  luminosity_distance: v.nullish(v.number()),
  dm: v.nullish(v.number()),
  angular_diameter_distance: v.nullish(v.number()),
  ebv: v.nullish(v.number()),
  first_detected: v.nullish(v.string()),
  last_detected: v.nullish(v.string()),
  host_offset: v.nullish(v.number()),
  host_distance: v.nullish(v.number()),
  period_exists: v.nullish(v.boolean()),
  period: v.nullish(v.boolean()),
  photometry_exists: v.nullish(v.boolean()),
  spectrum_exists: v.nullish(v.boolean()),
  comment_exists: v.nullish(v.boolean()),
  galaxies: v.nullish(v.array(v.string())),
  duplicates: v.optional(v.array(SourceDuplicateResponseSchema)),
  associated_objs: v.optional(v.array(SourceAssociatedObjResponseSchema)),
  color_magnitude: v.optional(v.array(SourceColorMagResponseSchema)),
  gcn_notes: v.optional(v.array(SourceGcnNoteResponseSchema)),
  tags: v.optional(v.array(ObjTagResponseSchema)),
  groups: v.optional(v.array(SourceSavedGroupResponseSchema)),
  thumbnails: v.optional(v.array(ThumbnailResponseSchema)),
  photstats: v.optional(v.array(PhotStatResponseSchema)),
  annotations: v.optional(v.array(AnnotationResponseSchema)),
  classifications: v.optional(v.array(ClassificationResponseSchema)),
  comments: v.optional(v.array(CommentResponseSchema)),
  photometry: v.optional(v.array(PhotometryPointResponseSchema)),
  host: v.nullish(GalaxyResponseSchema),
  followup_requests: v.optional(v.array(SourceFollowupRequestResponseSchema)),
  assignments: v.optional(v.array(AssignmentResponseSchema)),
  analyses: v.optional(v.array(ObjAnalysisResponseSchema)),
  candidates: v.optional(v.array(SourceCandidateResponseSchema)),
  gcn_crossmatch: v.optional(v.array(v.record(v.string(), v.unknown()))),
  labellers: v.optional(v.array(v.record(v.string(), v.unknown()))),
});

/** A SkyPortal source (an ``Obj`` saved to at least one group). */
export type SourceResponse = v.InferOutput<typeof SourceResponseSchema>;

export const SourcesPageResponseSchema = v.strictObject({
  sources: v.array(SourceResponseSchema),
  totalMatches: v.number(),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
  group_id: v.nullish(v.number()),
  queryID: v.nullish(v.string()),
  geojson: v.nullish(v.record(v.string(), v.unknown())),
  hint: v.nullish(v.string()),
});

/** One page of results from a sources query. */
export type SourcesPageResponse = v.InferOutput<
  typeof SourcesPageResponseSchema
>;

export const SourcesSaveSummaryPageResponseSchema = v.strictObject({
  sources: v.optional(v.array(SavedSourceResponseSchema)),
  totalMatches: v.nullish(v.number()),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
  group_id: v.nullish(v.number()),
  queryID: v.nullish(v.string()),
  hint: v.nullish(v.string()),
});

/** One page of results from a save-summary sources query. */
export type SourcesSaveSummaryPageResponse = v.InferOutput<
  typeof SourcesSaveSummaryPageResponseSchema
>;

export const SurveyThumbnailPostBodySchema = v.strictObject({
  objID: v.nullish(v.string()),
  objIDs: v.nullish(v.array(v.string())),
  types: v.nullish(v.array(v.string())),
});

/** Request body for adding survey thumbnails to one or more objects. */
export type SurveyThumbnailPostBody = v.InferOutput<
  typeof SurveyThumbnailPostBodySchema
>;
