// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const SourceGroupsPatchBodySchema = v.strictObject({
  groupID: v.number(),
  active: v.boolean(),
  requested: v.boolean(),
});

/** Request body for updating a Source table row. */
export type SourceGroupsPatchBody = v.InferOutput<
  typeof SourceGroupsPatchBodySchema
>;

export const SourceGroupsPostSchema = v.strictObject({
  objId: v.string(),
  inviteGroupIds: v.optional(v.array(v.number())),
  unsaveGroupIds: v.optional(v.array(v.number())),
});

/** Payload for saving or unsaving a source to or from groups. */
export type SourceGroupsPost = v.InferOutput<typeof SourceGroupsPostSchema>;

export const SourceGroupsPostBodySchema = v.strictObject({
  objId: v.string(),
  inviteGroupIds: v.optional(v.array(v.number())),
  unsaveGroupIds: v.optional(v.array(v.number())),
});

/** Request body for saving/unsaving a source to/from groups. */
export type SourceGroupsPostBody = v.InferOutput<
  typeof SourceGroupsPostBodySchema
>;
