// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const SpatialCatalogASCIIFilePostBodySchema = v.strictObject({
  catalogData: v.nullish(v.string()),
  catalogName: v.nullish(v.string()),
});

/** Request body for uploading a spatial catalog from an ASCII file. */
export type SpatialCatalogASCIIFilePostBody = v.InferOutput<
  typeof SpatialCatalogASCIIFilePostBodySchema
>;

export const SpatialCatalogASCIIFilePostResponseSchema = v.object({
  id: v.number(),
});

/** ID of the newly created spatial catalog. */
export type SpatialCatalogASCIIFilePostResponse = v.InferOutput<
  typeof SpatialCatalogASCIIFilePostResponseSchema
>;

export const SpatialCatalogEntryResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  catalog_id: v.nullish(v.number()),
  entry_name: v.nullish(v.string()),
  data: v.nullish(v.record(v.string(), v.unknown())),
  uniq: v.nullish(v.array(v.number())),
  probdensity: v.nullish(v.array(v.number())),
});

/** An entry in a spatial catalog (a ``SpatialCatalogEntry``). */
export type SpatialCatalogEntryResponse = v.InferOutput<
  typeof SpatialCatalogEntryResponseSchema
>;

export const SpatialCatalogGetQuerySchema = v.strictObject({
  catalog_name: v.nullish(v.string()),
});

/** Query parameters for retrieving spatial catalogs. */
export type SpatialCatalogGetQuery = v.InferOutput<
  typeof SpatialCatalogGetQuerySchema
>;

export const SpatialCatalogPostBodySchema = v.strictObject({
  catalog_name: v.optional(v.unknown()),
  catalog_data: v.optional(v.unknown()),
});

/** Request body for ingesting a spatial catalog. */
export type SpatialCatalogPostBody = v.InferOutput<
  typeof SpatialCatalogPostBodySchema
>;

export const SpatialCatalogPostResponseSchema = v.object({
  id: v.number(),
});

/** ID of the newly created spatial catalog. */
export type SpatialCatalogPostResponse = v.InferOutput<
  typeof SpatialCatalogPostResponseSchema
>;

export const SpatialCatalogResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  catalog_name: v.nullish(v.string()),
  entries: v.nullish(v.array(SpatialCatalogEntryResponseSchema)),
  entries_count: v.nullish(v.number()),
});

/** A spatial catalog of skymap regions (a ``SpatialCatalog``). */
export type SpatialCatalogResponse = v.InferOutput<
  typeof SpatialCatalogResponseSchema
>;
