// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import {
  GroupResponseSchema,
  InstrumentResponseSchema,
  UserResponseSchema,
} from "./_cyclic.js";
import { AnnotationDetailResponseSchema } from "./annotations.js";
import { CommentDetailResponseSchema } from "./comments.js";

export const BulkSpectraPostBodySchema = v.strictObject({
  group_id: v.nullish(v.number()),
  obj_ids: v.optional(v.union([v.array(v.string()), v.string(), v.null()])),
  classifications: v.optional(
    v.union([v.array(v.string()), v.string(), v.null()]),
  ),
  classificationProbThreshold: v.nullish(v.number()),
  maxSources: v.nullish(v.number()),
});

/** Request body for the bulk spectra endpoint. */
export type BulkSpectraPostBody = v.InferOutput<
  typeof BulkSpectraPostBodySchema
>;

export const BulkSpectraSourceResponseSchema = v.strictObject({
  id: v.string(),
  redshift: v.nullish(v.number()),
  first_detected_mjd: v.nullish(v.number()),
  peak_mjd: v.nullish(v.number()),
  tns_discovery_date: v.nullish(v.string()),
});

/** Phase anchors for one source in a bulk spectra response. */
export type BulkSpectraSourceResponse = v.InferOutput<
  typeof BulkSpectraSourceResponseSchema
>;

export const BulkSpectrumResponseSchema = v.strictObject({
  obj_id: v.nullish(v.string()),
  observed_at: v.nullish(v.string()),
  wavelengths: v.optional(v.array(v.number())),
  fluxes: v.optional(v.array(v.number())),
});

/** A slim spectrum returned by the bulk spectra endpoint. */
export type BulkSpectrumResponse = v.InferOutput<
  typeof BulkSpectrumResponseSchema
>;

export const BulkSpectraResponseSchema = v.strictObject({
  sources: v.optional(v.array(BulkSpectraSourceResponseSchema)),
  spectra: v.optional(v.array(BulkSpectrumResponseSchema)),
  truncated: v.optional(v.boolean()),
});

/** Result of a bulk spectra query. */
export type BulkSpectraResponse = v.InferOutput<
  typeof BulkSpectraResponseSchema
>;

export const ObjSpectraGetQuerySchema = v.strictObject({
  normalization: v.nullish(v.literal("median")),
  sortBy: v.optional(v.picklist(["observed_at", "created_at"])),
  sortOrder: v.optional(v.picklist(["asc", "desc"])),
  includeOriginalFile: v.optional(v.boolean()),
});

/** Query parameters for retrieving all spectra associated with an Object. */
export type ObjSpectraGetQuery = v.InferOutput<typeof ObjSpectraGetQuerySchema>;

export const ParsedSpectrumResponseSchema = v.strictObject({
  id: v.nullish(v.number()),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  observed_at: v.nullish(v.string()),
  wavelengths: v.optional(v.array(v.number())),
  fluxes: v.optional(v.array(v.number())),
  errors: v.nullish(v.array(v.number())),
  units: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  type: v.nullish(v.string()),
  label: v.nullish(v.string()),
  instrument_id: v.nullish(v.number()),
  followup_request_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  original_file_string: v.nullish(v.string()),
  original_file_filename: v.nullish(v.string()),
  owner_id: v.nullish(v.number()),
});

/** A spectrum parsed from ASCII but not saved to the database. */
export type ParsedSpectrumResponse = v.InferOutput<
  typeof ParsedSpectrumResponseSchema
>;

export const SpectrumResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  obj: v.nullish(v.record(v.string(), v.unknown())),
  observed_at: v.nullish(v.string()),
  wavelengths: v.optional(v.array(v.number())),
  fluxes: v.optional(v.array(v.number())),
  errors: v.nullish(v.array(v.number())),
  units: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  type: v.nullish(v.string()),
  label: v.nullish(v.string()),
  instrument_id: v.nullish(v.number()),
  instrument: v.nullish(InstrumentResponseSchema),
  instrument_name: v.nullish(v.string()),
  telescope_id: v.nullish(v.number()),
  telescope_name: v.nullish(v.string()),
  followup_request_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  original_file_string: v.nullish(v.string()),
  original_file_filename: v.nullish(v.string()),
  owner_id: v.nullish(v.number()),
  owner: v.nullish(UserResponseSchema),
  groups: v.optional(v.array(GroupResponseSchema)),
  pis: v.optional(v.array(UserResponseSchema)),
  reducers: v.optional(v.array(UserResponseSchema)),
  observers: v.optional(v.array(UserResponseSchema)),
  external_pi: v.nullish(v.string()),
  external_reducer: v.nullish(v.string()),
  external_observer: v.nullish(v.string()),
  comments: v.optional(v.array(CommentDetailResponseSchema)),
  annotations: v.optional(v.array(AnnotationDetailResponseSchema)),
  observed_at_mjd: v.nullish(v.number()),
});

/** A spectrum, as returned by the single-spectrum and per-object routes. */
export type SpectrumResponse = v.InferOutput<typeof SpectrumResponseSchema>;

export const SourceSpectraResponseSchema = v.strictObject({
  obj_id: v.nullish(v.string()),
  spectra: v.optional(v.array(SpectrumResponseSchema)),
});

/** Envelope of a source's spectra response. */
export type SourceSpectraResponse = v.InferOutput<
  typeof SourceSpectraResponseSchema
>;

export const SpectrumASCIIParseBodySchema = v.strictObject({
  wave_column: v.nullish(v.number()),
  flux_column: v.nullish(v.number()),
  fluxerr_column: v.nullish(v.number()),
  ascii: v.nullish(v.string()),
});

/**
 * Request body for parsing a spectrum from an ASCII file (see
 * SpectrumAsciiFileParseJSON).
 */
export type SpectrumASCIIParseBody = v.InferOutput<
  typeof SpectrumASCIIParseBodySchema
>;

export const SpectrumASCIIPostBodySchema = v.strictObject({
  wave_column: v.nullish(v.number()),
  flux_column: v.nullish(v.number()),
  fluxerr_column: v.nullish(v.number()),
  ascii: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  instrument_id: v.nullish(v.number()),
  type: v.nullish(v.string()),
  label: v.nullish(v.string()),
  observed_at: v.nullish(v.string()),
  group_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
  filename: v.nullish(v.string()),
  pi: v.nullish(v.array(v.number())),
  external_pi: v.nullish(v.string()),
  reduced_by: v.nullish(v.array(v.number())),
  external_reducer: v.nullish(v.string()),
  observed_by: v.nullish(v.array(v.number())),
  external_observer: v.nullish(v.string()),
  followup_request_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
});

/**
 * Request body for uploading a spectrum from an ASCII file (see
 * SpectrumAsciiFilePostJSON).
 */
export type SpectrumASCIIPostBody = v.InferOutput<
  typeof SpectrumASCIIPostBodySchema
>;

export const SpectrumASCIIPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when uploading a spectrum from an ASCII file. */
export type SpectrumASCIIPostResponse = v.InferOutput<
  typeof SpectrumASCIIPostResponseSchema
>;

export const SpectrumAsciiParseSchema = v.strictObject({
  ascii: v.string(),
  wave_column: v.nullish(v.number()),
  flux_column: v.nullish(v.number()),
  fluxerr_column: v.nullish(v.number()),
});

/** Payload for parsing an ASCII spectrum without saving it. */
export type SpectrumAsciiParse = v.InferOutput<typeof SpectrumAsciiParseSchema>;

export const SpectrumAsciiPostSchema = v.strictObject({
  ascii: v.string(),
  obj_id: v.string(),
  instrument_id: v.number(),
  observed_at: v.string(),
  filename: v.string(),
  wave_column: v.nullish(v.number()),
  flux_column: v.nullish(v.number()),
  fluxerr_column: v.nullish(v.number()),
  type: v.nullish(v.string()),
  label: v.nullish(v.string()),
  group_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
  pi: v.nullish(v.array(v.number())),
  external_pi: v.nullish(v.string()),
  reduced_by: v.nullish(v.array(v.number())),
  external_reducer: v.nullish(v.string()),
  observed_by: v.nullish(v.array(v.number())),
  external_observer: v.nullish(v.string()),
  followup_request_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
});

/** Payload for uploading a spectrum from an ASCII file. */
export type SpectrumAsciiPost = v.InferOutput<typeof SpectrumAsciiPostSchema>;

export const SpectrumDetailResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  obj: v.nullish(v.record(v.string(), v.unknown())),
  observed_at: v.nullish(v.string()),
  wavelengths: v.optional(v.array(v.number())),
  fluxes: v.optional(v.array(v.number())),
  errors: v.nullish(v.array(v.number())),
  units: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  type: v.nullish(v.string()),
  label: v.nullish(v.string()),
  instrument_id: v.nullish(v.number()),
  instrument: v.nullish(InstrumentResponseSchema),
  instrument_name: v.nullish(v.string()),
  telescope_id: v.nullish(v.number()),
  telescope_name: v.nullish(v.string()),
  followup_request_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  original_file_string: v.nullish(v.string()),
  original_file_filename: v.nullish(v.string()),
  owner_id: v.nullish(v.number()),
  owner: v.nullish(UserResponseSchema),
  groups: v.optional(v.array(GroupResponseSchema)),
  pis: v.optional(v.array(UserResponseSchema)),
  reducers: v.optional(v.array(UserResponseSchema)),
  observers: v.optional(v.array(UserResponseSchema)),
  external_pi: v.nullish(v.string()),
  external_reducer: v.nullish(v.string()),
  external_observer: v.nullish(v.string()),
  comments: v.optional(v.array(CommentDetailResponseSchema)),
  annotations: v.optional(v.array(AnnotationDetailResponseSchema)),
});

/** A spectrum with the full payload the server can attach to it. */
export type SpectrumDetailResponse = v.InferOutput<
  typeof SpectrumDetailResponseSchema
>;

export const SpectrumGetQuerySchema = v.strictObject({
  includeOriginalFile: v.optional(v.boolean()),
  minimalPayload: v.optional(v.boolean()),
  observedBefore: v.nullish(v.string()),
  observedAfter: v.nullish(v.string()),
  modifiedBefore: v.nullish(v.string()),
  modifiedAfter: v.nullish(v.string()),
  objID: v.nullish(v.string()),
  instrumentIDs: v.nullish(v.string()),
  groupIDs: v.nullish(v.string()),
  followupRequestIDs: v.nullish(v.string()),
  assignmentIDs: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  label: v.nullish(v.string()),
  type: v.nullish(v.string()),
  commentsFilter: v.nullish(v.string()),
  commentsFilterAuthor: v.nullish(v.string()),
  commentsFilterBefore: v.nullish(v.string()),
  commentsFilterAfter: v.nullish(v.string()),
});

/** Query parameters for retrieving a single spectrum or multiple spectra. */
export type SpectrumGetQuery = v.InferOutput<typeof SpectrumGetQuerySchema>;

export const SpectrumPostSchema = v.strictObject({
  obj_id: v.string(),
  instrument_id: v.number(),
  observed_at: v.string(),
  wavelengths: v.array(v.number()),
  fluxes: v.array(v.number()),
  errors: v.nullish(v.array(v.number())),
  units: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  type: v.nullish(v.string()),
  label: v.nullish(v.string()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  followup_request_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
  group_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
  pi: v.nullish(v.array(v.number())),
  external_pi: v.nullish(v.string()),
  reduced_by: v.nullish(v.array(v.number())),
  external_reducer: v.nullish(v.string()),
  observed_by: v.nullish(v.array(v.number())),
  external_observer: v.nullish(v.string()),
});

/** Payload for posting a spectrum. */
export type SpectrumPost = v.InferOutput<typeof SpectrumPostSchema>;

export const SpectrumPostBodySchema = v.strictObject({
  wavelengths: v.nullish(v.array(v.nullable(v.number()))),
  fluxes: v.nullish(v.array(v.nullable(v.number()))),
  errors: v.nullish(v.array(v.nullable(v.number()))),
  units: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  observed_at: v.nullish(v.string()),
  pi: v.nullish(v.array(v.number())),
  external_pi: v.nullish(v.string()),
  reduced_by: v.nullish(v.array(v.number())),
  external_reducer: v.nullish(v.string()),
  observed_by: v.nullish(v.array(v.number())),
  external_observer: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  type: v.nullish(v.string()),
  label: v.nullish(v.string()),
  instrument_id: v.nullish(v.number()),
  group_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
  followup_request_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
});

/** Request body for uploading/updating a spectrum (see SpectrumPost). */
export type SpectrumPostBody = v.InferOutput<typeof SpectrumPostBodySchema>;

export const SpectrumPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when uploading a spectrum. */
export type SpectrumPostResponse = v.InferOutput<
  typeof SpectrumPostResponseSchema
>;

export const SpectrumRangeGetQuerySchema = v.strictObject({
  instrument_ids: v.optional(v.array(v.number())),
  min_date: v.nullish(v.string()),
  max_date: v.nullish(v.string()),
});

/** Query parameters for retrieving spectra within a date range. */
export type SpectrumRangeGetQuery = v.InferOutput<
  typeof SpectrumRangeGetQuerySchema
>;

export const SpectrumUpdateSchema = v.strictObject({
  obj_id: v.nullish(v.string()),
  instrument_id: v.nullish(v.number()),
  observed_at: v.nullish(v.string()),
  wavelengths: v.nullish(v.array(v.number())),
  fluxes: v.nullish(v.array(v.number())),
  errors: v.nullish(v.array(v.number())),
  units: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  type: v.nullish(v.string()),
  label: v.nullish(v.string()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  followup_request_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
  group_ids: v.optional(v.union([v.array(v.number()), v.string(), v.null()])),
  pi: v.nullish(v.array(v.number())),
  external_pi: v.nullish(v.string()),
  reduced_by: v.nullish(v.array(v.number())),
  external_reducer: v.nullish(v.string()),
  observed_by: v.nullish(v.array(v.number())),
  external_observer: v.nullish(v.string()),
});

/** Payload for updating a spectrum; every field is optional. */
export type SpectrumUpdate = v.InferOutput<typeof SpectrumUpdateSchema>;

export const SyntheticPhotometryPostBodySchema = v.strictObject({
  filters: v.nullish(v.array(v.string())),
});

/** Request body for creating synthetic photometry from a spectrum. */
export type SyntheticPhotometryPostBody = v.InferOutput<
  typeof SyntheticPhotometryPostBodySchema
>;

export const _SpectrumBaseResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  obj: v.nullish(v.record(v.string(), v.unknown())),
  observed_at: v.nullish(v.string()),
  wavelengths: v.optional(v.array(v.number())),
  fluxes: v.optional(v.array(v.number())),
  errors: v.nullish(v.array(v.number())),
  units: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  type: v.nullish(v.string()),
  label: v.nullish(v.string()),
  instrument_id: v.nullish(v.number()),
  instrument: v.nullish(InstrumentResponseSchema),
  instrument_name: v.nullish(v.string()),
  telescope_id: v.nullish(v.number()),
  telescope_name: v.nullish(v.string()),
  followup_request_id: v.nullish(v.number()),
  assignment_id: v.nullish(v.number()),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  original_file_string: v.nullish(v.string()),
  original_file_filename: v.nullish(v.string()),
  owner_id: v.nullish(v.number()),
  owner: v.nullish(UserResponseSchema),
  groups: v.optional(v.array(GroupResponseSchema)),
  pis: v.optional(v.array(UserResponseSchema)),
  reducers: v.optional(v.array(UserResponseSchema)),
  observers: v.optional(v.array(UserResponseSchema)),
  external_pi: v.nullish(v.string()),
  external_reducer: v.nullish(v.string()),
  external_observer: v.nullish(v.string()),
  comments: v.optional(v.array(CommentDetailResponseSchema)),
  annotations: v.optional(v.array(AnnotationDetailResponseSchema)),
});

/** A spectrum of a source. */
export type _SpectrumBaseResponse = v.InferOutput<
  typeof _SpectrumBaseResponseSchema
>;
