// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const StreamPatchBodySchema = v.strictObject({
  name: v.string(),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  auto_join: v.nullish(v.boolean()),
});

/** Request body for updating a stream. */
export type StreamPatchBody = v.InferOutput<typeof StreamPatchBodySchema>;

export const StreamPostBodySchema = v.strictObject({
  name: v.string(),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  auto_join: v.optional(v.boolean()),
});

/** Request body for creating a stream. */
export type StreamPostBody = v.InferOutput<typeof StreamPostBodySchema>;

export const StreamPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating a stream. */
export type StreamPostResponse = v.InferOutput<typeof StreamPostResponseSchema>;

export const StreamResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  name: v.string(),
  altdata: v.nullish(v.record(v.string(), v.unknown())),
  auto_join: v.nullish(v.boolean()),
});

/** An alert stream, e.g. a survey's public alerts. */
export type StreamResponse = v.InferOutput<typeof StreamResponseSchema>;

export const StreamUserPostBodySchema = v.strictObject({
  user_id: v.number(),
});

/** Request body for granting stream access to a user. */
export type StreamUserPostBody = v.InferOutput<typeof StreamUserPostBodySchema>;

export const StreamUserPostResponseSchema = v.object({
  stream_id: v.number(),
  user_id: v.number(),
});

/** Data payload returned when granting stream access to a user. */
export type StreamUserPostResponse = v.InferOutput<
  typeof StreamUserPostResponseSchema
>;
