// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const SummaryQueryMatchResponseSchema = v.strictObject({
  id: v.string(),
  score: v.nullish(v.number()),
  values: v.nullish(v.array(v.number())),
  sparseValues: v.nullish(v.record(v.string(), v.unknown())),
  metadata: v.nullish(v.record(v.string(), v.unknown())),
});

/**
 * One vector-store hit for a summary query (not a SkyPortal model).
 *
 * The shape is defined by the Pinecone client: when ``q`` is used the
 * handler rebuilds each hit as exactly ``id``, ``score`` and ``metadata``,
 * but when ``objID`` is used it passes the raw ``matches`` of the Pinecone
 * query response straight through, so the remaining fields are Pinecone's
 * ``ScoredVector`` attributes (``values``, ``sparse_values``, serialized as
 * ``sparseValues``). ``metadata`` holds whatever was indexed alongside the
 * summary (``redshift``, ``class``, ...), so it stays free-form.
 */
export type SummaryQueryMatchResponse = v.InferOutput<
  typeof SummaryQueryMatchResponseSchema
>;

export const SummaryQueryPostSchema = v.strictObject({
  q: v.nullish(v.string()),
  objID: v.nullish(v.string()),
  k: v.nullish(v.number()),
  z_min: v.nullish(v.number()),
  z_max: v.nullish(v.number()),
  classificationTypes: v.nullish(v.array(v.string())),
});

/** Payload for a source summary similarity search. */
export type SummaryQueryPost = v.InferOutput<typeof SummaryQueryPostSchema>;

export const SummaryQueryPostBodySchema = v.strictObject({
  q: v.nullish(v.string()),
  objID: v.nullish(v.string()),
  k: v.optional(v.number()),
  z_min: v.nullish(v.number()),
  z_max: v.nullish(v.number()),
  classificationTypes: v.nullish(v.array(v.string())),
});

/** Request body for a summary similarity search. */
export type SummaryQueryPostBody = v.InferOutput<
  typeof SummaryQueryPostBodySchema
>;

export const SummaryQueryPostResponseSchema = v.object({
  query_results: v.array(v.record(v.string(), v.unknown())),
});

/** Sources whose summaries match the query. */
export type SummaryQueryPostResponse = v.InferOutput<
  typeof SummaryQueryPostResponseSchema
>;

export const SummaryQueryResultsResponseSchema = v.strictObject({
  query_results: v.optional(v.array(SummaryQueryMatchResponseSchema)),
});

/** Results of a source summary similarity search. */
export type SummaryQueryResultsResponse = v.InferOutput<
  typeof SummaryQueryResultsResponseSchema
>;
