// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const DefaultSurveyEfficiencyPostBodySchema = v.strictObject({
  default_observationplan_request_id: v.number(),
  payload: v.nullish(v.record(v.string(), v.unknown())),
});

/** Request body for creating a default survey efficiency request. */
export type DefaultSurveyEfficiencyPostBody = v.InferOutput<
  typeof DefaultSurveyEfficiencyPostBodySchema
>;

export const DefaultSurveyEfficiencyPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating a default survey efficiency request. */
export type DefaultSurveyEfficiencyPostResponse = v.InferOutput<
  typeof DefaultSurveyEfficiencyPostResponseSchema
>;

export const SurveyEfficiencyForObservationPlanGetQuerySchema = v.strictObject({
  observation_plan_id: v.nullish(v.number()),
});

/** Query parameters for listing observation plan efficiency analyses. */
export type SurveyEfficiencyForObservationPlanGetQuery = v.InferOutput<
  typeof SurveyEfficiencyForObservationPlanGetQuerySchema
>;

export const SurveyEfficiencyForObservationsGetQuerySchema = v.strictObject({
  gcnevent_id: v.nullish(v.number()),
});

/** Query parameters for listing observation efficiency analyses. */
export type SurveyEfficiencyForObservationsGetQuery = v.InferOutput<
  typeof SurveyEfficiencyForObservationsGetQuerySchema
>;
