// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const DBInfoResponseSchema = v.strictObject({
  source_table_empty: v.nullish(v.boolean()),
  postgres_version: v.nullish(v.string()),
});

/** Basic health information about the instance's database. */
export type DBInfoResponse = v.InferOutput<typeof DBInfoResponseSchema>;

export const GitLogEntryResponseSchema = v.strictObject({
  time: v.nullish(v.string()),
  sha: v.nullish(v.string()),
  email: v.nullish(v.string()),
  description: v.nullish(v.string()),
  pr_nr: v.nullish(v.string()),
  pr_url: v.nullish(v.string()),
  commit_url: v.nullish(v.string()),
  name: v.nullish(v.string()),
});

/** One parsed commit from the deployed SkyPortal git log. */
export type GitLogEntryResponse = v.InferOutput<
  typeof GitLogEntryResponseSchema
>;

export const LogPostBodySchema = v.strictObject({
  error: v.nullish(v.string()),
  stack: v.nullish(v.string()),
});

/** Request body for logging a frontend error. */
export type LogPostBody = v.InferOutput<typeof LogPostBodySchema>;

export const SysInfoResponseSchema = v.strictObject({
  gitlog: v.optional(v.array(GitLogEntryResponseSchema)),
});

/** System and deployment information for the SkyPortal instance. */
export type SysInfoResponse = v.InferOutput<typeof SysInfoResponseSchema>;
