// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { GroupResponseSchema } from "./_cyclic.js";

export const ObjTagDeleteBodySchema = v.strictObject({
  group_ids: v.nullish(v.array(v.number())),
});

/**
 * Request body for removing group associations from an object-tag
 * association.
 */
export type ObjTagDeleteBody = v.InferOutput<typeof ObjTagDeleteBodySchema>;

export const ObjTagGetQuerySchema = v.strictObject({
  obj_id: v.nullish(v.string()),
  objtagoption_id: v.nullish(v.number()),
  includeSuperObjs: v.optional(v.boolean()),
});

/** Query parameters for listing object-tag associations. */
export type ObjTagGetQuery = v.InferOutput<typeof ObjTagGetQuerySchema>;

export const ObjTagOptionPatchBodySchema = v.strictObject({
  name: v.string(),
  color: v.nullish(v.string()),
});

/** Request body for updating a tag option. */
export type ObjTagOptionPatchBody = v.InferOutput<
  typeof ObjTagOptionPatchBodySchema
>;

export const ObjTagOptionPostBodySchema = v.strictObject({
  name: v.string(),
  color: v.nullish(v.string()),
});

/** Request body for creating a tag option. */
export type ObjTagOptionPostBody = v.InferOutput<
  typeof ObjTagOptionPostBodySchema
>;

export const ObjTagOptionResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  name: v.nullish(v.string()),
  color: v.nullish(v.string()),
});

/** A tag that can be applied to objects. */
export type ObjTagOptionResponse = v.InferOutput<
  typeof ObjTagOptionResponseSchema
>;

export const ObjTagPostBodySchema = v.strictObject({
  objtagoption_id: v.number(),
  obj_id: v.string(),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for creating an object-tag association. */
export type ObjTagPostBody = v.InferOutput<typeof ObjTagPostBodySchema>;

export const ObjTagPostResponseSchema = v.strictObject({
  id: v.nullish(v.number()),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  objtagoption_id: v.nullish(v.number()),
  author_id: v.nullish(v.number()),
  groups: v.nullish(v.array(v.record(v.string(), v.unknown()))),
  message: v.nullish(v.string()),
});

/**
 * Result of creating an object-tag association.
 *
 * A brand-new association comes back in full; adding groups to one that
 * already exists returns only id and message, and adding nothing returns
 * an empty result.
 */
export type ObjTagPostResponse = v.InferOutput<typeof ObjTagPostResponseSchema>;

export const ObjTagResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  objtagoption_id: v.nullish(v.number()),
  author_id: v.nullish(v.number()),
  objtagoption: v.nullish(ObjTagOptionResponseSchema),
  groups: v.nullish(v.array(GroupResponseSchema)),
  obj: v.nullish(v.record(v.string(), v.unknown())),
  author: v.nullish(v.record(v.string(), v.unknown())),
  name: v.nullish(v.string()),
  total_group_count: v.nullish(v.number()),
});

/**
 * An object-tag association.
 *
 * Handlers that assemble the payload by hand add name (the tag option's
 * name) and, on the internal endpoints, total_group_count.
 */
export type ObjTagResponse = v.InferOutput<typeof ObjTagResponseSchema>;
