// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const TaxonomyPostSchema = v.strictObject({
  name: v.string(),
  version: v.string(),
  hierarchy: v.nullish(v.record(v.string(), v.unknown())),
  hierarchy_file: v.nullish(v.string()),
  group_ids: v.nullish(v.array(v.number())),
  provenance: v.nullish(v.string()),
  isLatest: v.optional(v.boolean()),
});

/** Payload for creating a taxonomy. */
export type TaxonomyPost = v.InferOutput<typeof TaxonomyPostSchema>;

export const TaxonomyPostBodySchema = v.strictObject({
  name: v.string(),
  version: v.string(),
  hierarchy: v.nullish(v.record(v.string(), v.unknown())),
  hierarchy_file: v.nullish(v.string()),
  group_ids: v.nullish(v.array(v.number())),
  provenance: v.nullish(v.string()),
  isLatest: v.optional(v.boolean()),
});

/** Request body for posting a new taxonomy. */
export type TaxonomyPostBody = v.InferOutput<typeof TaxonomyPostBodySchema>;

export const TaxonomyPostResponseSchema = v.object({
  taxonomy_id: v.number(),
});

/** Data payload returned when posting a taxonomy. */
export type TaxonomyPostResponse = v.InferOutput<
  typeof TaxonomyPostResponseSchema
>;

export const TaxonomyPutSchema = v.strictObject({
  name: v.nullish(v.string()),
  version: v.nullish(v.string()),
  provenance: v.nullish(v.string()),
  isLatest: v.nullish(v.boolean()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Payload for updating a taxonomy. */
export type TaxonomyPut = v.InferOutput<typeof TaxonomyPutSchema>;

export const TaxonomyPutBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  version: v.nullish(v.string()),
  provenance: v.nullish(v.string()),
  isLatest: v.nullish(v.boolean()),
  group_ids: v.nullish(v.array(v.number())),
  hierarchy: v.nullish(v.record(v.string(), v.unknown())),
});

/** Request body for updating a taxonomy. */
export type TaxonomyPutBody = v.InferOutput<typeof TaxonomyPutBodySchema>;
