// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const TeamGroupResponseSchema = v.strictObject({
  id: v.number(),
  name: v.nullish(v.string()),
  nickname: v.nullish(v.string()),
});

/** A group belonging to a team, as assembled by the team handler. */
export type TeamGroupResponse = v.InferOutput<typeof TeamGroupResponseSchema>;

export const TeamMemberResponseSchema = v.strictObject({
  id: v.number(),
  username: v.nullish(v.string()),
  first_name: v.nullish(v.string()),
  last_name: v.nullish(v.string()),
});

/** A user who is a member of one of a team's groups. */
export type TeamMemberResponse = v.InferOutput<typeof TeamMemberResponseSchema>;

export const TeamPostSchema = v.strictObject({
  name: v.string(),
  nickname: v.nullish(v.string()),
  description: v.nullish(v.string()),
  primary_color: v.nullish(v.string()),
  secondary_color: v.nullish(v.string()),
  logo_url: v.nullish(v.string()),
  background_url: v.nullish(v.string()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Payload for creating a team. */
export type TeamPost = v.InferOutput<typeof TeamPostSchema>;

export const TeamPostBodySchema = v.strictObject({
  name: v.string(),
  nickname: v.nullish(v.string()),
  description: v.nullish(v.string()),
  primary_color: v.nullish(v.string()),
  secondary_color: v.nullish(v.string()),
  logo_url: v.nullish(v.string()),
  background_url: v.nullish(v.string()),
  group_ids: v.optional(v.array(v.number())),
});

/** Request body for creating a team. */
export type TeamPostBody = v.InferOutput<typeof TeamPostBodySchema>;

export const TeamPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating a team. */
export type TeamPostResponse = v.InferOutput<typeof TeamPostResponseSchema>;

export const TeamPutSchema = v.strictObject({
  name: v.nullish(v.string()),
  nickname: v.nullish(v.string()),
  description: v.nullish(v.string()),
  primary_color: v.nullish(v.string()),
  secondary_color: v.nullish(v.string()),
  logo_url: v.nullish(v.string()),
  background_url: v.nullish(v.string()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Payload for updating a team. */
export type TeamPut = v.InferOutput<typeof TeamPutSchema>;

export const TeamPutBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  nickname: v.nullish(v.string()),
  description: v.nullish(v.string()),
  primary_color: v.nullish(v.string()),
  secondary_color: v.nullish(v.string()),
  logo_url: v.nullish(v.string()),
  background_url: v.nullish(v.string()),
  group_ids: v.nullish(v.array(v.number())),
});

/** Request body for updating a team. */
export type TeamPutBody = v.InferOutput<typeof TeamPutBodySchema>;

export const TeamPutResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when updating a team. */
export type TeamPutResponse = v.InferOutput<typeof TeamPutResponseSchema>;

export const TeamResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  name: v.nullish(v.string()),
  nickname: v.nullish(v.string()),
  description: v.nullish(v.string()),
  primary_color: v.nullish(v.string()),
  secondary_color: v.nullish(v.string()),
  logo_url: v.nullish(v.string()),
  background_url: v.nullish(v.string()),
  groups: v.optional(v.array(TeamGroupResponseSchema)),
  num_members: v.nullish(v.number()),
  users: v.nullish(v.array(TeamMemberResponseSchema)),
});

/** A collaboration-level grouping of groups (``Team``). */
export type TeamResponse = v.InferOutput<typeof TeamResponseSchema>;

export const TeamsResponseSchema = v.strictObject({
  teams: v.optional(v.array(TeamResponseSchema)),
});

/** Every team the requesting user can access. */
export type TeamsResponse = v.InferOutput<typeof TeamsResponseSchema>;
