// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const TelescopeGetQuerySchema = v.strictObject({
  name: v.nullish(v.string()),
  latitudeMin: v.nullish(v.number()),
  latitudeMax: v.nullish(v.number()),
  longitudeMin: v.nullish(v.number()),
  longitudeMax: v.nullish(v.number()),
});

/** Query parameters for retrieving telescopes. */
export type TelescopeGetQuery = v.InferOutput<typeof TelescopeGetQuerySchema>;

export const TelescopePostSchema = v.strictObject({
  name: v.string(),
  nickname: v.string(),
  diameter: v.number(),
  lat: v.nullish(v.number()),
  lon: v.nullish(v.number()),
  elevation: v.nullish(v.number()),
  skycam_link: v.nullish(v.string()),
  weather_link: v.nullish(v.string()),
  robotic: v.optional(v.boolean()),
  fixed_location: v.nullish(v.boolean()),
});

/** Payload for creating a telescope. */
export type TelescopePost = v.InferOutput<typeof TelescopePostSchema>;

export const TelescopePostBodySchema = v.strictObject({
  name: v.string(),
  nickname: v.string(),
  diameter: v.number(),
  lat: v.nullish(v.number()),
  lon: v.nullish(v.number()),
  elevation: v.nullish(v.number()),
  mpc_obscode: v.nullish(v.string()),
  skycam_link: v.nullish(v.string()),
  weather_link: v.nullish(v.string()),
  robotic: v.optional(v.boolean()),
  fixed_location: v.nullish(v.boolean()),
  acknowledgment: v.nullish(v.string()),
});

/** Request body for creating a telescope. */
export type TelescopePostBody = v.InferOutput<typeof TelescopePostBodySchema>;

export const TelescopePostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when creating a telescope. */
export type TelescopePostResponse = v.InferOutput<
  typeof TelescopePostResponseSchema
>;

export const TelescopePutSchema = v.strictObject({
  name: v.nullish(v.string()),
  nickname: v.nullish(v.string()),
  diameter: v.nullish(v.number()),
  lat: v.nullish(v.number()),
  lon: v.nullish(v.number()),
  elevation: v.nullish(v.number()),
  skycam_link: v.nullish(v.string()),
  weather_link: v.nullish(v.string()),
  robotic: v.nullish(v.boolean()),
  fixed_location: v.nullish(v.boolean()),
});

/** Payload for updating a telescope. */
export type TelescopePut = v.InferOutput<typeof TelescopePutSchema>;

export const TelescopePutBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  nickname: v.nullish(v.string()),
  diameter: v.nullish(v.number()),
  lat: v.nullish(v.number()),
  lon: v.nullish(v.number()),
  elevation: v.nullish(v.number()),
  mpc_obscode: v.nullish(v.string()),
  skycam_link: v.nullish(v.string()),
  weather_link: v.nullish(v.string()),
  robotic: v.nullish(v.boolean()),
  fixed_location: v.nullish(v.boolean()),
  acknowledgment: v.nullish(v.string()),
});

/** Request body for updating a telescope. */
export type TelescopePutBody = v.InferOutput<typeof TelescopePutBodySchema>;
