// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const ThumbnailPathGetQuerySchema = v.strictObject({
  types: v.optional(v.array(v.string())),
  requiredDepth: v.optional(v.number()),
});

/** Query parameters for checking thumbnail paths. */
export type ThumbnailPathGetQuery = v.InferOutput<
  typeof ThumbnailPathGetQuerySchema
>;

export const ThumbnailPathPatchQuerySchema = v.strictObject({
  types: v.optional(v.array(v.string())),
  requiredDepth: v.optional(v.number()),
  pageNumber: v.optional(v.number()),
  numPerPage: v.optional(v.number()),
});

/**
 * Query parameters for updating thumbnail paths (same filters as the
 * check, plus pagination over the rows to move).
 */
export type ThumbnailPathPatchQuery = v.InferOutput<
  typeof ThumbnailPathPatchQuerySchema
>;

export const ThumbnailPathReportResponseSchema = v.strictObject({
  totalMatches: v.nullish(v.number()),
  inCorrectFolder: v.nullish(v.number()),
  inWrongFolder: v.nullish(v.number()),
  numMoved: v.nullish(v.number()),
});

/** Counts of thumbnails found in the correct and incorrect folders. */
export type ThumbnailPathReportResponse = v.InferOutput<
  typeof ThumbnailPathReportResponseSchema
>;

export const ThumbnailPostSchema = v.strictObject({
  obj_id: v.string(),
  data: v.string(),
  ttype: v.picklist([
    "new",
    "ref",
    "sub",
    "sdss",
    "dr8",
    "ls",
    "ps1",
    "sm",
    "hst",
    "chandra",
    "jwst",
    "new_gz",
    "ref_gz",
    "sub_gz",
  ]),
  survey: v.nullish(v.string()),
});

/** Payload for uploading a thumbnail. */
export type ThumbnailPost = v.InferOutput<typeof ThumbnailPostSchema>;

export const ThumbnailPostBodySchema = v.strictObject({
  obj_id: v.string(),
  data: v.string(),
  ttype: v.string(),
  survey: v.nullish(v.string()),
});

/** Request body for uploading a thumbnail. */
export type ThumbnailPostBody = v.InferOutput<typeof ThumbnailPostBodySchema>;

export const ThumbnailPostResponseSchema = v.object({
  id: v.number(),
});

/** Data payload returned when uploading a thumbnail. */
export type ThumbnailPostResponse = v.InferOutput<
  typeof ThumbnailPostResponseSchema
>;

export const ThumbnailPutBodySchema = v.strictObject({
  obj_id: v.nullish(v.string()),
  type: v.nullish(v.string()),
  file_uri: v.nullish(v.string()),
  public_url: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  is_grayscale: v.nullish(v.boolean()),
});

/** Request body for updating a thumbnail. */
export type ThumbnailPutBody = v.InferOutput<typeof ThumbnailPutBodySchema>;

export const ThumbnailResponseSchema = v.strictObject({
  id: v.number(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  obj_id: v.nullish(v.string()),
  type: v.nullish(
    v.picklist([
      "new",
      "ref",
      "sub",
      "sdss",
      "dr8",
      "ls",
      "ps1",
      "sm",
      "hst",
      "chandra",
      "jwst",
      "new_gz",
      "ref_gz",
      "sub_gz",
    ]),
  ),
  file_uri: v.nullish(v.string()),
  public_url: v.nullish(v.string()),
  origin: v.nullish(v.string()),
  survey: v.nullish(v.string()),
  is_grayscale: v.nullish(v.boolean()),
});

/** A thumbnail image centered on an object. */
export type ThumbnailResponse = v.InferOutput<typeof ThumbnailResponseSchema>;
