// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const ApiTokenResponseSchema = v.strictObject({
  id: v.string(),
  created_at: v.nullish(v.string()),
  modified: v.nullish(v.string()),
  created_by_id: v.nullish(v.number()),
  created_by: v.nullish(v.record(v.string(), v.unknown())),
  name: v.nullish(v.string()),
  acls: v.optional(v.array(v.record(v.string(), v.unknown()))),
});

/**
 * An API token (baselayer ``Token``).
 *
 * ``acls`` are the full ACL rows and ``created_by`` the owner's
 * ``User.to_dict()``, both eager-loaded by the token endpoints.
 */
export type ApiTokenResponse = v.InferOutput<typeof ApiTokenResponseSchema>;

export const TokenPostBodySchema = v.strictObject({
  name: v.string(),
  acls: v.array(v.string()),
  user_id: v.nullish(v.number()),
});

/** Request body for creating a new API token. */
export type TokenPostBody = v.InferOutput<typeof TokenPostBodySchema>;

export const TokenPostResponseSchema = v.object({
  token_id: v.string(),
});

/** ID of the newly created token. */
export type TokenPostResponse = v.InferOutput<typeof TokenPostResponseSchema>;

export const TokenPutBodySchema = v.strictObject({
  name: v.nullish(v.string()),
  acls: v.nullish(v.array(v.string())),
  user_id: v.nullish(v.number()),
});

/** Request body for updating a token. */
export type TokenPutBody = v.InferOutput<typeof TokenPutBodySchema>;
