// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";
import { UserResponseSchema } from "./_cyclic.js";

export const UserGetQuerySchema = v.strictObject({
  numPerPage: v.nullish(v.number()),
  pageNumber: v.optional(v.number()),
  firstName: v.nullish(v.string()),
  lastName: v.nullish(v.string()),
  username: v.nullish(v.string()),
  email: v.nullish(v.string()),
  role: v.nullish(v.string()),
  acl: v.nullish(v.string()),
  group: v.nullish(v.string()),
  stream: v.nullish(v.string()),
  slim: v.optional(v.boolean()),
  includeExpired: v.optional(v.boolean()),
  sortBy: v.optional(v.picklist(["username", "createdAt"])),
  sortOrder: v.optional(v.picklist(["asc", "desc"])),
});

/** Query parameters for listing users. */
export type UserGetQuery = v.InferOutput<typeof UserGetQuerySchema>;

export const UserPatchBodySchema = v.strictObject({
  expirationDate: v.nullish(v.string()),
  username: v.nullish(v.string()),
  first_name: v.nullish(v.string()),
  last_name: v.nullish(v.string()),
  contact_email: v.nullish(v.string()),
});

/** Request body for updating a user. */
export type UserPatchBody = v.InferOutput<typeof UserPatchBodySchema>;

export const UserPostSchema = v.strictObject({
  username: v.string(),
  first_name: v.nullish(v.string()),
  last_name: v.nullish(v.string()),
  affiliations: v.nullish(v.array(v.string())),
  contact_email: v.nullish(v.string()),
  contact_phone: v.nullish(v.string()),
  oauth_uid: v.nullish(v.string()),
  roles: v.nullish(v.array(v.string())),
  groupIDsAndAdmin: v.nullish(
    v.array(v.array(v.union([v.number(), v.boolean()]))),
  ),
});

/** Payload for adding a new user. */
export type UserPost = v.InferOutput<typeof UserPostSchema>;

export const UserPostBodySchema = v.strictObject({
  username: v.string(),
  first_name: v.nullish(v.string()),
  last_name: v.nullish(v.string()),
  affiliations: v.nullish(v.array(v.string())),
  contact_email: v.nullish(v.string()),
  contact_phone: v.nullish(v.string()),
  oauth_uid: v.nullish(v.string()),
  roles: v.optional(v.array(v.string())),
  groupIDsAndAdmin: v.optional(v.array(v.array(v.unknown()))),
});

/** Request body for adding a new user. */
export type UserPostBody = v.InferOutput<typeof UserPostBodySchema>;

export const UserPostResponseSchema = v.object({
  id: v.number(),
});

/** ID of the newly added user. */
export type UserPostResponse = v.InferOutput<typeof UserPostResponseSchema>;

export const UsersPageResponseSchema = v.strictObject({
  users: v.array(UserResponseSchema),
  totalMatches: v.number(),
});

/** One page of results from a users query. */
export type UsersPageResponse = v.InferOutput<typeof UsersPageResponseSchema>;
