// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
import * as v from "valibot";

export const WeatherGetQuerySchema = v.strictObject({
  telescope_id: v.nullish(v.number()),
});

/** Query parameters for retrieving weather at a telescope site. */
export type WeatherGetQuery = v.InferOutput<typeof WeatherGetQuerySchema>;

export const WeatherResponseSchema = v.strictObject({
  weather: v.nullish(v.record(v.string(), v.unknown())),
  weather_retrieved_at: v.nullish(v.string()),
  weather_fetch_at: v.nullish(v.string()),
  weather_link: v.nullish(v.string()),
  telescope_name: v.nullish(v.string()),
  telescope_nickname: v.nullish(v.string()),
  telescope_id: v.nullish(v.number()),
  message: v.nullish(v.string()),
});

/**
 * Cached OpenWeather data for a telescope site.
 *
 * The handler builds this dict by hand: ``weather`` is the raw OpenWeather
 * ``weather_info`` JSON blob, ``weather_retrieved_at`` is the Weather row's
 * ``retrieved_at``, and the remaining keys come off the associated Telescope.
 */
export type WeatherResponse = v.InferOutput<typeof WeatherResponseSchema>;
