#!/usr/bin/env python
"""Generate projects/js-client/src/models/ from the pydantic API models.

Each model in ``skyportal_py_models`` becomes a valibot schema plus the type
inferred from it, in a TypeScript module mirroring the python one, so the JS
client and the server validate against the same declared contract.

Pydantic's own JSON Schema is the intermediate representation: it already
resolves aliases, unions, literals and nested references, so this only has to
translate JSON Schema nodes to valibot. Schemas are emitted with field *aliases*
(the wire names), which is what both the server's ``model_validate`` and the
client see.

``model_config["extra"]`` decides the object's strictness, so whether an
unmodelled response field is fatal is a property of the pydantic model rather
than of this generator: ``forbid`` → ``v.strictObject``, ``allow`` →
``v.looseObject``, ``ignore`` (pydantic's default) → ``v.object``.

A model that takes part in a reference cycle cannot have its type inferred, so
those get an explicit type and a ``v.GenericSchema<T>`` annotation, with the
cycle's edges deferred through ``v.lazy``. Every cycle is contained in one
module (that is what ``_cyclic.py`` is for), so the emitted modules form a DAG
and import each other without initialisation-order hazards.
"""

from __future__ import annotations

import importlib
import json
import pkgutil
import re
import subprocess
from collections import defaultdict
from pathlib import Path
from typing import Any

import skyportal_py_models
from pydantic import BaseModel

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = REPO_ROOT / "projects" / "js-client" / "src" / "models"

HEADER = """// Generated by tools/build-js-models.py from projects/api-models -- DO NOT EDIT.
// Run `make js-models` to regenerate.
"""

# Pydantic's `extra` setting, as the valibot object variant with the same
# behaviour for unknown keys.
OBJECT_VARIANT = {
    "forbid": "v.strictObject",
    "allow": "v.looseObject",
    "ignore": "v.object",
}

IDENTIFIER = re.compile(r"[A-Za-z_$][A-Za-z0-9_$]*")


def discover() -> tuple[dict[str, Any], dict[str, str], dict[str, type[BaseModel]]]:
    """Return (schema by model name, module by model name, model classes)."""
    schemas: dict[str, Any] = {}
    module_of: dict[str, str] = {}
    classes: dict[str, type[BaseModel]] = {}

    for info in sorted(pkgutil.iter_modules(skyportal_py_models.__path__)):
        module = importlib.import_module(f"skyportal_py_models.{info.name}")
        for value in vars(module).values():
            if not (isinstance(value, type) and issubclass(value, BaseModel)):
                continue
            if value.__module__ != f"skyportal_py_models.{info.name}":
                continue  # imported for re-export; the defining module owns it
            name = value.__name__
            if name in module_of:
                raise SystemExit(
                    f"Duplicate model name {name}: "
                    f"{module_of[name]} and {info.name}. Model names are the "
                    "TypeScript export names, so they must be unique."
                )
            module_of[name] = info.name
            classes[name] = value

            schema = value.model_json_schema(by_alias=True, ref_template="{model}")
            defs = schema.pop("$defs", {})
            # A self-referential model's top level is a bare $ref into its $defs.
            own = defs.pop(name, None) if schema.get("$ref") == name else None
            schemas[name] = own if own is not None else schema
            for def_name, def_schema in defs.items():
                schemas.setdefault(def_name, def_schema)

    missing = set(schemas) - set(module_of)
    if missing:
        raise SystemExit(
            f"Referenced models with no defining module: {sorted(missing)}"
        )
    return schemas, module_of, classes


def refs_in(node: Any) -> set[str]:
    """Every model name `node` references, at any depth."""
    found: set[str] = set()
    if isinstance(node, dict):
        if isinstance(node.get("$ref"), str):
            found.add(node["$ref"])
        for value in node.values():
            found |= refs_in(value)
    elif isinstance(node, list):
        for value in node:
            found |= refs_in(value)
    return found


def strongly_connected(edges: dict[str, set[str]]) -> list[list[str]]:
    """Tarjan's SCCs, iteratively (the graph is wide, not deep)."""
    index: dict[str, int] = {}
    low: dict[str, int] = {}
    on_stack: set[str] = set()
    stack: list[str] = []
    components: list[list[str]] = []
    counter = 0

    for root in sorted(edges):
        if root in index:
            continue
        work = [(root, iter(sorted(edges[root])))]
        index[root] = low[root] = counter
        counter += 1
        stack.append(root)
        on_stack.add(root)
        while work:
            node, children = work[-1]
            descended = False
            for child in children:
                if child not in index:
                    index[child] = low[child] = counter
                    counter += 1
                    stack.append(child)
                    on_stack.add(child)
                    work.append((child, iter(sorted(edges[child]))))
                    descended = True
                    break
                if child in on_stack:
                    low[node] = min(low[node], index[child])
            if descended:
                continue
            work.pop()
            if work:
                low[work[-1][0]] = min(low[work[-1][0]], low[node])
            if low[node] == index[node]:
                component = []
                while True:
                    member = stack.pop()
                    on_stack.discard(member)
                    component.append(member)
                    if member == node:
                        break
                components.append(component)
    return components


class Emitter:
    """Translates one model's JSON Schema into valibot and TypeScript."""

    def __init__(self, schemas, module_of, classes, scc_of):
        self.schemas = schemas
        self.module_of = module_of
        self.classes = classes
        self.scc_of = scc_of

    def schema_expr(self, node: Any, owner: str, out_refs: set[str]) -> str:
        """valibot expression for a JSON Schema node, as seen from `owner`."""
        if node is True or node == {}:
            return "v.unknown()"
        if "$ref" in node:
            name = node["$ref"]
            out_refs.add(name)
            # Only a cycle needs deferring; everything else is already declared.
            if self.scc_of[name] == self.scc_of[owner]:
                return f"v.lazy(() => {name}Schema)"
            return f"{name}Schema"
        if "const" in node:
            return f"v.literal({json.dumps(node['const'])})"
        if "enum" in node:
            values = node["enum"]
            if len(values) == 1:
                return f"v.literal({json.dumps(values[0])})"
            return f"v.picklist([{', '.join(json.dumps(value) for value in values)}])"
        if "anyOf" in node or "oneOf" in node:
            members = node.get("anyOf") or node["oneOf"]
            # `T | None` is by far the commonest union; v.nullable reads better.
            others = [member for member in members if member.get("type") != "null"]
            if len(others) == 1 and len(others) < len(members):
                return f"v.nullable({self.schema_expr(others[0], owner, out_refs)})"
            rendered = [self.schema_expr(member, owner, out_refs) for member in members]
            return f"v.union([{', '.join(rendered)}])"

        node_type = node.get("type")
        if node_type == "string":
            return "v.string()"
        if node_type in ("integer", "number"):
            return "v.number()"
        if node_type == "boolean":
            return "v.boolean()"
        if node_type == "null":
            return "v.null()"
        if node_type == "array":
            items = node.get("items")
            inner = (
                "v.unknown()"
                if items is None
                else self.schema_expr(items, owner, out_refs)
            )
            return f"v.array({inner})"
        if node_type == "object":
            return self.object_expr(node, owner, out_refs)
        # No `type`: a field annotated `Any`.
        return "v.unknown()"

    def object_expr(self, node: Any, owner: str, out_refs: set[str]) -> str:
        properties = node.get("properties")
        if not properties:
            extra = node.get("additionalProperties")
            value = (
                "v.unknown()"
                if extra in (None, True)
                else self.schema_expr(extra, owner, out_refs)
            )
            return f"v.record(v.string(), {value})"

        required = set(node.get("required", []))
        variant = OBJECT_VARIANT[
            "forbid" if node.get("additionalProperties") is False else "ignore"
        ]
        entries = []
        for name, child in properties.items():
            expr = self.schema_expr(child, owner, out_refs)
            if name not in required:
                expr = (
                    f"v.nullish({expr[len('v.nullable(') : -1]})"
                    if expr.startswith("v.nullable(")
                    else f"v.optional({expr})"
                )
            key = name if IDENTIFIER.fullmatch(name) else json.dumps(name)
            entries.append(f"  {key}: {expr},")
        return variant + "({\n" + "\n".join(entries) + "\n})"

    def type_expr(self, node: Any, out_refs: set[str]) -> str:
        """Explicit TypeScript type, for models whose type cannot be inferred."""
        if node is True or node == {}:
            return "unknown"
        if "$ref" in node:
            out_refs.add(node["$ref"])
            return node["$ref"]
        if "const" in node:
            return json.dumps(node["const"])
        if "enum" in node:
            return " | ".join(json.dumps(value) for value in node["enum"])
        if "anyOf" in node or "oneOf" in node:
            members = node.get("anyOf") or node["oneOf"]
            return " | ".join(self.type_expr(member, out_refs) for member in members)

        node_type = node.get("type")
        if node_type == "string":
            return "string"
        if node_type in ("integer", "number"):
            return "number"
        if node_type == "boolean":
            return "boolean"
        if node_type == "null":
            return "null"
        if node_type == "array":
            items = node.get("items")
            inner = "unknown" if items is None else self.type_expr(items, out_refs)
            return f"({inner})[]" if re.search(r"[ |]", inner) else f"{inner}[]"
        if node_type == "object":
            properties = node.get("properties")
            if not properties:
                extra = node.get("additionalProperties")
                value = (
                    "unknown"
                    if extra in (None, True)
                    else self.type_expr(extra, out_refs)
                )
                return f"Record<string, {value}>"
            required = set(node.get("required", []))
            lines = []
            for name, child in properties.items():
                key = name if IDENTIFIER.fullmatch(name) else json.dumps(name)
                rendered = self.type_expr(child, out_refs)
                if name in required:
                    lines.append(f"  {key}: {rendered};")
                else:
                    # exactOptionalPropertyTypes: an absent key is `undefined`,
                    # and these types have to match what the schema infers.
                    lines.append(f"  {key}?: {rendered} | undefined;")
            return "{\n" + "\n".join(lines) + "\n}"
        return "unknown"


def docblock(schema: Any) -> list[str]:
    description = schema.get("description")
    if not description:
        return []
    lines = [line.rstrip() for line in description.strip().split("\n")]
    if len(lines) == 1:
        return [f"/** {lines[0]} */"]
    return ["/**", *[f" * {line}".rstrip() for line in lines], " */"]


def order_within(
    names: list[str], edges: dict[str, set[str]], scc_of: dict[str, int]
) -> list[str]:
    """Declaration order: dependencies first, cycles emitted together."""
    by_scc: dict[int, list[str]] = defaultdict(list)
    for name in names:
        by_scc[scc_of[name]].append(name)

    local = set(names)
    scc_edges: dict[int, set[int]] = defaultdict(set)
    for name in names:
        for ref in edges[name]:
            if ref in local and scc_of[ref] != scc_of[name]:
                scc_edges[scc_of[name]].add(scc_of[ref])

    ordered: list[str] = []
    seen: set[int] = set()

    def visit(component: int) -> None:
        if component in seen:
            return
        seen.add(component)
        for dependency in sorted(scc_edges[component]):
            visit(dependency)
        ordered.extend(sorted(by_scc[component]))

    for component in sorted(by_scc, key=lambda c: sorted(by_scc[c])):
        visit(component)
    return ordered


def main() -> None:
    schemas, module_of, classes = discover()
    edges = {name: refs_in(schema) for name, schema in schemas.items()}

    scc_of: dict[str, int] = {}
    recursive: set[str] = set()
    for identifier, component in enumerate(strongly_connected(edges)):
        for name in component:
            scc_of[name] = identifier
        if len(component) > 1 or component[0] in edges[component[0]]:
            recursive.update(component)

    by_module: dict[str, list[str]] = defaultdict(list)
    for name, module in module_of.items():
        by_module[module].append(name)

    emitter = Emitter(schemas, module_of, classes, scc_of)
    written = 0
    for module, names in sorted(by_module.items()):
        refs: set[str] = set()
        type_refs: set[str] = set()
        body: list[str] = []
        for name in order_within(sorted(names), edges, scc_of):
            schema = schemas[name]
            extra = classes[name].model_config.get("extra", "ignore")
            variant = OBJECT_VARIANT[extra]
            expression = emitter.schema_expr(schema, name, refs)
            # The top-level object's strictness comes from the model's config,
            # not from the `additionalProperties` the nested emitter sees.
            for default in OBJECT_VARIANT.values():
                if expression.startswith(default + "({"):
                    expression = variant + expression[len(default) :]
                    break
            if name in recursive:
                body += docblock(schema)
                body.append(
                    f"export type {name} = {emitter.type_expr(schema, type_refs)};\n"
                )
                body.append(
                    f"export const {name}Schema: v.GenericSchema<{name}> = {expression};\n"
                )
            else:
                body.append(f"export const {name}Schema = {expression};\n")
                body += docblock(schema)
                body.append(
                    f"export type {name} = v.InferOutput<typeof {name}Schema>;\n"
                )

        imports: dict[str, list[str]] = defaultdict(list)
        for ref in sorted(refs | type_refs):
            home = module_of[ref]
            if home == module:
                continue
            if ref in refs:
                imports[home].append(f"{ref}Schema")
            if ref in type_refs:
                imports[home].append(f"type {ref}")
        lines = [HEADER, 'import * as v from "valibot";\n']
        for home, symbols in sorted(imports.items()):
            lines.append(f'import {{ {", ".join(symbols)} }} from "./{home}.js";\n')
        lines.append("\n")
        (OUTPUT_DIR / f"{module}.ts").write_text("".join(lines) + "\n".join(body))
        written += 1

    index = [HEADER] + [
        f'export * from "./{module}.js";\n' for module in sorted(by_module)
    ]
    (OUTPUT_DIR / "index.ts").write_text("".join(index))

    # Same version as the prettier hook in .pre-commit-config.yaml, so that
    # committing generated output does not reformat it and trip the drift check.
    subprocess.run(
        [
            "bun",
            "x",
            "prettier@3.9.6",
            "--write",
            "--log-level",
            "warn",
            "--prose-wrap",
            "preserve",
            str(OUTPUT_DIR),
        ],
        check=True,
    )
    print(
        f"Wrote {len(module_of)} models ({len(recursive)} recursive) to "
        f"{written + 1} files in {OUTPUT_DIR.relative_to(REPO_ROOT)}"
    )


if __name__ == "__main__":
    main()
